### ISSUE TITLE
Relay stopped working with error unknown variant 'spanOperations', expected 'span_operations'`

### ISSUE THREAD

**Issue by holophil** [getsentry/relay#1001]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Relay 21.4.1 (via [dockerhub relay:latest](https://hub.docker.com/r/getsentry/relay/tags?page=1&ordering=last_updated&name=latest))

### Steps to Reproduce
Deploy relay 21.4.1 in managed mode.

### Expected Result
Relay executes without error logs.
Relay can fetch project states successfully (projectsconfig endpoint).

### Actual Result

Relay logs the following error
`ERROR: error fetching project state <redacted>: unknown variant 'spanOperations', expected 'span_operations'`

It seems that relay is not relaying any events to sentry SaaS anymore.

Probably caused by[ recent change in the projectsconfig endpoint](https://github.com/getsentry/sentry/pull/25886) release to sentry SaaS without releasing related [change on sentry relay](https://github.com/getsentry/relay/pull/993).

**Comment by untitaker** [comment]
Thanks and sorry, we're reverting the change at https://github.com/getsentry/sentry/pull/26082

**Comment by holophil** [comment]
Thank you for the fast response and action. :+1:

**Comment by untitaker** [comment]
Not closing until fix is deployed.

**Comment by untitaker** [comment]
We believe that the incident has been resolved. Let me know if it still occurs. Thanks and sorry again!
