### ISSUE TITLE
Unity events: parse `contexts.os.raw_description`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/relay#1004]
The API available to get the OS version on Unity returns a single string such as `Android OS 10 / API-29 (QKQ1.190716.003/2103022249)`. Is [this issue on the Unity SDK](https://github.com/getsentry/sentry-unity/issues/182) we agreed to send it as `raw_description`.

The Unity Lite SDK has been sending this as `os.name`. Could we add this parsing logic also in the event the `sdk.name=sentry.unity.lite`?

https://github.com/getsentry/sentry-unity-lite/blob/4b584f8d372c179aa4d6931f9fe386960273f4e8/Runtime/Sentry.cs#L281-L285

If that's not the case, we might as well reconsider this and parse in the SDK.

**Comment by jan-auer** [comment]
@bruno-garcia can you help me with this and find a list of possible values and their structure?

**Comment by bruno-garcia** [comment]
`Mac OS X 10.16.0` [Link](https://sentry.io/organizations/sentry-sdks/issues/2308319708/?project=5439417&statsPeriod=1h)
`iOS 14.6` [Link](https://sentry.io/organizations/sentry-sdks/issues/2314354823/?project=5439417&statsPeriod=1h)

I can give more examples but 'list of values' I'm not sure. Would it be enough we infer the format based on some examples for known platforms like desktop and mobile?

**Comment by bitsandfoxes** [comment]
A couple of additional examples we have so far:
- Android 
  - Android OS 10 / API-29 (QKQ1.191014.012/2010292059)
  - Android OS 11 / API-30 (RSR1.201211.001/7027799)

- Mac OS
  - Mac OS X 10.16.0

- Windows
  - Windows 10 (10.0.19042) 64bit
  - Windows 10 (10.0.17763) 64bit

- iOS
  - iOS 14.6

**Comment by bruno-garcia** [comment]
One proposal to tackle this is:

If the SDK name if: `sentry.unity.lite` or `sentry.dotnet.unity`:
If there's no `os.version` or `os.raw_description` but there's `os.name`, then:
Parse `os.name` against a few regex's to extra name+version. If we match the regex then move `os.name` into `os.raw_description` and use the new `name` and `version`.

We need to discuss whether in newer versions of the SDK (only the new one, `sentry.dotnet.unity`) we want move this raw info from `os.name` into `os.raw_description` (where it should belong). Then the logic needs to account for that: if we don't have `os.name` and `os.version` but do have `os.raw_description`... apply regex to create name+version (I believe we do that with .NET events already).

If we can agree with that, in the example of Android it would be:

Regex: `Android OS (?<version>(\d+)) \/ API-(?<api>(\d+))` 
We'd match: `Android OS 10 / API-29 (QKQ1.191014.012/2010292059)` 
And set `os.name=Android` and `os.version=10`.
API version ideally would be set as a tag: `android.api=29`.

With iOS: `iOS (?<version>([\d\.]+))` would match `iOS 14.6` and we'd get name and version.

`Mac OS X (?<version>([\d\.]+))` for `Mac OS X 10.16.0`.
I propose we finally use the right name: `os.name: macOS` but that would match whatever else is in the product captured. by other SDKs. `os.version: 10.16` (What about we drop the patch version if it's `.0`?)

Windows: `Windows (?<short_version>([\d\.]+)) \((?<long_version>([\d\.]+))\)`
Matching: `Windows 10 (10.0.19042) 64bit`

I believe we'd get better value by using the precise version, like:
`os.name: Windows` and `os.version: 10.0.19042`.

Not sure it's worth bothering with the architecture there which would go in `device.arch`. We could find that out in another way and set to the event.

**Comment by bruno-garcia** [comment]
This task now replaces the Unity repo issue: https://github.com/getsentry/sentry-unity/issues/41

**Comment by jan-auer** [comment]
This is being worked on now.

**Comment by bruno-garcia** [comment]
Done through: https://github.com/getsentry/relay/pull/1072
Thanks @RaduW
