### ISSUE TITLE
More verbose logging

### ISSUE THREAD

**Issue by fliespl** [getsentry/relay#1014]
I think it would be a valuable addition to provide switch that will allow more verbose logging to console.

Info about received event about sending to sentry instance, about connection errors.

**Comment by jan-auer** [comment]
This switch exists with the `logging.level` configuration field. For full verbosity, set this in your `config.yml`:

```yaml
logging:
  level: trace
```

There's more information on monitoring Relay [here](https://docs.sentry.io/product/relay/monitoring/) and the configuration [here](https://docs.sentry.io/product/relay/options/#logging).

**Comment by fliespl** [comment]
Omg... Thank you @jan-auer.

I was so obsessed looking for debug/verbose switch that I simply missed that one. Appreciate quick reply!
