### ISSUE TITLE
Release version with an unescaped string.

### ISSUE THREAD

**Issue by deissh** [getsentry/relay#1015]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

error when trying to open a release. also, when trying to delete via the API, it gives the answer that it was not found

![image](https://user-images.githubusercontent.com/21129524/115746569-1ad08c00-a39d-11eb-997d-980ce1e21e0e.png)

## Steps to Reproduce

1. create a new release
2. then you need to set the release version, for example, I have problems with this name `"\n> rfrontend@0.1.0 release:version\n> echo "dev-19be1b7e-dirty"\n\ndev-19be1b7e-dirty"` (forgot to escape the symbol in the bash script)

Good items to include here include:

```
vendor.f93d44c7de6da4a40abf.js:2 GET https://sentry.io/api/0/organizations/somename/sessions/?project=123456&query=release%3A%22%5Cn%3E+rfrontend%400.1.0+release%3Aversion%5Cn%3E+echo+%22dev-19be1b7e-dirty%22%5Cn%5Cndev-19be1b7e-dirty%22&field=sum(session)&statsPeriod=90d&interval=1d 400 (Bad Request)

{"detail":"Invalid query field: \"message\""}
```

**Comment by BYK** [comment]
Ping @getsentry/owners-releases-ui for triage. /cc @mitsuhiko @untitaker

**Comment by kamilogorek** [comment]
We could, but then it'd still be an issue for the API itself https://docs.sentry.io/api/releases/create-a-new-release-for-an-organization/ so when someone is using it directly, it'd fail even if sentry-cli would be fixed.

**Comment by jan-auer** [comment]
Relay itself has multiple methods to check release names. I would suggest to consolidate all of those into `sentry-release-parser` and then reuse them in place of the existing `is_valid_release` method, as well as during session processing.

**Comment by jan-auer** [comment]
Relay now has correct release validation.
