### ISSUE TITLE
Run integration tests against Sentry

### ISSUE THREAD

**Issue by armenzg** [getsentry/relay#1017]

**Comment by BYK** [comment]
This is what we do for now: https://github.com/getsentry/relay/blob/1a28c1d9df7a8da5de1058f630829d79007475fb/cloudbuild.yaml#L56-L73

Pretty sure we can extend that.

**Comment by armenzg** [comment]
Hi Burak, thanks for the pointer. I looked into it, however, I decided with Billy that it is preferable to follow a similar model as in the Sentry repo. The main reason is that it resembles a lot more to the testing set up that engineers are already familiar with rather than putting more work to make install.sh/test.sh the main testing method for engineers.

If you're interested I have a WIP in [here](https://github.com/getsentry/relay/pull/1034). I still have to validate and get customer feedback before I continue further down to completion.
