### ISSUE TITLE
Using Git submodules prevents caching Docker layers

### ISSUE THREAD

**Issue by armenzg** [getsentry/relay#1048]
CC: @BYK @RaduW @jan-auer @untitaker 

In the Docker build process, the step that takes the longest to execute is the one that we cannot cache because we include `.git` in Docker's build context. The `.git` directory always changes every time we commit, however, the files that are processed as part of `make build-linux-release` (`cargo build --release --locked --features ${RELAY_FEATURES} --target=${TARGET}`) [1].

See the code:
https://github.com/getsentry/relay/blob/fba39474ec9d5d1ce941797d9927d71087053b6d/.dockerignore#L3-L4:

This is not a major issue unless we want to make running Sentry integration tests faster. Fixing this could potentially save 8 minutes from integration tests and the release process (This step takes 50% of the current GCB build which includes e2e tests).

If we moved dealing with git submodules inside of a directory level we could avoid including `.git` inside of `.dockerignore`. Dropping the usage of git submodules altogether would also help.

Code that added submodules for `uap-core`:
https://github.com/getsentry/relay/commit/e65b5336fb858a9ed7a0ecc6b5cf3a7a4360f4d8

[1]
```
13 [relay-deps 3/3] WORKDIR /work
#13 CACHED

#15 [relay-builder 1/5] COPY --from=sentry-cli /bin/sentry-cli /bin/sentry-c...
#15 DONE 0.1s

#17 [relay-builder 2/5] COPY . .
#17 DONE 0.1s

#18 [relay-builder 3/5] RUN make build-linux-release TARGET=x86_64-unknown-l
```

**Comment by BYK** [comment]
Yeah, copying in all the files or definitely changing files like the `.git` directory into a container image is an anti-pattern. I think a better approach would be to adopt the `builder` pattern we have over at getsentry/sentry:

Build a `builder` image first with minimal to no changes across project revisions (unless dependencies change), mount the current working directory into the container instance of this builder image, run it to produce build artifacts. If you need a docker image as a build artifact too, add the binaries produced in the previous stage to a core runtime image.

See the pattern here: https://github.com/getsentry/sentry/blob/master/docker/cloudbuild.yaml

**Comment by jan-auer** [comment]
Why would you like to cache the builder image? Sources change with almost every commit, too. We do cache the dependencies stage.

**Comment by BYK** [comment]
If you are including `.git` in your docker image there's really no good reason to be using Docker. The builder image can still be cached as we do over at getsentry/sentry which speeds up things tremendously as installing the same dependencies over and over is not very fast, especially with Rust. And by caching, we are not talking about full caching but at least caching certain layers.

**Comment by jan-auer** [comment]
We have a `relay-deps` stage for that reason, so the only thing the builder stage does is executing the build step itself, and that must run every time because of code changes. The final stage doesn't include `.git` again.

**Comment by BYK** [comment]
Could we use https://github.com/facebookincubator/cargo-guppy to help with this process?

**Comment by jan-auer** [comment]
Potentially, yes. @andriisoldatenko also discovered [`cargo-chef`](https://github.com/LukeMathWalker/cargo-chef) which would help with caching dependency builds.

**Comment by jan-auer** [comment]
Going to close this in favor of a GHA-based docker build.
