### ISSUE TITLE
Running Sentry integration tests should support testing against non-Docker Relay

### ISSUE THREAD

**Issue by armenzg** [getsentry/relay#1050]
As part of the work in #1017 we discovered that we can only run integration tests against Relay within a Docker container.
Waiting on the Docker build to run Sentry integration tests takes a long time (over 10 minutes before we can run the tests).

Another benefit of this work is that Relay developers would be able to easily run Sentry integration tests against their local Relay changes or even test locally changes required to both Relay and Sentry.

**Comment by jan-auer** [comment]
Relay's docker builds are now moving to GitHub actions, which allows us to utilize caches between builds. Through this, we should be able to speed them up significantly, which will also improve test times. This keeps the test setup closer to the development environment and also production.
