### ISSUE TITLE
Make Sentry integration tests a required check

### ISSUE THREAD

**Issue by armenzg** [getsentry/relay#1052]
This will prevent merging PRs that break integration tests with Sentry.
Please :)

**Comment by untitaker** [comment]
Yup, but can we wait a bit and see how it performs and if it's flaky or anything?

**Comment by armenzg** [comment]
Sounds good!

**Comment by jan-auer** [comment]
Tests have been stable so far, so I think we can move ahead with this. However, I noticed that they take considerably longer than all other tests, tripling the time we need to wait for CI now. Is there a way to speed them up before we make this required?

**Comment by armenzg** [comment]
It would not be a trivial amount of work. This is a problem we face across the board.

**Comment by jan-auer** [comment]
_"Sentry-Relay Integration Tests"_ is a required check now.
