### ISSUE TITLE
.yaml support

### ISSUE THREAD

**Issue by k0t3n** [getsentry/relay#1094]
Please add `config.yaml` besides `config.yml` to config recognition and other YAML files. This is gonna save hundreds of hours debugging.

**Comment by BYK** [comment]
This should be easy to submit a PR for, would you be interested?

**Comment by untitaker** [comment]
If both files exist, which is preferred?

**Comment by k0t3n** [comment]
@untitaker I think that in this case an error should be raised, but have not looked at the code yet.
@BYK ok, I'll try to see what I can do with it this weekend.

UPD: sorry guys, no way to dig into Rust in the near future :(

**Comment by jan-auer** [comment]
Thanks for the update. We'll happily accept a PR for this in the future.

In the meanwhile, please use `.yml` as the documentation states.

**Comment by iker-barriocanal** [comment]
Relay uses `yml` as the primary extension, and there's no reason to also support `yaml`, so closing this issue.
