### ISSUE TITLE
error processing envelope: could not schedule project fetch caused by: Mailbox has closed

### ISSUE THREAD

**Issue by drook** [getsentry/relay#1095]
### Environment
Sentry 21.6.3
Relay 21.6.3
Snuba 21.6.3

Issue:
-----
After certain load treshold relay is failing to a state that it's not able to recover from, until restarted (by the way the exact same behavior is there at least from 20.8.0):

===Cut===
[...]
Sep 29 06:25:52 jsentry relay[62139]: 2021-09-29T06:25:52Z [relay_server::actors::upstream] INFO: relay successfully registered with upstream
Sep 29 06:26:07 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:26:07 jsentry relay[62139]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Sep 29 06:26:07 jsentry relay[62139]: 2021-09-29T06:26:07Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:26:07 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:26:09 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:26:09 jsentry relay[62139]: 2021-09-29T06:26:09Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:26:09 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:26:09 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:26:09 jsentry relay[62139]: 2021-09-29T06:26:09Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:26:09 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:26:09 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:26:09 jsentry relay[62139]: 2021-09-29T06:26:09Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:26:09 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:26:09 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:26:09 jsentry relay[62139]: 2021-09-29T06:26:09Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:26:09 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:27:23 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:27:23 jsentry relay[62139]: 2021-09-29T06:27:23Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:27:23 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:27:24 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:27:24 jsentry relay[62139]: 2021-09-29T06:27:24Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:27:24 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:27:25 jsentry relay[62139]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:316:5
Sep 29 06:27:25 jsentry relay[62139]: 2021-09-29T06:27:25Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:27:25 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:27:25 jsentry relay[62139]: 2021-09-29T06:27:25Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:27:25 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:27:26 jsentry relay[62139]: 2021-09-29T06:27:26Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
Sep 29 06:27:26 jsentry relay[62139]:   caused by: Mailbox has closed
Sep 29 06:27:27 jsentry relay[62139]: 2021-09-29T06:27:27Z [relay_server::actors::envelopes] ERROR: error processing envelope: could not schedule project fetch
===Cut===

**Comment by untitaker** [comment]
Once there's a panic the mailbox is closed, and we appear to panic in a debug_assert in datascrubbing/pii.

We have a backlog item for the debug assertion at https://getsentry.atlassian.net/browse/INGEST-109, but: You are running a debug-build of relay. This is very unlikely to lead to acceptable performance. I assume you compiled relay yourself to obtain such a build, please run `cargo build --release` instead.

**Comment by drook** [comment]
Thanks a lot, will try it.

**Comment by drook** [comment]
Well, results are disappointing:
`cargo build --all-features` produces an unstripped binary of 90 megs and it's reliable.
`cargo build --all-features --release` or, `cargo build --release --features=ssl,processing`, like in Dockerfile/Makefile,  produces an unstripped binary of 430 megs and... yeah, it's able to start but it doesn't process events at all, complaining in logs almost about everything:

````
Oct  1 00:45:02 jsentry relay[37323]: 2021-09-30T21:45:02Z [relay_server::actors::envelopes] ERROR: error processing envelope: envelope exceeded its configured lifetime
````

or

````
Oct  1 00:37:09 jsentry relay[37323]: 2021-09-30T21:37:09Z [relay_server::actors::upstream] INFO: registering with upstream (http://10.100.33.18:9000/)
Oct  1 00:37:09 jsentry relay[37323]: 2021-09-30T21:37:09Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
Oct  1 00:37:09 jsentry relay[37323]:   caused by: error sending request for url (http://10.100.33.18:9000/api/0/relays/register/response/): connection closed before message completed
````
or

````
Oct  1 00:45:17 jsentry relay[37323]: 2021-09-30T21:45:17Z [relay_server::actors::envelopes] ERROR: error processing envelope: failed to resolve project information
Oct  1 00:45:17 jsentry relay[37323]:   caused by: failed to fetch project state from upstream
````

and these errors are reproducible across restarts. The idea to build a release version looks totally reasonable but the resulting binary just doesn't look like it, because it's not working. Currently I'm back to the debug one.

By the way, from what I see in Cargo.toml, the debug one isn't the debug one, and this matches perfectly to the binaries size:

````Cargo.toml
[profile.dev]
# Debug information slows down the build and increases caches in the
# target folder, but we don't require stack traces in most cases.
debug = false

[profile.release]
# In release, however, we do want full debug information to report
# panic and error stack traces to Sentry.
debug = true
````

**Comment by jjbayer** [comment]
@drook Do you know what event was sent to relay that caused the `'assertion failed: replacement_chunks.is_empty()'`? If so, could you share the event JSON payload with us?

**Comment by drook** [comment]
Unfortunately, no. In case I will get this on 21.8.x or recenter versions, could you please point me in direction of how can I pin down this event to report it here ?

**Comment by jjbayer** [comment]
@drook The only way I can think of is logging the entire `state` here:
https://github.com/getsentry/relay/blob/29176f8106a46d68e34cd1e7005ffca92f27b0cb/relay-server/src/actors/envelopes.rs#L1535
Be aware that you might be logging sensitive user data.

We will fix this bug for debug builds. Please run a release build in the mean time (I see you already opened a follow-up issue in https://github.com/getsentry/relay/issues/1096).
