### ISSUE TITLE
after DB outage or long kafka/DB desync where's no way to tell that Kafka queues needs to be flushed

### ISSUE THREAD

**Issue by drook** [getsentry/relay#1097]
### Environment
SentryRelay/Snuba 21.8.0, dedockerized, self-hosted.

### Steps to Reproduce
Install relay. Configure it, start to flow events from applications. Get relay or database down for some time, or get DB and Kafka state descync with some other method (say, components are to slow to consume kafka queues).
Then restore missing functionality or performance of components.

Reproducible at least from 10.x.

### Expected Result
Events should start flowing back.

### Actual Result
Nothing happends.
No new events are showing in the sentry web portal.

There's no way to tell that kafka queues should be flushing. Noone it complaining about anything in logs. And thats' a huge issue - you have to know the internals. Actually, "no new events are flowing" is no. 1 question in forums. This situation should be diagnozeable via logs. Yup, not only DB/Kafka desync (if I'm naming it correctly, doubt that) can be the root cause - also relay/snuba not running or relay not registering on the sentry can be the cause along many others, but in general all these states should be readable from logs, and at this time only few are.

**Comment by jjbayer** [comment]
@drook could you narrow this down to one specific scenario? Not sure if this problem can be fixed in Relay though. How would Relay know that Kafka topics are not being consumed? Or what information would you like to appear in Relay logs, specifically?

**Comment by BYK** [comment]
@drook it is not clear what your ask is here. Do you want more documentation? Do you need something else?

>And thats' a huge issue - you have to know the internals.

I mean, that's part of the deal with self-hosted?
