### ISSUE TITLE
Need help with configuring relay sentry setup with proxy

### ISSUE THREAD

**Issue by vinaysarode** [getsentry/relay#1138]
I want to connect relay to sentry.io via proxy service/application.
Please help me in this I am not able to find any way to put proxy between relay and sentry.

Config.yml
relay:
mode: managed
upstream: “https://sentry.io/”
host: 0.0.0.0
port: 3000
tls_port: ~
tls_identity_path: ~
tls_identity_password: ~

Where I have to set the proxy in relay?

**Comment by untitaker** [comment]
you need to configure the `https_proxy` variable to intercept SSL connections: https://stackoverflow.com/questions/58559109/difference-between-http-proxy-and-https-proxy/61248144
