### ISSUE TITLE
Default value for `protocol::Level` contradicts docs

### ISSUE THREAD

**Issue by relaxolotl** [getsentry/relay#1160]
According to the [docs on event payloads](https://develop.sentry.dev/sdk/event-payloads/#optional-attributes), the default value for an event's level is `error`. I could be misinterpreting the intended target of these documents, but it looks like the default value used by relay is `info`, which directly contradicts that:

https://github.com/getsentry/relay/blob/754266b5a50ac495fbc3c2ba89d9c14c45bf476b/relay-general/src/protocol/types.rs#L611-L615

This works out fairly well in practice as the spec does not explicitly state what the expected level for transactions should be; Any transactions coming from SDKs that omit levels on those are then being assigned a default level of `info` instead of `error`. Understandably it does not make sense for transactions to be an `error`, since their intended purpose isn't directly related to errors.

I'd mostly like to just start a discussion about this difference between the spec and relay, and to figure out whether this should be fixed on relay itself, or in the docs.

**Comment by untitaker** [comment]
Those are two action items for the ingest team before we can have a discussion about desired behavior:

* Investigate whether we even *can* remove level from transaction schema without de-facto breakage.
* The `Default` impl likely has no correlation with what we actually set as default during event processing -- maybe just remove `Default` to avoid confusion, or make actual use of it.

**Comment by untitaker** [comment]
For employees, see https://getsentry.atlassian.net/browse/INGEST-796

**Comment by jan-auer** [comment]
> Investigate whether we even can remove level from transaction schema without de-facto breakage.

Do we even have to remove it from schema, or would it be enough if we remove it during normalization? 

> The Default impl likely has no correlation with what we actually set as default during event processing

The default was actually intended to be the default level for "default" events, that is, plain message events. Error events override this default as error. However, now normalization does something completely different.

https://github.com/getsentry/relay/blob/bc6914f7da9ec2e5764414c0a18ec618f5f62ecf/relay-general/src/store/normalize.rs#L487-L490

This was introduced in https://github.com/getsentry/relay/pull/585, and see the commit history and comments for some more context.

**Comment by jan-auer** [comment]
We're closing this as we would like to keep the level as-is. The inconsistency is noted, however there are parts in the processing pipeline that still rely on the level being set. If those places are changed, we can also touch defaults in Relay.
