### ISSUE TITLE
relay ERROR: error processing envelope: failed to resolve project information   caused by: failed to fetch project state from upstream

### ISSUE THREAD

**Issue by fadeinflames** [getsentry/relay#1162]
there is a problem with setting up the sentry relay on a separate server
log:
```
2021-12-21T16:31:48Z [relay_server::actors::envelopes] ERROR: error processing envelope: failed to resolve project information
  caused by: failed to fetch project state from upstream
2021-12-21T16:31:48Z [relay_server::actors::envelopes] ERROR: error processing envelope: failed to resolve project information
  caused by: failed to fetch project state from upstream
2021-12-21T16:31:48Z [relay_server::actors::envelopes] ERROR: error processing envelope: failed to resolve project information
  caused by: failed to fetch project state from upstream
2021-12-21T16:31:48Z [relay_server::actors::envelopes] ERROR: error processing envelope: failed to resolve project information
  caused by: failed to fetch project state from upstream
2021-12-21T16:31:48Z [relay_server::actors::envelopes] ERROR: error processing envelope: failed to resolve project information
  caused by: failed to fetch project state from upstream
2021-12-21T16:31:48Z [relay_server::actors::envelopes] ERROR: error processing envelope: failed to resolve project information
  caused by: failed to fetch project state from upstream
2021-12-21T16:31:48Z [relay_server::actors::envelopes] ERROR: error processing envelope: failed to resolve project information
  caused by: failed to fetch project state from upstream
2021-12-21T16:31:48Z [relay_server::actors::envelopes] ERROR: error processing envelope: failed to resolve project information
  caused by: failed to fetch project state from upstream
2021-12-21T16:31:48Z [relay_server::actors::envelopes] ERROR: error processing envelope: failed to resolve project information
  caused by: failed to fetch project state from upstream
2021-12-21T16:31:48Z [relay_server::actors::envelopes] ERROR: error processing envelope: failed to resolve project information
  caused by: failed to fetch project state from upstream
```

my compose:
```
relay:
  mode: managed
  upstream: "https://fqnd-to-my-sentry/"
  host: 0.0.0.0
  port: 3000
cache:
  event_expiry: 86400
logging:
  level: debug
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "kafka:9092"}
    - {name: "message.max.bytes", value: 50000000} # 50MB
  redis: redis://redis:6379
 
```

what could be the reason for this error? exactly the same relay standing on the same server as the web - works fine

**Comment by jan-auer** [comment]
Are you setting up Relay as part of a Sentry setup similar to ~https://github.com/getsentry/single-tenant~ https://github.com/getsentry/self-hosted (processing mode) or would you like to put it in front of a Sentry installation (managed mode)? The configuration you supplied suggests that you are setting up a Sentry processing Relay, but at the same time you have a HTTPS upstream which suggests managed mode.

**Comment by fadeinflames** [comment]
@jan-auer ty for the answer
I want to set up a sentry relay on another server, as a proxy, to send events to sentry on-premise
with the ability to limit the number of events
btw - ur link - 404

**Comment by priscilawebdev** [comment]
Thanks for opening this issue @fadeinflames 

The link provided by Jan is indeed broken, but perhaps this document can help you https://docs.sentry.io/product/relay/modes/

Anyway, we've added this issue to our backlog and we'll check it out soon.

**Comment by jan-auer** [comment]
> btw - ur link - 404

Fixed, it should go to https://github.com/getsentry/self-hosted.

> I want to set up a sentry relay on another server, as a proxy [...]

Please have a look at the instructions at https://docs.sentry.io/product/relay/getting-started/#initializing-configuration. You are providing `processing` configuration, which is not valid for your use case. If you remove it, Relay will be able to connect to Sentry.

> [...] this document can help you https://docs.sentry.io/product/relay/modes/

This is important, too. In "managed" mode, you need to add your Relay's public key to Sentry like described [here](https://docs.sentry.io/product/relay/getting-started/#registering-relay-with-sentry). Proxy mode does not require this.

**Comment by fadeinflames** [comment]
@jan-auer 
okay, sorry, I incorrectly expressed
the task - I have a sentry-selfhosted on server in DC-1 (dc - datacenter)
and I want to put a relay in DC-2 so that requests go to her, and she transmits them to the selfhosted center
according to this scheme, it does not work
what am I doing wrong? it seems to me or the relay should be on the same server with sentry and there is no other way?

**Comment by jan-auer** [comment]
Understood, thanks for the clarification. In that case, you'll want to configure the Relay running in DC-2 without the entire `processing` configuration object. Your `relay.yml` file should roughly look like this:

```yaml
relay:
  mode: managed
  upstream: "https://fqnd-to-my-sentry/"
  host: 0.0.0.0
  port: 3000
cache:
  event_expiry: 86400
logging:
  level: debug
# no processing
```

NB, in a production environment, I'd strongly suggest switching to `info` log level.

**Comment by fadeinflames** [comment]
@jan-auer ty
and in this mode, the relay will be able to limit the number of events? it seems that in this mode she skips them all and the limits in the projects do not work

**Comment by jan-auer** [comment]
Relay will apply the limits from the upstream that are configured there, yes.

I recommend you configure nginx (part of the self-hosted package) with rate limits, although there's also ways to configure this directly in Sentry. https://github.com/getsentry/sentry/pull/33197 will add better ways to control this, right now you can set a global rate limit through [`system.rate-limit`](https://github.com/getsentry/sentry/blob/8af7940509eadcd21c33b5c6f7a19c09f62556c2/src/sentry/options/defaults.py#L22).
