### ISSUE TITLE
Initialize broken using docker-compose 2.2.3

### ISSUE THREAD

**Issue by aminvakil** [getsentry/relay#1169]
### Environment

How do you use Sentry?
self-hosted/on-premise (nightly)

Which SDK and version?
Irrelevant

### Steps to Reproduce

1. Trying to Bump docker-compose 2.2.3 on sentry self-hosted repository
More info can be found on the PR itself:
https://github.com/getsentry/self-hosted/pull/1251

### Expected Result

Tests pass.

### Actual Result

I think somehow relay is not picking up credentials as it should be.

Also please do note that I'm currently using 21.12.0 myself without a problem using docker-compose 2.2.3 on my environment.

**Comment by aminvakil** [comment]
Please note that I have tested with other docker-compose versions (2.0.1, 2.1.1, 2.2.1, 2.2.2) as well and this only happens with 2.2.3 :eyes: 
https://github.com/getsentry/self-hosted/pull/1251#issuecomment-1015357276

**Comment by untitaker** [comment]
Relay does not interface with docker-compose at all. This is categorically an issue with self-hosted, and should be handled there (seems like it already is)

Checking burak's comment, if there are issues with relay's CLI that make it hard/fragile to produce valid YAML, or if there's something wrong with Relay's Dockerfile, it makes sense to open an issue here. Not sooner.
