### ISSUE TITLE
Documentation for data scrubbing in static and proxy mode

### ISSUE THREAD

**Issue by laurenz-glueck** [getsentry/relay#1173]
Currently there is no documentation about how to configure data scrubbing when you run the relay in `static` or `proxy` mode.

Therefore the only way to do data scrubbing on a relay is by using the `managed` mode which is only available in Sentry SaaS Business and Enterprise plan.

I was already in contact with the SaaS support and they told me that it is in general possible to do data scrubbing in `static` and `proxy` mode. But unfortunately the documentation for the configuration is not done yet. As I'm now already waiting several months for the documentation, I decided to open this issue.

It would be nice if someone could add this documentation sooner than later :)

Nevertheless I would be happy to get a hint where I should look in the code to find out how the data scrubbing can be configured...

**Comment by jjbayer** [comment]
@laurenz-glueck there's no plan to add data scubbing to Relay's _product_ documentation any time soon, because the format is still subject to change. That said, it is not impossible to configure it, so if you want to experiment with it, here's some pointers:
https://docs.sentry.io/product/relay/projects/
https://getsentry.github.io/relay/relay_general/pii/struct.DataScrubbingConfig.html
https://github.com/getsentry/relay/blob/1215d198236f942842861a434c930f4d5b5bb935/relay-server/src/actors/project.rs#L78

You should be able to add a key `datascrubbingSettings` to your local project config.

**Comment by laurenz-glueck** [comment]
@jjbayer Thanks for your response! And also the informations regarding the documentation. I was in contact with Rodolfo from the support team. Unfortunately he did not mention that the format is subject to change and that this is the reason why there is no documentation yet...

I have already looked into the code and tried something like this:
```
 "datascrubbing_settings": {
  "exclude_fields": [],
  "scrub_data": true,
  "scrub_ip_addresses": true,
  "sensitive_fields": [
    "email",
    "password",
    "firstName",
    "lastName",
    "fullName",
    "initials",
    "shortName",
    "name",
    "street",
    "houseNumber",
    "zip",
    "city"
  ],
  "scrub_defaults": true
}
```

But now I'm a bit confused as you call the key `datascrubbingSettings` and not `datascrubbing_settings`?

In the link you have shared (https://getsentry.github.io/relay/relay_general/pii/struct.DataScrubbingConfig.html) the keys are also with an underscore and not camelcase.

Maybe you could quickly confirm what the right format is? :) 

Thanks!

**Comment by jjbayer** [comment]
Camel case is the correct format in JSON. See this line: https://github.com/getsentry/relay/blob/1215d198236f942842861a434c930f4d5b5bb935/relay-general/src/pii/legacy.rs#L20

**Comment by laurenz-glueck** [comment]
I have just tested it with camel case and it seems to work well 👍🏼 

Thanks for your help :)

**Comment by jjbayer** [comment]
Perfect!
