### ISSUE TITLE
Issue when running sentry relay behind a corporate firewall

### ISSUE THREAD

**Issue by andre-dsm-poly** [getsentry/relay#1193]
### Environment

I have sentry-rely setup in a docker container (using getsentry/relay:latest) behind a nginx reverse proxy running on an on-premise server at a client site. This server sits behind a firewall on which the client uses TLS interception, so an amended root certificate has been provided by them.

### Steps to Reproduce

So, reproducing this is going to hard as to do as the issue only occurs when behind a client's firewall. I can run the exact same sentry-relay/nginx combination locally and have events appear on sentry.io.

### Actual Result

When run on the client infrastructure, the relay queries upstream state and processes events but then fails to post. See logs below:

![image](https://user-images.githubusercontent.com/70684423/155245480-dffa48d9-c660-4dd5-8d99-3cb4dddfd003.png)

I have hunch that this is because the event post to upstream hits a "request insecure" error which then gets masked by the relay's "Network outage" error.

This could then be fixed by adding:

`.add_root_certificate(cert)` when `reqwest_client` is built in `UpstreamRelay` by streaming in a file in the same way that is used for `tls_identity_path`

Thoughts?

**Comment by jan-auer** [comment]
The `native-tls` crate used inside will use the system's trust root by default, such as the ones provided by the `ca-certificates` package on Debian/Ubuntu. Is there a way you could put that certificate there?

**Comment by andre-dsm-poly** [comment]
Great suggestion. This worked... tyvm. <3
