### ISSUE TITLE
Support scaling on web containers

### ISSUE THREAD

**Issue by wmellema** [getsentry/relay#1218]
In our deployment of self-hosted sentry we're running into CPU limits on the web(backend) container. We'd like to be able to scale those web containers to our needs, but the relay is not responding to the round-robin DNS that docker provides by default.

**Comment by jjbayer** [comment]
Hi @wmellema, could you elaborate on "relay is not responding"? Could you share some details on how to reproduce this problem (sentry version, relay version, config, logs, ...)?

**Comment by wmellema** [comment]
Hi @jjbayer.

We're using the default configuration of the complete sentry stack. All normal configuration within the docker containers. Main sentry project is version 20.6.0

What we've tried is to add the `--scale web=2` parameter to the normal docker-compose command in order to scale up the backend installations. This causes dockers internal DNS to round-robin between 2 web instances. 

However, the sentry-relay doesn't appear to honour those changes in IP adress.

**Comment by wmellema** [comment]
I retract this statement :) Relay is just fine, it's the regular nginx config that doesn't do round-robin configuration
