### ISSUE TITLE
Support rate limiting for envelope item type profile

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/relay#1258]
Relay should support rate limiting for envelope item types profile. Add a new data category for profile and the attribution logic.

**Comment by jjbayer** [comment]
@jan-auer @phacops do I understand correctly that https://github.com/getsentry/relay/pull/1259 will take care of this?

**Comment by phacops** [comment]
@jjbayer yes, #1259 is meant to take care of this.

**Comment by philipphofmann** [comment]
Can we also update the develop docs, please once we merge this https://develop.sentry.dev/sdk/rate-limiting/#definitions and https://develop.sentry.dev/sdk/envelopes/#data-model?

**Comment by jjbayer** [comment]
@philipphofmann made a good point about updating the dev docs, maybe someone from @getsentry/profiling can take that?

**Comment by philipphofmann** [comment]
Related develop docs PR https://github.com/getsentry/develop/pull/803
