### ISSUE TITLE
Map Android model to product name

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/relay#1297]
### Problem Statement

For reference: https://github.com/jaredrummler/AndroidDeviceNames

Came up internally:

> They would like to see the Android device name (i.e., Samsung Galaxy), rather than device model number for their Discover results (not sure what field they’re referring to exactly). They have to do an additional step right now to google these model names. Is it possible to translate the device model number to a name inside the product?

### Solution Brainstorm

Instead of increasing the size of the SDK with this mapping that would ultimately get outdated all the time, we could do this on the backend. We need to get ingest folks involved on this one.

**Comment by marandaneto** [comment]
Yep, definitely should be done on the server.

**Comment by saintpepsicola** [comment]
I love this 🚀. Thank you !

**Comment by jjbayer** [comment]
Is the suggestion that we compile [this database](https://storage.googleapis.com/play_public/supported_devices.html) into Relay, and then map the column "Model" (e.g. SAMSUNG-SM-G930A) to the column "Marketing Name" (e.g. "Galaxy S7")?

**Comment by marandaneto** [comment]
@jjbayer yes, there's also this https://storage.googleapis.com/play_public/supported_devices.csv so we can choose where to pull from the data, mapping ideally during ingestion?

**Comment by jan-auer** [comment]
We're leaning towards compiling this into Relay, as this will make operating Relay easy. Before we do this, we need to check the license of this file.

**Comment by marandaneto** [comment]
@jan-auer @TBS1996 Double check if MDX has not started working on this, I recall them asking about this, I might be wrong tho.
