### ISSUE TITLE
Too many 400 Bad Request

### ISSUE THREAD

**Issue by yayapao** [getsentry/relay#1336]
### Environment

self-hosted/on-premise and relay version is **relay-21.6.3**

Which SDK and version?

JavaScript v6.13.3

### Steps to Reproduce

1. Start a relay server online
2. Config relay info on sentry
3. Client report transaction by envelope api

### Expected Result

Less 400 http code for response

### Actual Result

Too many 400 http code, almost 90%

```
[relay_server::actors::envelopes] ERROR: failed to extract security report: invalid security report type
[relay_server::actors::envelopes] ERROR: failed to extract security report: invalid security report type
[relay_server::actors::envelopes] ERROR: failed to extract security report: invalid security report type
[relay_server::actors::envelopes] ERROR: failed to extract security report: invalid security report type
[relay_server::actors::envelopes] ERROR: failed to extract security report: invalid security report type
[relay_server::actors::envelopes] ERROR: failed to extract security report: invalid security report
  caused by: invalid value: integer `-1226665688`, expected u64 at line 1 column 1685
```

It's there any way to do with it or some solutions?

Have a great day, bro!

**Comment by iker-barriocanal** [comment]
I see support for client reports, introduced in https://github.com/getsentry/relay/pull/1081, is available from `v21.9.0`, see [changelog](https://github.com/getsentry/relay/releases/tag/21.9.0). Upgrade relay to at least `v21.9.0` to have this support, and open a new issue if you find any trouble or continue seeing too many `400` responses.

I recommend upgrading your JavaScript SDK to the latest version and taking advantage of the v7 features, such as a smaller bundle size. See [v6 to v7 migration guide](https://github.com/getsentry/sentry-javascript/blob/master/MIGRATION.md#upgrading-from-6x-to-7x).

**Comment by untitaker** [comment]
@iker-barriocanal this is about CSP/security reports, which we have open tickets for

**Comment by yayapao** [comment]
Thanks, i will try upgrade relay to latest version and see response status. Hope all 200/201

**Comment by yayapao** [comment]
> Thanks, i will try upgrade relay to latest version and see response status. Hope all 200/201

Solved!
