### ISSUE TITLE
UA reduction is resulting in Chrome versions being matched as IPs, breaking agent detection

### ISSUE THREAD

**Issue by tiedotguy** [getsentry/relay#1375]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry.javascript.react, 7.8.1

### Steps to Reproduce

Regular usage, with regular users, on the latest Chrome

### Expected Result

UAs are processed normally, and browser detection is successfully done based on it

### Actual Result

UAs have the version redacted as they match the IP regex

-----

With [UA reduction](https://www.chromium.org/updates/ua-reduction/), Chromium user-agents are being transformed from, eg, `103.0.5060.140` to `103.0.0.0`.  This results in the relay redacting the UA string as it matches the IP regex:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[ip] Safari/537.36`

This results in the browser being detected as Safari rather than Chrome.

**Comment by untitaker** [comment]
thanks for the detailed diagnostics, this makes sense and we'll file it internally. can't yet give an ETA as to when this will be fixed. can you confirm that disabling datascrubbing/default scrubbers fixes this issue?

**Comment by untitaker** [comment]
we may fix this when #1366 and related PRs land, because then user-agent parsing might run before datascrubbing.

**Comment by tiedotguy** [comment]
Hi

Unfortunately we're not in a position to disable data scrubbing due to compliance and all that fun stuff.  Regarding #1366, is the UA detection handled in the relay? It sounds like there may be two potential data flows:

1. `browser -> sentry -> redact -> UA`, which becomes `browser -> sentry -> UA -> redact`
2. `browser -> relay -> redact -> sentry -> redact -> UA`, which becomes `browser -> relay -> redact -> sentry -> UA -> redact`

The second may still fail if the UA detection is done by Sentry after the relay.

**Comment by untitaker** [comment]
both datascrubbing and user agent parsing are done in relay, and now user agent parsing is done before datascrubbing. please check again if this is still a problem

**Comment by tiedotguy** [comment]
Hi, quick update on this - we got the update out yesterday and confirmed it's working.
