### ISSUE TITLE
Future Proof Relay

### ISSUE THREAD

**Issue by tobias-wilfert** [getsentry/relay#1424]
The general idea is to future-proof Really by updating the Actors to:
- Work with the standard [Futures](https://doc.rust-lang.org/stable/std/future/trait.Future.html) instead of the former `futures` crate.
- No longer work with [`actix`](https://docs.rs/actix/0.13.0/actix/) internally.
- Refer to Actors as Services.

**General Refactor:**

- [X] #1362
- [X] #1405
  - [X] #1415
- [x] #1421
- [x] #1457 ([gist](https://gist.github.com/jan-auer/68305125c13aaab7355a1c99b3b65012))
- [x] #1495
- [x] Fix uses `SleepHandle` with redundant `reset()` (requires https://github.com/getsentry/relay/pull/1485)
- [x] #1492
- [x] #1498
- [x] #1610
- [x] #1611
- [x] #1613
- [x] #1614
- [ ] #1458

**Actor Migration:**

- [X] #1349
  - [X] #1377
- [X] #1397
- [x] #1441
- [x] #1470
- [x] #1479 
- [x] #1485
- [ ] #1497
- [x] #1605
- [x] #1607
- [x] #1602
- [x] #1603
- [x] #1604
- [x] #1606
- [x] #1608
- [X] #1508 

_**Note:** this list is neither complete nor definitive and might be subject to change._

**Comment by jan-auer** [comment]
Let's close this, this is now being tracked in this milestone:
https://github.com/getsentry/relay/milestone/2
