### ISSUE TITLE
Data scrubbing should filter sensitive headers such as `Set-Cookie`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/relay#1501]
[OkHttp defines](https://github.com/square/okhttp/blob/58ee1ce170c2aea75a113012956260873e808dad/okhttp/src/commonMain/kotlin/okhttp3/internal/-UtilCommon.kt#L194-L200) its own sensitive headers.
Some of them are filtered by Relay already, but not all of them.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie

Not all HTTP clients respect that `Set-Cookie` should not be accessible.

`Cookie` is just removed from the headers list instead of being `[Filtered]`, most likely because there's a high-level property `Request#cookies` already.

<img width="655" alt="Screenshot 2022-09-27 at 10 46 02" src="https://user-images.githubusercontent.com/5731772/192478851-207e7d81-df89-4ba4-b118-035afa925f35.png">

**Comment by untitaker** [comment]
the request interface of an event is for http request headers, set-cookie is a response header. generally we are filtering header names iirc

**Comment by marandaneto** [comment]
We're trying to use the `request` property for all the merged headers (request, response), but since there's this limitation plus a few other ones, I will reconsider that.
I'll leave that up to you if you still wanna run scrubbing or not, there's also the inconsistency of `Cookie` being removed instead of filtered.

**Comment by jjbayer** [comment]
I suggest we put this hold until we've completed the RFC on where to put response data in the event payload.

**Comment by untitaker** [comment]
>We're trying to use the request property for all the merged headers (request, response), but since there's this limitation plus a few other ones, I will reconsider that.

I would definitely not do that. Which RFC are we talking about?

**Comment by marandaneto** [comment]
@untitaker I'm going to write an RFC that adds `Event.response` or `Event.contexts.response`, data structure similar to `event.request` but with additional fields such as `status_code`, etc...
Data scrubbing would need to give a pass in the `headers` field, etc.

**Comment by untitaker** [comment]
@marandaneto sounds good. there is potential for a lot of pii there so i think we should think about designing new default scrubbing rules in the same vein.

**Comment by marandaneto** [comment]
> @marandaneto sounds good. there is potential for a lot of pii there so i think we should think about designing new default scrubbing rules in the same vein.

https://github.com/getsentry/rfcs/pull/22

**Comment by marandaneto** [comment]
Closing in favor of https://github.com/getsentry/rfcs/pull/22
`Request #headers[Cookie]` is removed from the list because it's set to the high-level field `cookies` if found.
`Set-Cookie` isn't scrubbed because it's a response header and it should not be set in the first place.
Response headers go to the Response interface -> https://github.com/getsentry/rfcs/pull/22
