### ISSUE TITLE
Spurious failures from GCB for gh-pages branch

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/relay#1532]
Hey team, just noticed in passing that [the `relay-branch-push` trigger](https://console.cloud.google.com/cloud-build/triggers;region=global/edit/9d0218a6-21ba-4106-939c-474d55a922d6?project=sentryio) in GCB is configured to fire for any branch, but there is no `cloudbuild.yml` on the `gh-pages` branch, resulting in build failures. Not the biggest deal but did add a touch of noise when debugging other build failures.

**Comment by jjbayer** [comment]
Thanks @chadwhitacre. I changed the exclusion regex to `^(release-library\/.+)|(gh-pages)$`, hope that that does the trick.
