### ISSUE TITLE
custom metrics query return empty response

### ISSUE THREAD

**Issue by TonyGui7** [getsentry/relay#1546]
### Environment

Relay 22.10.0

### Steps to Reproduce

- config "organizations:dashboards-mep" flag to sentry.conf.py file;
- config relay project configuration with json file below
![896F55EA-A403-40D6-AB47-CA38D9A83F74](https://user-images.githubusercontent.com/19777415/197702023-ae00fb1e-649e-4c06-899f-a6053346c087.png)

- start service

- report custom metrics with key code below
```
ISpan span = Sentry.getSpan();
span.setMeasurement("video_prepare", preparingTime, MeasurementUnit.Duration.MILLISECOND)

```
- Server receive event in performance panel, but I can not find "measurement.video_prepare" metrics while creating custom widget
   
![0278EC87-0B22-431B-B40B-BFC03032B823](https://user-images.githubusercontent.com/19777415/197704234-869382d8-f68b-4abd-b07b-9b087345eba6.png)

- debug [sentry web code](https://github.com/getsentry/sentry),  request for custom metrics get empty response
    
![23DBBBA8-698B-4E0B-B10F-30FA4ACE9EA7](https://user-images.githubusercontent.com/19777415/197703367-66341f66-c230-4e92-92f1-9a2e620b3362.png)

### Expected Result

request for custom metrics should get response that has "video_prepare" metric like below
![AFE7BD36-A083-48B4-BF78-FF6289C6FD8C](https://user-images.githubusercontent.com/19777415/197703801-4ec8b6f2-c145-4098-8a67-0cd410ec85a4.png)

### Actual Result

request for custom metrics get empty response

**Comment by iker-barriocanal** [comment]
Hi there. Are you able to see/query other metrics, and that's the only one that fails? Since you're running your own relay, do you have a full self-hosted setup, or are you using Sentry SaaS?

**Comment by TonyGui7** [comment]
> Hi there. Are you able to see/query other metrics, and that's the only one that fails? Since you're running your own relay, do you have a full self-hosted setup, or are you using Sentry SaaS?

Yes, I am able to see all of the built-in metrics like app_cold_start etc&, it's just the custom metrics that I can't see. 
I am using self-hosted. Since I can't see custom metric "video_prepare" that I report with default configuration, I read the sentry web code and relay code and I modify three files below
![91B7754E-57B4-426B-B5FA-38355F58FBAB](https://user-images.githubusercontent.com/19777415/197920650-7fd4bb5b-5bbc-426c-82e9-a2a9d4e198fd.png)

- modify /relay/config.yml. file
   
![83A5F99C-B4DD-41B0-A673-607A8F16221D](https://user-images.githubusercontent.com/19777415/197921896-2b8adbc8-ea30-4cec-a8a0-0badf4ff7ccd.png)

- add /relay/projects/2.json  file
   the screenshot is posted above in "Step to Reproduce" section
- modify /sentry/sentry.conf.py. file
![7667EFDE-51E0-4C8F-A045-9E3257B44B0E](https://user-images.githubusercontent.com/19777415/197922130-cde62fca-6f0d-4cac-99b4-5e406c85e075.png)
   by the way, I add all of the flags that I find in sentry source code and this screenshot just show part of that

**Comment by iker-barriocanal** [comment]
Are you also on v22.10.0 for all the other components, or is it just relay? What version of sentry are you running?

**Comment by TonyGui7** [comment]
> Are you also on v22.10.0 for all the other components, or is it just relay? What version of sentry are you running?

I use self-hosted with tag 22.10.0 to deploy service and the environment config shows that the version of sentry, snuba and relay is 22.10.0
![B76F09C0-D6E0-4659-9458-65B6D46D6217](https://user-images.githubusercontent.com/19777415/199011478-98ba4381-2bdc-4acf-a9c0-5de5c1589e54.png)

![5E9BEC34-8CC8-4A97-800D-21A4A24CF281](https://user-images.githubusercontent.com/19777415/199011806-709e987b-d595-4d66-97e3-364902544d32.png)

by the way, here are issues I post for the same problem, which may be useful for your analysis

https://github.com/getsentry/self-hosted/issues/1769

https://github.com/getsentry/sentry/issues/40240

**Comment by iker-barriocanal** [comment]
William answers [here](https://github.com/getsentry/sentry/issues/40240#issuecomment-1287083636) -- dynamic sampling, the feature custom metrics is part of, isn't supported yet for self-hosted.

Thanks for opening the issue, but I'll close it since it isn't actionable in Relay at the moment. Stay tuned!
