### ISSUE TITLE
Message production error: MessageTimedOut (Local: Message timed out)

### ISSUE THREAD

**Issue by bumarcell** [getsentry/relay#1572]
I'm running Sentry in k8s with relay. A few days ago I updated to v22.10 (through a helm-chart update) and since then I'm getting the following error from relay:
`[relay_server::utils::kafka] ERROR: failed to produce message to Kafka (delivery callback): Message production error: MessageTimedOut (Local: Message timed out)`

I tried raising message.timeout.ms to 1000000 (~17min). After restart relay started listening for connection for about 17min then it jumped into the same error again and got stuck in it with ~2sec interval (as before raising the timeout)
I also tried increasing all timeouts but that didn't help neither.

My current config:
`
relay:
  mode: managed
  upstream: "http://sentry-prod-web:9000/"
  host: 0.0.0.0
  port: 3000

processing:
  enabled: true

  kafka_config:
    - name: "bootstrap.servers"
      value: "sentry-prod-kafka:9092"
    - name: "message.max.bytes"
      value: 50000000  # 50MB or bust
    # below configs trying to solve the problem
    - name: "message.timeout.ms"
      value: 1000000
    - name: request.timeout.ms
      value: 900000
    - name: "delivery.timeout.ms"
      value: 1000000
    - name: api.version.request.timeout.ms
      value: 300000
  redis: "redis://:@sentry-prod-sentry-redis-master:6379"
`
It has network access to Kafka and the cluster seems to work just fine. 
Any idea on how can I fix it?

Thanks 🙏

**Comment by jjbayer** [comment]
Hi @bumarcell, what helm chart are you using? A similar issue was reported ~2 years ago, let me know if that thread helps you at all: https://github.com/getsentry/self-hosted/issues/687.

**Comment by bumarcell** [comment]
@jjbayer Thanks for your answer. I found out later that I do have some Kafka issues, which when got resolved fixed the relay issue.
