### ISSUE TITLE
Transaction name parsing rule spec

### ISSUE THREAD

**Issue by HazAT** [getsentry/relay#1596]
Write a document with the spec on how a rule looks like, the protocol to send it between different services, and anything else that’s also relevant.

The spec must also contain a clear section on what this milestone changes, so that other teams and non-technical people (such as product managers) can quickly find and understand the consequences of the initiative without diving into (technical) details.

- [x] Requires #1598

**Comment by iker-barriocanal** [comment]
[doc](https://www.notion.so/sentry/Transaction-name-normalization-changes-42516662dc684a9abcc8d0aa2212396c)
