### ISSUE TITLE
Add hardcoded transaction name parsing rules to relay

### ISSUE THREAD

**Issue by HazAT** [getsentry/relay#1597]
The goal is to ship something from which we can already get value and learn from it. The rule spec will probably look different than this initial iterations; that’s expected and they will be adapted to match the spec.

**Details**

* Replace UUIDs, git SHAs and numerical IDs in transaction names by placeholders. 

**Acceptance Criteria**

* The `transaction` tag on transaction metrics is transformed.
* The `transaction` field of the Dynamic Sampling Context (and its FieldValueProvider) is transformed.
* The output of the FieldValueProvider for events is transformed.
* The `transaction` field of the event payload is transformed, but the original transaction name is also written to the event (for example in _meta).
  * The original transaction name does not have to be searchable (yet)
  * Optional: Mark in the string what section was replaced and put that information in `_meta`.
* Feature flag and ship for sentry

PRs:
* https://github.com/getsentry/relay/pull/1621
* https://github.com/getsentry/sentry/pull/41642

**Comment by jjbayer** [comment]
Initial proposal for detecting identifiers (internal docs): https://www.notion.so/sentry/Prevent-high-cardinality-for-transaction-names-09fc121e1a5743f980a8ccae1b543e6c#e895b742080944d28762f985a77b5803

Regex we use to detect identifiers in issue grouping: https://github.com/getsentry/sentry/blob/6ba59023a78bfe033e48ea4e035b64710a905c6b/src/sentry/grouping/strategies/message.py#L16

**Comment by jjbayer** [comment]
This will not provide value in the product yet, because erasing identifiers does not give us enough confidence to declare the transaction name "low cardinality", and with that, it will still be changed to "unparameterized" in metrics extraction.

**Comment by olksdr** [comment]
Changes deployed and enabled for sentry. We could watch the changes to transaction names as the result of linked PRs.
