### ISSUE TITLE
Fix broken shutdown test

### ISSUE THREAD

**Issue by HazAT** [getsentry/relay#1608]
There is a disabled integration test `test_forced_shutdown` that currently doesn’t work because the Dropped future fires after the sdk client has been closed. Actix keeps the system and all its registered futures alive even after the System::stop call.

After we’re done with getting rid of actix/modernizing in general, try to get that test running again.

**Comment by jan-auer** [comment]
Closed. This will be addressed as part of changes to shutdown.
