### ISSUE TITLE
[INC-237] Missing alert for dropped envelopes

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#1609]
There should be a Relay error on [sentry.my.sentry.io](http://sentry.my.sentry.io/) + alert whenever envelopes get dropped, in https://getsentry.atlassian.net/browse/INC-237 it did not trigger.

[Alert](https://sentry.my.sentry.io/organizations/sentry/alerts/rules/details/17/) looks for “error processing envelope”, but that did not occur since Aug 8 (INC-192), see [Discover](https://sentry.my.sentry.io/organizations/sentry/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=9&project=4&query=event.type%3Adefault+%22error+processing+envelope%22&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29).

That error [still exists in Relay code](https://github.com/getsentry/relay/blob/07eff5a6a1942829f34307b9593961480961e284/relay-server/src/actors/processor.rs#L2123), but maybe that code path is never reached?

We did get a lot of “error fetching project state, deadline exceeded” errors ([Discover](https://sentry.my.sentry.io/organizations/sentry/discover/results/?display=top5&end=2022-10-19T16%3A17%3A29.000&field=project&field=title&field=count%28%29&name=All+Events&project=9&project=4&query=event.type%3Adefault+%21message%3A%22unit+mismatch%22&sort=-count&start=2022-10-19T15%3A45%3A51.000&yAxis=count%28%29))

**Comment by jjbayer** [comment]
I verified that `error processing envelope` is still logged by returning a dummy error from `enforce_quotas`:

```rust
    #[cfg(feature = "processing")]
    fn enforce_quotas(&self, state: &mut ProcessEnvelopeState) -> Result<(), ProcessingError> {
        return dbg!(Err(ProcessingError::ProcessingFailed(
            ProcessingAction::InvalidTransaction("DUMMY ERROR"),
        )));
```

-> 

```
ERROR relay_server::actors::processor          > error processing envelope: envelope processor failed
```

The reason we did not see this error in INC-237 (Oct 19 2022) is that we failed envelope handling even before processing. The open question is why we did not see _any_ error during INC-237.

**Comment by jjbayer** [comment]
Alerts now updated (see linked PR for context):

https://sentry.my.sentry.io/organizations/sentry/alerts/rules/details/16/
https://sentry.my.sentry.io/organizations/sentry/alerts/rules/details/17/
