### ISSUE TITLE
When transactions are rate limited, profiles are sampled at 100%

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#1612]
When an envelope does not contain transactions, we do not attach a “sampling project state” to the envelope context: [relay/dynamic_sampling.rs at 0586fa62eb3ee75697120ea6d89efe51c740f6ad · getsentry/relay](https://github.com/getsentry/relay/blob/0586fa62eb3ee75697120ea6d89efe51c740f6ad/relay-server/src/utils/dynamic_sampling.rs#L138-L145)

But rate limit enforcement may already have removed transactions at that point, so we just sample 100% of profiles in that case: [relay/project.rs at 0586fa62eb3ee75697120ea6d89efe51c740f6ad · getsentry/relay](https://github.com/getsentry/relay/blob/0586fa62eb3ee75697120ea6d89efe51c740f6ad/relay-server/src/actors/project.rs#L886)

Example ([internal link](https://sentry.io/organizations/sentry/stats/?dataCategory=profiles&end=2022-11-16T23%3A59%3A59&project=1&start=2022-11-16T00%3A00%3A00&utc=true)):

![image](https://user-images.githubusercontent.com/363802/205597675-1e404a0b-4f39-4908-8105-5cbf460a154c.png)

Reproduce the bug in a (integration) test.

Fix: Either

* drop dependent items on rate limiting: When we remove the transaction, also remove profiles from the envelope.

* Apply dynamic sampling (i.e. attach a sampling project state to the envelope context) even if the transaction has been removed.

**Comment by phacops** [comment]
We always want to have a transaction for a given profile. Some of our SDKs were not sending a profile in the same envelope as the associated transaction. We're going to fix this and we should see the numbers aligned.
