### ISSUE TITLE
Prevent double-counting of metric buckets towards rate limit

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#1627]
When `EnvelopeManager` returns an error for an envelope of metrics buckets, these buckets will be merged back into the aggregator. This can happen if Kafka is down. Because rate limit have already been applied at this point, these buckets will count double, triple or worse towards the rate limit.

In order to not double count metrics buckets that were merged back into the aggregator, we have four options:

1. Enforce redis rate limits _before_ aggregation. **Downside**: more calls to redis than when we do it after aggregation.
2. Status quo: Leave as-is, accept that we might double-count. **Downside**: I assume that when Kafka is down for a while, we will exhaust quotas quickly.
3. Enforce redis rate limits after aggregation, but do not attempt to merge back after rate limiting. **Downside**: buckets are lost when we cannot connect to kafka (but that is also what happens to events)
4. Enforce redis rate limits after aggregation, but add a counter to each bucket how much it contributes to rate limiting. **Downside**: larger memory footprint

**Comment by jjbayer** [comment]
Fixed by https://github.com/getsentry/relay/pull/2652.
