### ISSUE TITLE
Metrics aggregator dropping buckets

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#1629]
Sentry Issue: [POP-RELAY-2BP](https://sentry.my.sentry.io/organizations/sentry/issues/297799/?referrer=github_integration)

```
Metrics aggregator dropping 2568 buckets
```

**Comment by jernejstrasner** [comment]
Seems to have stopped happening but will leave it open for now since it looks like it was opened and closed multiple times. Tagging as maintenance.
