### ISSUE TITLE
Dynamic sampling should respect metrics extraction version

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#1631]
For transaction metrics extraction, we have a versioning mechanism that works as follows: When sentry bumps the version number in the `transactionMetrics` part of the project config, old Relays which do not yet support this version will stop extracting metrics.

In practice, this means that customer Relays will stop extracting metrics, deferring the work to our PoP Relays instead. But these customer Relays will still drop events in dynamic sampling, under the assumption that transaction metrics have already been extracted.

→ Dynamic sampling should also be skipped if the `transactionMetrics.version` goes out of sync. This does mean increased load on our PoP Relays, though.

**Comment by jjbayer** [comment]
Alternatively, instead of looking at `transactionMetrics.version`, dynamic sampling could look at the `transaction_metrics_extracted` flag, and skip sampling when no metrics were extracted.
