### ISSUE TITLE
Remove transaction metrics allowlist from Sentry

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#1632]
Once Relay does not use the old configuration format anymore, remove it from project configs.

This means we can also completely remove the metrics allow list set up there.

**NOTE:** Outdated external Relays will not recognize the new config format, so when Sentry stops sending the metrics allowlist, they will stop sending metrics altogether, while still setting `metricsExtracted=1`. The way around this is bumping the `VERSION` of the metrics extraction config.

**Comment by iker-barriocanal** [comment]
@TBS1996 have we checked if we need to remove the list from project configs on the sentry side? I see no sentry PR linked to this issue, maybe we already removed it?
