### ISSUE TITLE
Enumerations in public interfaces need a catch-all type

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#1639]
- [x] https://github.com/getsentry/relay/pull/1638
- [x] Add unknown to `RuleType` and `SamplingMode` https://github.com/getsentry/relay/pull/1641
- [x] Check for more enumerations without a catch-all variant
- [x] Add `Other(u8)` to `SpanStatus` #1737 
       @jjbayer will check if we need different behavior in processing relays, and how.
- [x] Add `Unknown(String)` to `SessionStatus`. Do not extract metrics for unknown, but do forward session payloads. Remove in processing Relays. // pr: #1736 
- [x] Add `Unknown(String)` variant to `relay_profiling::MeasurementUnit`. Let Profiling team decide whether or not to drop unknowns in processing Relays. -> Not necessary right now because we don't parse profiles in non-processing relays.
- [x] `BucketValue`: Drop buckets with unknown type on deserialization. // bucketvalues are only sent from relay to relay, so no need forward compatibility in external relays
- [x] All PII config enums (see notion doc for details): skip rule on deserialization.
   Moved to separate issue: https://github.com/getsentry/relay/issues/1751
- [x] `RateLimitScope`: Skip unknown scopes (e.g. by skipping rule on deserialization). -> This already has a fallback via `QuotaScope`, see https://github.com/getsentry/relay/blob/337a8a0ed5c7f96e0c19f70757b9e54e2e99f7a5/relay-quotas/src/rate_limit.rs#L122-L123

**Comment by jjbayer** [comment]
Found the following problematic enums (internal doc): https://www.notion.so/sentry/Forward-compatibility-of-enums-5eafecc16a014cbab13dbab3791ccef3
