### ISSUE TITLE
Make Dangerbot work on external PRs

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#1654]
The Github token issued in forks for external PRs does not have sufficient permissions to read pull request information. This fails the Dependabot job with:

```
Request failed [403]: https://api.github.com/repos/getsentry/relay/issues/1645/comments
Response: {
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/issues#create-an-issue-comment"
}
```

PRs that are blocked on this:

- https://github.com/getsentry/relay/pull/1307
- https://github.com/getsentry/relay/pull/1558
- https://github.com/getsentry/relay/pull/1645

**Comment by jjbayer** [comment]
Example PR: https://github.com/getsentry/relay/pull/1558

**Comment by jan-auer** [comment]
What if we try to use `@actions/toolkit` like described here?
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions
- https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions

This should allow us to use GitHub Actions-specific commands to influence the status check of the PR without additional GitHub tokens.

**Comment by olksdr** [comment]
After the discussion with @jan-auer and testing few things in the lined PR #1664 we came to conclusion that it might be better and easier to write a small script using the `@actions/toolkit` and [`oktokit.js`](https://github.com/octokit/octokit.js) to actually check the `CHANGELOG`s and properly report the status also for forks.  

Also, see the comment above.

**Comment by olksdr** [comment]
PR is ready for review: https://github.com/getsentry/relay/pull/1664 
we just have to remove `Danger` check as required and make a new one required.
