### ISSUE TITLE
Support transaction renaming rules

### ISSUE THREAD

**Issue by iker-barriocanal** [getsentry/relay#1657]
Given the [protocol](https://www.notion.so/sentry/Clusterer-infra-design-1353df44638b4167af7358d25431ed9c#c5b6345c3e9245b7b460f8b3d2c76106), add support in relay for transaction renaming rules.

### Acceptance criteria
- [ ] Relay only applies the first matching rule.
- [ ] Relay ensures the path ends with a `/` when checking whether a rule matches, as detailed [here](https://www.notion.so/sentry/Rule-formats-c25e476637a2483cb33ca00ae48a7c5a#c45c3cae5b2b44b5b733b4fd15ffee61).
- [ ] Transaction renaming rules must be applied before applying any filters (such as dynamic sampling or inbound).
- [ ] Relay must preserve the original transaction name in the transaction's `meta` when applying the rules.
- [ ] The exact format to find the old name in a transaction's meta is documented [here](https://www.notion.so/sentry/Transaction-name-normalization-changes-42516662dc684a9abcc8d0aa2212396c#63d4f5d4472345aca08c5c6b95bf7481).
- [ ] When a transaction name has been sanitized, the transaction's source is set to `sanitized`.

**Comment by jjbayer** [comment]
Do this in the same place as https://github.com/getsentry/relay/pull/1621.
