### ISSUE TITLE
Error sending a metric: channel full

### ISSUE THREAD

**Issue by olksdr** [getsentry/relay#1680]
This happened few times, our statsd metrics could not be sent.

Sentry Issue: [POP-RELAY-2NV](https://sentry.my.sentry.io/organizations/sentry/issues/316057/?referrer=github_integration)

```
Error sending a metric: channel full
  caused by: channel full, maximum capacity: 100000
```

Error is coming from https://github.com/getsentry/relay/blob/576466bc15902959f55107b061a2067e33b83ae6/relay-statsd/src/lib.rs#L117

**Comment by iker-barriocanal** [comment]
[Investigation doc (internal)](https://www.notion.so/sentry/Can-t-send-metrics-because-the-channel-is-full-3d464b2250fe4e2789f1884a31fd28ee).

**Comment by jan-auer** [comment]
We have concluded the only viable short-term option is to reduce the amount of metrics. We are going to analyze which metrics are creating too much traffic and will reduce them. Note that this is NOT a cardinality concern, it's that our individual increments of metrics are too much.

Other considered options:
- **Increase channel size:** This option doesn’t really address the problem, and it only postpones it. The cost is the increased CPU and memory usage, which currently may be around 20% of a relay instance’s cost.
- **Increase number of channels or clients:** Same as above.
- **“Optimize” the channel**: To “optimize” the channel for higher throughput, it is recommended to move from UDP to Unix Domain Socket (UDS). UDS is another, strem-oriented protocol (supports UDP). However, there aren’t any guarantees of increased performance (we need to run benchmarks for that), comes with its own set of challenges, and requires infrastructure changes. The main challenge is based on how UDS fundamentally works, based on a special file.
