### ISSUE TITLE
Attachment with `event.view_hierarchy` type isn't shown in the Issues page

### ISSUE THREAD

**Issue by marandaneto** [getsentry/relay#1704]
### Environment

Sent by Flutter/RN on Android.

### Steps to Reproduce

1. Capture an envelope with an event
2. Capture an envelope with an attachment of the `event.view_hierarchy` type.

Obs: If the attachment and the event are sent within the very same envelope, it works.
I know that `minidumps` requires to be within the very same envelope of the event, but it's not the case for `event.view_hierarchy`.

[envelope.txt](https://github.com/getsentry/relay/files/10244975/envelope.txt)

The event id `dfbaa509977c4626af8266753e256908` set in the envelope header already exists in Sentry.

### Expected Result

Attachment is shown in the Issues page

### Actual Result

Attachment isn't show in the Issues page

**Comment by markushi** [comment]
Can we get some attention on this issue? This is blocking our Dart, Cocoa and Java (Android) SDK from shipping this feature. cc @kahest

**Comment by olksdr** [comment]
Opened https://github.com/getsentry/sentry/pull/42805 to fix this and also added integration test to relay in https://github.com/getsentry/relay/pull/1728 to check that we actually can send the individual attachments to Sentry.
