### ISSUE TITLE
Document custom measurement limit

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#1712]
It seems that the custom measurement limit of 5 is not documented (see https://docs.sentry.io/product/performance/metrics/#custom-performance-metrics). Also, from reading the code I think we don’t create any annotation within the event payload that would pop up in our UI to tell the user why they’re seeing fewer elements than expected, which would be even better than documentation.

```[tasklist]
- [ ] https://github.com/getsentry/sentry-docs/pull/6216
- [ ] https://github.com/getsentry/relay/pull/1815
```

**Comment by jjbayer** [comment]
Relevant code: https://github.com/getsentry/relay/blob/4cb923f0667da94801039ff2cbd99635221dd97b/relay-general/src/store/normalize.rs#L345

**Comment by jan-auer** [comment]
Increasing priority to P0 as per request from @ale-cota.
