### ISSUE TITLE
Connect to redis with credentials

### ISSUE THREAD

**Issue by adiletkabylbekov** [getsentry/relay#1722]
There is no configuration option for connection to Redis service using pasword!
I'v tried to setup connection string with password, but getting error
Configuration
```
processing:
  enabled: true
  kafka_config:
  - {name: "bootstrap.servers", value: "127.0.0.1:9093"}
  - {name: "message.max.bytes", value: 50000000} # 50MB
  redis: "redis://{password}@redis:6379"
  geoip_path: /geoip/GeoLite2-City.mmdb
```

Error message is 
```
2022-12-23T18:05:02Z [relay_server::actors::project_redis] ERROR: Failed to fetch project from Redis: failed to talk to redis
  caused by: failed to communicate with redis
  caused by: NOAUTH: Authentication required.
```

As i understoond relay service didn't provide configured password

**Comment by olksdr** [comment]
Hey @adiletkabylbekov ,

the format you have to use for the redis connection string is `redis://{username}:{password}@redis:6379`. In your example above you should still provide the `{username}`. 

According to the [redis docs](https://redis.io/commands/auth/) you might have to setup the proper user as well.  Or use the default one. 

> When ACLs are used, the single argument form of the command, where only the password is specified, assumes that the implicit username is "default".

**Comment by adiletkabylbekov** [comment]
@olksdr thank you for support
Yes you're right
i've already solved with providing default user in dsn string
`redis: "redis://default:{password}@redis:6379"`
