### ISSUE TITLE
browser extensions filter not working for chrome

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#1750]
We see the following form of stack trace both in our own projects as in customer projects (look for it by searching for `stack.abs_path:chrome*` in Discover):

```json
"frames": [
    {
        "filename": "chrome-extension://asdf/some.js",
        "abs_path": "chrome-extension://asdf/some.js",
        "lineno": 44,
        "colno": 65812,
        "in_app": true
    },
    {
        "function": "someFn",
        "filename": "chrome-extension://asdf/some.js",
        "abs_path": "chrome-extension://asdf/some.js",
        "lineno": 44,
        "colno": 65406,
        "in_app": true
    },
    {
        "function": "Function.defineProperty",
        "filename": "<anonymous>",
        "abs_path": "<anonymous>",
        "in_app": true
    }
]
```

Because `get_exception_source` only looks at the last stack frame, this is not caught by the browser extensions filter: https://github.com/getsentry/relay/blob/2a0976d7d9ecfd4daa6cb2390c224d09f9a79bbd/relay-filter/src/browser_extensions.rs#L107-L112.

Unsure if this is the case for all chrome extensions or just for some.

Possible solution: Look at the last frame in the stack trace that has a line number.

**Comment by jan-auer** [comment]
Alternatively: Skip frames that are `<anonymous>`. Minified sources might not have line numbers but they would at least have the `extension://` path.

**Comment by rodolfoBee** [comment]
Skipping "invalid" frames is a good option, it can also skip `[native code]` frames.
