### ISSUE TITLE
Make pii config forward-compatible

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#1751]
This is a follow-up to #1639: When we extend the PII part of project config, we want to make sure that old external Relays do not fail parsing the config. For this, we need to add fallback variants to all enums:

- [x] RuleType: https://github.com/getsentry/relay/pull/1741
- [x] Redaction: https://github.com/getsentry/relay/pull/1859
- [ ] ReplaceBehavior
- [ ] SelectorPathItem: https://github.com/getsentry/relay/pull/2209
- [ ] SelectorSpec: https://github.com/getsentry/relay/pull/2202

Ideally, we would already catch unknown variants during deserialization, so we do not have to add an enum variant in code, and we don't have to handle that variant in match statements etc.

**Comment by TBS1996** [comment]
closed on recommdation from jjbayer
