### ISSUE TITLE
[statsd] Relay's statsd take up 20% CPU

### ISSUE THREAD

**Issue by jernejstrasner** [getsentry/relay#1763]
Something in the way that we emit metrics is inefficient and fishy. I suspect we don't aggregate any metrics in-process, and as a result spend way too much CPU on emitting metrics. 

`Anton Ovchinnikov` claimed 20% CPU increase by turning on metrics collection. More CPU usage than normal in both Relay and the statsd collector.

We also likely drop metrics as a result of that.

**Comment by iker-barriocanal** [comment]
What do we want to do with this? I think the best course of action at this point in time is to not emit many metrics, see [investigation doc](https://www.notion.so/sentry/Can-t-send-metrics-because-the-channel-is-full-3d464b2250fe4e2789f1884a31fd28ee?pvs=4).

**Comment by jernejstrasner** [comment]
@jan-auer what's your take since this is metrics related?

**Comment by Dav1dde** [comment]
Not a problem at the moment, with the addition of `statsdproxy` this already got a lot better.
