### ISSUE TITLE
Question: can I keep my Sentry DSN private?

### ISSUE THREAD

**Issue by olivierchedru** [getsentry/relay#1771]
I am using Relay to route events from a web app to sentry.io, because some browser extensions block direct traffic to sentry.io.

I would like to go further and avoid exposing my public key and project-id in the web app code, but could not find any configuration option to "rewrite" a DSN with Relay.

Is there a way to achieve this?
Thank you!

**Comment by jan-auer** [comment]
Unfortunately, you cannot do that. The public key and project ID from the DSN are required to deliver data to your Sentry projects. If we were to add a mode to Relay that doesn't require the public key, everyone could send traffic the same way as if they had your public key.

In project settings, you can configure "Allowed Domains" in your project settings to limit traffic to a set of configured origins.

**Comment by olivierchedru** [comment]
Thank you for your quick response! That indeed makes a lot of sense.
