### ISSUE TITLE
Add new replay context to the context protocol

### ISSUE THREAD

**Issue by cmanallen** [getsentry/relay#1792]
This can go into a separate PR, but we should add this new Context to the protocol. see for example 

https://github.com/getsentry/relay/blob/23c24a93dd9c26749cbef6fc49a52d70d25e91bd/relay-general/src/protocol/contexts/browser.rs#L6-L16

_Originally posted by @jjbayer in https://github.com/getsentry/relay/pull/1791#discussion_r1090883064_

**Comment by jan-auer** [comment]
The information in this context seems to contain metadata on sampling. This information is usually not stored in the event payload but rather in special metadata keys (either `_meta` or `_metrics`). To resolve this issue, @cmanallen please:

1. List fields and data types that are part of this context
2. Describe how these fields are used in the product

We may need to move some of these fields to other places in the payload.

**Comment by cmanallen** [comment]
@jan-auer The fields are supplied to relay as a "replay" object within the "contexts" object containing two keys with float values.


```json
{
    "contexts": {
        "replay": {
            "error_sample_rate": f64,
            "session_sample_rate": f64
        }
        ...
    }
}
```

The values are not used within the product and are instead used for internal metrics calculations.  @mydea knows more and can give more details on usage.

**Comment by JoshFerge** [comment]
I am running into this now in https://github.com/getsentry/relay/pull/1983 as I didn't realize we already were setting things in the context. I think that we shouldn't store these on the replay context, and need to rethink these fields. let's discuss soon.

**Comment by jjbayer** [comment]
@cmanallen is this still relevant? Closing because of age, feel free to reopen.
