### ISSUE TITLE
PII scrubbing breaks a replay

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/relay#1806]
the Replay Recording payload has the entirety of its `_cssText` scrubbed on two of the three events below. The resulting output is also linked.

This is not a bug in PII scrubbing behavior, but session replays needs to use it correctly. we cannot remove the entirety of strings with certain words, as below you'll see one of the css selectors has the word "password".

I propose the following:
- We tweak the default PII scrubbing rules to not redact entire strings, but to do replacements (I think there are already mechanisms to do this)
- We need observability on how many of our replays are being scrubbed, and we also need to understand how these rules can break replays.
- When we re-introduce schemas, this may be less of a problem as we can be mroe discerning about what nodes we scrub

[css.txt](https://github.com/getsentry/relay/files/10563980/css.txt)
[output.txt](https://github.com/getsentry/relay/files/10564035/output.txt)

Closes https://github.com/getsentry/sentry-javascript/issues/7041

**Comment by JoshFerge** [comment]
working on a script now to identify how often this occurs and get more example data

**Comment by reinoldus** [comment]
@JoshFerge This is also happening on my sentry, if I can help with example data let me know.

I am using the cloud version, in case that helps to get access.

**Comment by AxelDeneu** [comment]
Same here, from like 2-3 days, no css is being loaded on the replay. I'm on cloud too if this can help.

**Comment by cmanallen** [comment]
@reinoldus @AxelDeneu You should now see your (new) replays playing correctly.  Let us know if the problem persists.

**Comment by jan-auer** [comment]
We're going to ship a new version of the data scrubber that exclusively targets sentry's data (breadcrumbs, network). At a later point, we're going to expand this back to the entirety of replays and exclude CSS along with other safe attributes from data scrubbing.
