### ISSUE TITLE
captureException additional data displays [Filtered] even when whitelisted

### ISSUE THREAD

**Issue by ciriousjoker** [getsentry/relay#1808]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which package are you using?

@sentry/angular

### SDK Version

6.18.2

### Framework Version

@sentry/angular

### Steps to Reproduce

```ts
addBreadcrumb({
  category: "...",
  data: {
    // I whitelisted functionName in the data scrubber on the project level and on the organization level
    // via "(Global) Safe Fields". If I put smth else as the functionName, for example
    // "[europe-west1] checkoutEstimate()", it works.
    // I put
    functionName: "[europe-west1] checkoutCreateBraintreeClientAuthorization()",
  },
  level: Severity.Log,
  message: id,
  type: 'http',
});
```

Here's my safe fields field:

<img width="1127" alt="Bildschirmfoto 2022-03-20 um 00 37 30" src="https://user-images.githubusercontent.com/16866223/159142015-726895a0-9960-48f1-bc1e-ffd12c6293f5.png">

If I disable the whole thing, it works. That's the current workaround, but it's obviously not optimal.

### Related:
- (forum is broken, so cached link): https://webcache.googleusercontent.com/search?q=cache:UdKrpPH_U7IJ:https://forum.sentry.io/t/safe-fields-still-get-scrubbed/14529+&cd=2&hl=de&ct=clnk&gl=de

### Expected Result

`functionName` should be displayed properly.

### Actual Result

`functionName` gets replaced with "[Filtered]".

**Comment by lobsterkatie** [comment]
Hi, @ciriousjoker.

Sorry you're having trouble! This is more of an ingest question, so I'll refer this to them for a surer answer, but I believe the reason that's getting scrubbed is that it contains the substring `"auth"`.

@untitaker, is there a way of circumventing this?

**Comment by untitaker** [comment]
At first sight this is a legitimate bug. We should investigate this.

**Comment by Dav1dde** [comment]
I tried to reproduce the issue both with a `safe fields` configuration on the organization as well as the project and relay correctly honored the configuration in both cases.

Is this still an issue for you?

**Comment by ciriousjoker** [comment]
@Dav1dde honestly I don't know, it's been 2 years and I'm not working on the project from back then anymore. Just close this and I'll create a new issue and reference this one if it comes up again.
