### ISSUE TITLE
IP scrubbing removes chrome version

### ISSUE THREAD

**Issue by TBS1996** [getsentry/relay#1826]
Michael Chai reported that a customer got a false positive where ip scrubbing removed the browser version. Customer issue [here](https://getsentry.atlassian.net/browse/ISSUE-1652).

https://files.slack.com/files-pri/T024ZCV9U-F04NU8URXGR/image.png

Perhaps we should add user agent to the default safe fields?

**Comment by olksdr** [comment]
Ideas:

* disable IP scrubbing for `user_agent` header or/and client hints

**Comment by smeubank** [comment]
I think it's best to loop in @jan-auer here i see someone from ingest already create tge issue

@TBS1996 the default safe fields: would you need any changes in thr JS SDK for this?
