### ISSUE TITLE
Redis TLS does not work in official docker image

### ISSUE THREAD

**Issue by SmoshySmosh** [getsentry/relay#1835]
Filing bug report at the request of @olksdr.

### Environment

What version are you running?
Relay 23.1.1 (https://hub.docker.com/layers/getsentry/relay/23.1.1/images/sha256-bac5c620c10a5e2308f391fe19f71bf7fec3219b0ab173580f5a606be2f7c635?context=explore)

### Steps to Reproduce

1. Connected to the running container in interactive mode.
2. Run command using environment variables to test
```bash
$ RELAY_PORT=3001 RELAY_REDIS_URL=rediss://<username>:<password>@<redis host>:6379 relay run -c /work/.relay/
```

### Expected Result

Relay should start up and connect to TLS enabled Redis Cluster based on discussion in this PR: https://github.com/getsentry/relay/pull/1772

### Actual Result

Relay did not connect to the Redis Cluster.

```
 INFO  relay::setup > launching relay from config folder /work/.relay/
 INFO  relay::setup >   relay mode: managed
 INFO  relay::setup >   relay id: <redacted>
 INFO  relay::setup >   public key: <redacted>
 INFO  relay::setup >   log level: INFO
 INFO  relay_statsd > reporting metrics to statsd at <reacted>:8125
 INFO  relay_server::actors::upstream > upstream relay started
 INFO  relay_server::actors::upstream > registering with upstream (http://<reacted>:9000/)
 INFO  relay_server::actors::outcome  > OutcomeProducer started.
 INFO  relay_server::actors::outcome_aggregator > outcome aggregator started
 INFO  relay_server::actors::upstream           > relay successfully registered with upstream
 ERROR relay_log::utils                         > could not initialize redis cluster client
  caused by: failed to communicate with redis
  caused by: can't connect with TLS, the feature is not enabled
```

**Comment by TBS1996** [comment]
Thank you, we will look into this.

**Comment by olksdr** [comment]
I've double checked the features on the `relay` side and everything looks ok to me.


I've also tried to reproduce the error but I couldn't:

* * started Redis with generated TLS certs and enabled TLS on the port
* pulled `23.1.1` docker image
* run the same command to connect to my TLS-enabled Redis
* there was no errors and the relay could communicate with this Redis instance 

Everything seemed worked as expected. 

Could you, please, check if the Redis configured properly on your side and if the `relay` image you use is the latest one as well? 

Also, if the error persist, could you, please, provide  config of the `relay` service and more information about how your Redis instance was configured? 

Thank you.

**Comment by jernejstrasner** [comment]
@SmoshySmosh just a friendly ping 🔔

**Comment by SmoshySmosh** [comment]
Apologies for the delays. I will be modifying my deployment later this week to try and use this feature again. When that happens, I will report back the results.

**Comment by olksdr** [comment]
Closing this as non-active.
Please, reopen when there is more information or the reproduction case available. 
Thanks!
