### ISSUE TITLE
Pattern regex fails compilation

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#1836]
[RELAY-2NFB](https://sentry.my.sentry.io/organizations/sentry/issues/392396):

```
Unable to compile pattern into regex: could not parse pattern
  caused by: Compiled regex exceeds size limit of 262144 bytes.
```

Same error happens on sentry-side when we re-apply datascrubbing: https://github.com/getsentry/relay/issues/1626.

In both cases, we should compile the regex at UI time (when the customer configures their rules) to prevent this config from being saved in the first place.

**Comment by faevourite** [comment]
Could this be related to https://github.com/getsentry/relay/issues/1626#issuecomment-1636021252 ? (min-repetition regex like `{10,}` triggers this error).

**Comment by jjbayer** [comment]
Only happened for a single project in SaaS in the past 90 days. I deleted the offending rule and notified support.
