### ISSUE TITLE
IP address in transaction name is normalized to `*`

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#1852]
`GET http://127.0.0.1:8000/some/url/` becomes `GET http://*/some/url/`.

We could try to parse URL transaction names as

```
(GET|POST|...)? <schema>://<domain-or-ip>(:<port>)?<uri>`
```

and then only apply identifier scrubbing to the `<uri>` part. But as @olksdr pointed out, IP addresses could also be high-cardinality.

**Comment by olksdr** [comment]
We actually could try to parse it as URI, see https://docs.rs/http/latest/http/uri/index.html, which would give us desire effect, as we would only work on `path` part. This might cover like 95% of the cases our of the box.  

We might be able to do this without regex.

**Comment by jan-auer** [comment]
IP addresses and ports are not unlikely to cause high cardinality. We will rather keep scrubbing them, and will fix SDKs to exclude the host and port from the transaction name.
