### ISSUE TITLE
Figure out if Relay needs the ingest-sessions topic

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#1882]
Ops want to remove the `ingest-sessions` kafka topic, to which SaaS Relays does not produce any messages now that we convert all sessions to metrics and [drop the original session payloads](https://github.com/getsentry/sentry/blob/302f747e8390f09e9ca51c126cc4a702287257a2/src/sentry/relay/config/__init__.py#L316-L318).

Since `ingest-sessions` is still [part of Relay's default static config](https://github.com/getsentry/relay/blob/8539142c32326318124a1f07e38385a60fb1a958/relay-kafka/src/config.rs#L128), test if Relay can run healthily if this topic does not exist anymore.

The difficulty of testing this in a local env consists of making sure that kafka consumers / producers do not autocreate the topic. See
* https://kafka.apache.org/documentation/#consumerconfigs_allow.auto.create.topics
* Sentry option [`KAFKA_CONSUMER_AUTO_CREATE_TOPICS`](https://github.com/getsentry/sentry/blob/e775f979048c0c2ad5876c1480eeac841392324f/src/sentry/conf/server.py#L2670-L2671).

**Comment by Dav1dde** [comment]
Closing this since we no longer have this topic in Relay.
