### ISSUE TITLE
Add support for CSP reports with extended `effective-directive`

### ISSUE THREAD

**Issue by oioki** [getsentry/relay#1973]
Consider this CSP violation report:
```
{"csp-report":{"document-uri":"REDACTED","referrer":"REDACTED","violated-directive":"script-src 'report-sample' 'strict-dynamic' 'unsafe-eval' 'nonce-random'","original-policy":"base-uri 'self'; object-src 'none'; script-src 'report-sample' 'strict-dynamic' 'unsafe-eval' 'nonce-random'","blocked-uri":"REDACTED","effective-directive":"script-src 'report-sample' 'strict-dynamic' 'unsafe-eval' 'nonce-random'"}}
```

Currently, Relay drops those with such error:
```
failed to extract security report: invalid security report
  caused by: invalid value: string "script-src 'report-sample' 'strict-dynamic' 'unsafe-eval' 'nonce-random'", expected a csp directive at line 1 column 729
```

Apparently, this has something to do with older browsers before CSPv3 where `effective-directive` and `violated-directive` contained a longer substring of CSP. Check this excerpt from [csplite.com](https://csplite.com/csp66/#violated-directive):
> According to recomendations for [CSP 1](https://csplite.com/csp1/#violated-directive) and [CSP 2](https://csplite.com/csp2/#violation-report-violated-directive), in the violated-directive (unlike [effective-directive](https://csplite.com/csp66/#effective-directive)), not only the name of the directive is sent, but also a set of its rules, for example:
> `"violated-directive":"script-src 'unsafe-inline' 'unsafe-eval' 'self' https://site.com ..."`
> In [CSP 3](https://csplite.com/csp3/#violation-effective-directive) this behavior has been changed - now always [violated-directive = effective-directive](https://csplite.com/csp3/#deprecated-serialize-violation), and it is more does not contain violated policy rules:
> > [Note CSP 3](https://csplite.com/csp3/#violated-effective). Both [effectiveDirective](https://csplite.com/csp66/#effective-directive) and [violatedDirective](https://csplite.com/csp66/#violated-directive) have [the same value](https://csplite.com/csp3/#violated-effective) (meaning the name of the directive). This is intentional to maintain backwards compatibility.

My proposal is to add support for such cases. Seems like `effective-directive` is a searchable field (i.e. we can have a filter on the issues page like `effective-directive:img-src`), so I guess it should be of low cardinality. To keep cardinality low, we can do the following:
- save the original value of `effective-directive` CSP field to `effective-directive-full` (or something similar), make it unsearchable;
- save the first keyword of `effective-directive` CSP field to `effective-directive`.

That is, for the CSP violation above, the results would look like:
```
effective-directive: script-src
effective-directive-full: script-src 'report-sample' 'strict-dynamic' 'unsafe-eval' 'nonce-random'
```

**Comment by iker-barriocanal** [comment]
Related error: [POP-RELAY-2GC](https://sentry.my.sentry.io/organizations/sentry/issues/309590/events/97853b79148d40bd9f3b4f6a4693d987/).

**Comment by TBS1996** [comment]
@oioki 

does 'effective-directive' ever contain the long form like  "script-src 'unsafe-inline' 'unsafe-eval' 'self' https://site.com ..."" 

or just violated-directive does (in version 1 and 2)

the quote you used from csplite seems to suggest its only violated-directive, but your solutions seem to imply that it's effective-directive
