### ISSUE TITLE
PII scrub bank accounts

### ISSUE THREAD

**Issue by iker-barriocanal** [getsentry/relay#1995]
Relay should be able to PII scrub bank accounts (e.g. `IBAN.....`).

**Comment by TBS1996** [comment]
now that we're done with IBAN, I try to find other types of bank numbers we can scrub. BIC seemed logical, however, the format is too broad that I think we would have too many false positives.

do you have any thoughts on this? should we perhaps close this issue?

**Comment by iker-barriocanal** [comment]
I don't think there's anything immediately actionable, so closing the issue. We can consider reopening it in the future or creating a new one if there're more requests.
