### ISSUE TITLE
New (prod) internal endpoint for metrics envelope submission

### ISSUE THREAD

**Issue by onewland** [getsentry/relay#2000]
For the expanding metrics use cases, we would like to have a new Relay internal endpoint that takes metrics envelopes and flushes messages to `ingest-performance-metrics` in Kafka.

It would be nice if this had some switch to write to a dummy topic so that we could test integration with the endpoint from Sentry without ingesting new metric data

**Comment by jernejstrasner** [comment]
@onewland do you have any further information on the timing of this? Anything else we should know to schedule this?
