### ISSUE TITLE
Session Replay: Key-based PII scrubbing

### ISSUE THREAD

**Issue by billyvg** [getsentry/relay#2007]
The Replay team has started to ingest fetch/xhr request and response bodies (and later on headers) on the Sentry org. As you can imagine, a big concern with this feature will be PII. Assuming the fetch response body is JSON, we will send the body as JSON rather than stringifying it. You can see an example payload here:

```json
{
    "type": 5,
    "timestamp": 1680009712.507,
    "data": {
        "tag": "performanceSpan",
        "payload": {
            "op": "resource.fetch",
            "description": "https://api2.amplitude.com/2/httpapi",
            "startTimestamp": 1680009712.507,
            "endTimestamp": 1680009712.671,
            "data": {
                "method": "POST",
                "statusCode": 200,
                "request": {
                    "size": 2949,
                    "body": {
                        "api_key": "foobar",
                        "events": "[...]",
                        "options": {
                            "min_id_length": 1
                        }
                    }
                },
                "response": {
                    "size": 94,
                    "body": {
                        "code": 200,
                        "server_upload_time": 1680009712652,
                        "payload_size_bytes": 2949,
                        "events_ingested": 5
                    }
                }
            }
        }
    }
}
```

Relay is already scrubbing replay events where `type == 5`, however we would want the scrubber to be contextually aware so that it is able to scrub values based on keys. In the example above we have `data.payload.data.request.body.api_key`, whose value (`foobar`) we would like to be scrubbed.

**Comment by jjbayer** [comment]
This should be possible to do in 2-3 person days. I will try to pick it up this or next week.

**Comment by billyvg** [comment]
Thanks Joris! Wondering, is it possible to conditionally scrub and at a specific key path, or does it need to be the entire JSON?

e.g. condition: `data.payload.op` == `resource.fetch` or `resource.xhr`, then scrub at path: `data.payload.data`

**Comment by jjbayer** [comment]
> Thanks Joris! Wondering, is it possible to conditionally scrub and at a specific key path, or does it need to be the entire JSON?
> 
> e.g. condition: `data.payload.op` == `resource.fetch` or `resource.xhr`, then scrub at path: `data.payload.data`

@billyvg we might be able to hard code specific conditions, but our current PII rule framework does not support it in a general way.

**Comment by billyvg** [comment]
OK, no worries then.

**Comment by billyvg** [comment]
I wrote some comments embedded in the example payload below:

```javascript

{
    "type": 5,
    "timestamp": 1680009712.507, // safe to ignore
    "data": {
        "tag": "performanceSpan", // safe to ignore
        "payload": {
            "op": "resource.fetch",  // safe to ignore
            "description": "https://api2.amplitude.com/2/httpapi", // default scrubbers
            "startTimestamp": 1680009712.507, // safe to ignore
            "endTimestamp": 1680009712.671,   // safe to ignore

            /**
             * This `data` object will vary based on `data.payload.op`, and it will contain
             * a mix of SDK specified keys and "user" data. In this case, `method`, 
             * `statusCode`, and `request.size`, are SDK-created keys and known safe values. 
             * However, `request.body` will be arbitrary data and a key like `api_key` could
             *  exist anywhere within `request.body` (or not at all).
             */
            "data": {
                "method": "POST",
                "statusCode": 200, 
                "request": {
                    "size": 2949,
                    "body": {
                        "api_key": "foobar",
                        "events": "[...]",
                        "options": {
                            "min_id_length": 1
                        }
                    }
                },
                "response": {
                    "size": 94,
                    "body": {
                        "code": 200,
                        "server_upload_time": 1680009712652,
                        "payload_size_bytes": 2949,
                        "events_ingested": 5
                    }
                }
            }
        }
    }
}
```

Ultimately what we would like to do is apply a scrubbing strategy to `data.payload.data` that will iterate through the entire object and scrub values based on the key, where key matches a set of "likely to contain PII" values. `api_key` was an example, but it could be variations on it, `token`, `password`, etc.

If it's too complex to only scrub `data.payload.data` in this way, I think applying it to the entire payload (for type == 5) should be fine too as it's highly unlikely we use a problematic key.
