### ISSUE TITLE
Expand CSP filtering options

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/relay#2037]
Our CSP filter works on blocked_uri and source_file: https://github.com/getsentry/relay/blob/1bd6764397a9a251d31ee1bd1b68f49269d1b895/relay-filter/src/csp.rs#L10-L34 

A customer has requested to add `document_uri` to filter, which can improve the CSP filters UX. One option is to allow users to choose which CSP fields they want to use with the filters.

Originally requested in: https://getsentry.atlassian.net/browse/FEEDBACK-1070

**Comment by jjbayer** [comment]
Makes sense to me, will add it to our backlog.
