### ISSUE TITLE
Match trace rules against the parametrized name of a transaction

### ISSUE THREAD

**Issue by RaduW** [getsentry/relay#2068]
At the moment it looks like dynamic sampling rules that apply on traces do not operate on the parametrised transaction names, i.e.  the transaction name is taken from the trace header and it is compared as is against the name specified in the rule.

This is a problem because we would like to create trace rules for rebalancing the transactions (root transactions) in a project and we are restricted to a small number of rules ( 30). Having hundreds of transaction names makes it hard to properly balance the transactions in a project.

What we need:
1. The trace transaction rules should be able to operate on parametrized transaction names ( not the original transaction name from the trace header).
2. The transaction name specified in the root transaction count metric should be the parametrized name ( since these are the names used to generate the rules in the first place), at the moment that doesn't seem to be the case (didn't check in the code just looked at the transaction names from the collected metrics).

**Comment by ale-cota** [comment]
[This](https://sentry.slack.com/archives/C011TCYRLF6/p1682472108642909) might to be an example of this problem materialising in the Issues page, reported by @JoshFerge
