### ISSUE TITLE
More indexed transactions than processed

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#2083]
In a test project, we see that "transactions" (a.k.a. transaction metrics) are limited by spike protection, but the corresponding "indexed transactions" (a.k.a. transaction payloads) are not:

| processed  | indexed |
| ------------- | ------------- |
| ![Screenshot 2023-05-02 at 08 20 52](https://user-images.githubusercontent.com/1565449/235595893-47592d9e-2d0e-4367-9b2d-9fcdb881ebdd.png)  | ![Screenshot 2023-05-02 at 08 21 18](https://user-images.githubusercontent.com/1565449/235595913-8f6bf458-5d03-4c72-bb41-5a06e2ca0b22.png) |

([link](https://sentry.io/_admin/customers/profiling-ga-test/?dataType=indexed_transactions&end=2023-05-02T02%3A17%3A26&start=2023-05-01T12%3A22%3A13))

This also means that profiles are not limited by transaction spike protection.
```[tasklist]
### Delay metrics extraction
- [x] Skip metrics extraction in non-processing Relays when sampling decision is "keep": https://github.com/getsentry/relay/pull/2562
- [x] Bump metrics extraction version so outdated external Relays stop extracting for "keep" as well
```

```[tasklist]
### Rate limit metrics before aggregation
- [ ] https://github.com/getsentry/relay/pull/2574
- [ ] https://github.com/getsentry/relay/pull/2588
- [ ] https://github.com/getsentry/relay/pull/2652
```

**Comment by jjbayer** [comment]
cc @phacops

**Comment by jjbayer** [comment]
Tracking the profiles-specific issue here now because it has higher priority than the inconsistency between indexed and processed transactions: https://github.com/getsentry/relay/issues/2158

**Comment by jernejstrasner** [comment]
@jjbayer the Profiling specific case doesn't fix this one fully, does it?

**Comment by jjbayer** [comment]
> the Profiling specific case doesn't fix this one fully, does it?

@jernejstrasner no, https://github.com/getsentry/relay/issues/2158 only guarantees consistency between processed profiles and processed transactions.

**Comment by jjbayer** [comment]
More real world examples here (all spike protection): https://www.notion.so/sentry/More-indexed-than-processed-10acca5514324738a8c7587f9b93788d

**Comment by jjbayer** [comment]
Wrote this test to verify that we're not dealing with a simple bug: In principle, a rate limit scoped to the general category (`Transaction`) also applies to the indexed category (`TransactionIndexed`): https://github.com/getsentry/relay/pull/2499.

**Comment by jernejstrasner** [comment]
From @indragiek:

Hi folks, we are working on doing some estimation for the COGS impact of doing more processing on "processed" 

> profiles,  and @viglia's been working on pulling data for existing orgs to do the estimation.
> Along the way we hit this issue again: https://github.com/getsentry/relay/issues/2083. This is the same bug we found during the lead up to the Profiling launch where we are under counting both processed profiles and processed transactions, making it hard to get a good estimate to do our calculations with.
> This issue says it only applies when spike protection is enabled, which leads to a few questions:
> 
> 1. Is it still true that this only impacts spike protected orgs? I believe this still seems to be the case - some orgs that @jjbayer checked recently all have spike protection enabled: https://www.notion.so/sentry/More-indexed-than-processed-10acca5514324738a8c7587f9b93788d
> 2. Is spike protection enabled by default for all new AM2 orgs?
> 3. If it is enabled by default, would we expect the impact of this bug to grow significantly with new org growth? We deemed it P2 last time but I think it may be worth elevating the priority

**Comment by jjbayer** [comment]
Best idea so far:

1. In non-processing relays (PoPs, external), when the sampling decision is "keep", do _not_ extract metrics.
1. In processing relays, enforce rate limits for metrics buckets _before_ inserting into the aggregator.

This way, if an event survives dynamic sampling, its extracted metrics will get rate limited at approx. the same point in time as the payload itself.

**Comment by jan-auer** [comment]
The proposed solution would also fix https://github.com/getsentry/relay/issues/1627

**Comment by TBS1996** [comment]
Final PR is merged now, closing this when we've confirmed it works

**Comment by viglia** [comment]
@TBS1996 thanks for taking care of this. I've asked the Data Team (ticket [here](https://getsentry.atlassian.net/browse/BI2-362)) to recreate the Dashboard of `indexed vs processed` profiles by `org` we had originally so that we can validate it.

**Comment by jjbayer** [comment]
Unfortunately there are still projects that have more indexed than total transactions, and they don't seem to be related to spike protection. See query and examples here: https://www.notion.so/sentry/More-indexed-than-processed-10acca5514324738a8c7587f9b93788d?pvs=4#a55a327833c24c0ebbccb05bc76714ea

**Comment by jjbayer** [comment]
Keeping this ticket open while we're tracking down the different reasons for this.

**Comment by jjbayer** [comment]
All large diffs seem to have been resolved (see [internal doc](https://www.notion.so/sentry/More-indexed-than-processed-10acca5514324738a8c7587f9b93788d?pvs=4#a55a327833c24c0ebbccb05bc76714ea)). Issues with small diffs tracked here:
* https://github.com/getsentry/team-ingest/issues/234
* https://github.com/getsentry/team-ingest/issues/243
