### ISSUE TITLE
Types `BagSize` mismatching

### ISSUE THREAD

**Issue by marandaneto** [getsentry/relay#2109]
https://github.com/getsentry/relay/blob/c38cd0a32e1d9c8f27c3e50e1e599495e49e3ee3/relay-general/src/processor/attrs.rs#L173-L195

`ExtraValue` -> `bag_size = "massive"`
https://github.com/getsentry/relay/blob/c38cd0a32e1d9c8f27c3e50e1e599495e49e3ee3/relay-general/src/protocol/event.rs#L452

`bag_size = "larger"`
https://github.com/getsentry/relay/blob/c38cd0a32e1d9c8f27c3e50e1e599495e49e3ee3/relay-general/src/protocol/event.rs#L115

@jjbayer:

> I actually don't know, I assume both (i.e. the strictest one wins)

Ideally this is documented and/or fixed, it's confusing the very same type having multiple `BagSize` sizes.

**Comment by iambriccardo** [comment]
Resolved in: https://github.com/getsentry/relay/pull/3422
