### ISSUE TITLE
Multiple Public Keys Per Project

### ISSUE THREAD

**Issue by mpass99** [getsentry/relay#2120]
### Environment

- Docker image
  - `getsentry/relay:latest`
  - Digest: `c5e282591c38`

### Steps to Reproduce

1. Setup a project with multiple public keys.

``` json
{
    "slug": "example",
    "publicKeys": [
        {
            "publicKey": "1234567890abcdefghijklmnopqrstuv",
            "isEnabled": true
        },
        {
            "publicKey": "zyxwvutsrqponmlkjihgfedcba098765",
            "isEnabled": true
        }
    ]
}
```
2. Send a test event
``` bash
export SENTRY_DSN='http://zyxwvutsrqponmlkjihgfedcba098765@example.org/1234567'
sentry-cli send-event -m 'A test event'
```
3. Observe the error in the logs
``` logs
public key mismatch on state zyxwvutsrqponmlkjihgfedcba098765
```

### Expected Result

The relay accepts all valid public keys.

### Actual Result

The relay accepts only the first public key configured.

### Insights

The error is thrown only in one line - when checking the request.

https://github.com/getsentry/relay/blob/075170c9f8c4dbe7ff66779f51f2c2ce2687b8e1/relay-server/src/actors/project.rs#L321-L324

The function `self.is_matching_key` compares the keys while using the function `get_public_key_config` to get the key configuration.

https://github.com/getsentry/relay/blob/075170c9f8c4dbe7ff66779f51f2c2ce2687b8e1/relay-server/src/actors/project.rs#L219-L222

The function `get_public_key_config` has all public key configurations available, but just returns the first key.

https://github.com/getsentry/relay/blob/075170c9f8c4dbe7ff66779f51f2c2ce2687b8e1/relay-server/src/actors/project.rs#L142-L144

**Comment by olksdr** [comment]
Hey @mpass99,

Could you, please, provide more information about your setup:
* the exact version of the Relay you use, maybe the actual tag? 
* are you connecting to a self-hosted or SAAS (sentry.io)?
* could you, please, point us to the documentation which you used to configure Relay to `setup a project with multiple public keys`?

**Comment by mpass99** [comment]
Hey @olksdr,

Thank you for your quick response. Here is the required information about our setup.

> the exact version of the Relay you use, maybe the actual tag

The Docker image we use `getsentry/relay:latest` is using the relay version 23.4.0.
We have also been able to reproduce the error by building the relay from its source code. We used the latest commit `075170c9` on the `master` branch which is also relay version 23.4.0.

> are you connecting to a self-hosted or SAAS (sentry.io)?

We are self-hosting the relay as Docker container and use `sentry.io` as upstream.

``` yaml
relay:
  mode: static
  upstream: "https://o1234567890123456.ingest.sentry.io"
```

> could you, please, point us to the documentation which you used to configure Relay to `setup a project with multiple public keys`?

We followed the documentation you provide [here](https://docs.sentry.io/product/relay/getting-started/). Especially, the step of the [Project Configuration](https://docs.sentry.io/product/relay/projects/).

> publicKeys
>    A list of known public keys (the public key in a DSN) and whether events using that key should be accepted.

**Comment by olksdr** [comment]
@mpass99 thanks for the provided information! 

We will look into this on our side and will get back to you when we have more information.

**Comment by mpass99** [comment]
We can confirm that our issue is solved with the current nightly build (`getsentry/relay:nightly`, Digest: `7fa9cbf38475`). Thank you!
