### ISSUE TITLE
Panic on parsing resolv.conf

### ISSUE THREAD

**Issue by luckyraul** [getsentry/relay#2147]
### Environment

Running docker image getsentry/relay:23.5.0  on nomad

Same thing on symbolicator

### Steps to Reproduce
resolv.conf
```
nameserver x.x.x.x
nameserver y.y.y.y
option rotate timeout:2
```

### Expected Result

running 

### Actual Result
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Custom { kind: Other, error: "error reading DNS system conf: Error parsing resolv.conf: InvalidDirective(2)" } }', relay-server/src/actors/upstream.rs:719:14
```

**Comment by iker-barriocanal** [comment]
Hi. Reading the error you pasted, it seems to me this is a configuration error.

> `error: "error reading DNS system conf: Error parsing resolv.conf: InvalidDirective(2)"`

Could you verify the relay configuration is correct, and share it so I can try to debug it? Thanks!

**Comment by luckyraul** [comment]
```
relay:
  upstream: "http://192.168.1.14:29581/"
  host: 0.0.0.0
  port: 3000
logging:
  level: WARN
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "192.168.1.15:29092"}
    - {name: "message.max.bytes", value: 50000000} # 50MB
  redis: redis://192.168.1.16:5656

**Comment by iker-barriocanal** [comment]
Are you self-hosting Sentry? Could you attach the whole error logs?

**Comment by luckyraul** [comment]
yes. That log above is the only log I have. Container starts and exits with that error.

**Comment by olksdr** [comment]
This looks like the upstream issue, see https://github.com/bluejekyll/trust-dns/issues/1131 

And looks like `reqwest` crate disables `trust-dns` by default, as this can be an issue, see https://github.com/seanmonstar/reqwest/pull/437 but we enable it explicitly https://github.com/getsentry/relay/blob/f6e486a51834423da0807a4f4cdcb5bd5980e692/relay-server/src/actors/upstream.rs#L709-L718

@luckyraul , looks one the options in your `resolv.conf` cannot be parsed properly , either `rotate` or `timeout`. 
For a quick fix you could update  your `resolv.conf` and remove the options.
I can open the PR to disable this feature on our end and can discuss with a team further if that's something we can do as well.

**Comment by luckyraul** [comment]
I just want to prevent a crash. I have already changed my resolv.conf.

**Comment by olksdr** [comment]
@luckyraul  thanks for the update! 
and looking at the provide in the description of this issue config, there was a type `option rotate timeout:2` should be `options` with `s` at the end. 

I'm closing this issue then, since everything is worked out for you. 
Please, reopen if there are more questions about this.

**Comment by defp** [comment]
some issue 
```
ubuntu@ubuntu:~/apps/sentry-self-hosted$ docker compose logs relay
sentry-self-hosted-relay-1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Custom { kind: Other, error: "error reading DNS system conf: Error parsing resolv.conf: InvalidOption(1)" } }', relay-server/src/actors/upstream.rs:721:14
sentry-self-hosted-relay-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
sentry-self-hosted-relay-1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Custom { kind: Other, error: "error reading DNS system conf: Error parsing resolv.conf: InvalidOption(1)" } }', relay-server/src/actors/upstream.rs:721:14
sentry-self-hosted-relay-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
sentry-self-hosted-relay-1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Custom { kind: Other, error: "error reading DNS system conf: Error parsing resolv.conf: InvalidOption(1)" } }', relay-server/src/actors/upstream.rs:721:14
sentry-self-hosted-relay-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
sentry-self-hosted-relay-1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Custom { kind: Other, error: "error reading DNS system conf: Error parsing resolv.conf: InvalidOption(1)" } }', relay-server/src/actors/upstream.rs:721:14
sentry-self-hosted-relay-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
sentry-self-hosted-relay-1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Custom { kind: Other, error: "error reading DNS system conf: Error parsing resolv.conf: InvalidOption(1)" } }', relay-server/src/actors/upstream.rs:721:14
```
getsentry/relay:23.8.0
