### ISSUE TITLE
Encode namespace into kafka message header for metrics

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#2233]
via @john-z-yang 

The generic metrics platform would like to implement a kill switch that shuts down certain metrics from a specific namespace (aka use case ID).

Since all (generic) metrics are sent over the same Kafka topic, to determine the namespace of a metric requires us to parse the message, which is still computationally expensive.

We would like to have a lighter weight mechanism to do this. We propose that the ingest platform encode the namespace into the message header so that we do not need to parse the entire message.

**Comment by olksdr** [comment]
hey @john-z-yang,
Are the headers already parsed on your side? Or rather, if we deploy the changes from PR https://github.com/getsentry/relay/pull/2281 will it break anything or those headers will be just ignored for now?

**Comment by john-z-yang** [comment]
> 



> hey @john-z-yang, Are the headers already parsed on your side? Or rather, if we deploy the changes from PR #2281 will it break anything or those headers will be just ignored for now?

Hey Sorry I missed this message, we're not parsing the headers as of now
