### ISSUE TITLE
Return Cross-Origin-Resource-Policy (CORP) header for CSP reports

### ISSUE THREAD

**Issue by pbudzon** [getsentry/relay#2298]
### Problem Statement

We are trying to implement `Cross-Origin-Embedder-Policy: require-corp` header on our web app and while sentry SDK works correctly, we are having issues with Content-Security-Policy reports failing to be sent, because the sentry's endpoint does not return the `Cross-Origin-Resource-Policy: cross-origin` header (or any all). 

Attaching screenshot from Chrome's console about the request (ignore the rate limiting error):
<img width="1113" alt="Screenshot 2023-07-05 at 12 57 33" src="https://github.com/getsentry/sentry/assets/1087886/392db296-93b5-470c-97b0-d42bdaed5368">

### Solution Brainstorm

Return `Cross-Origin-Resource-Policy: cross-origin` header from the security headers reports endpoint. This will tell the browsers that you are consciously allowing cross origin requests to this endpoint (which is its purpose, anyway). This is an extension of CORS headers.

Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy

### Product Area

Issues - Suggested Fix

**Comment by lobsterkatie** [comment]
Routing to @getsentry/security.

**Comment by leedongwei** [comment]
@pbudzon Thanks for the feedback. I've added it as an agenda item for the backend committee and I'll update again in 2-ish weeks.

**Comment by leedongwei** [comment]
@pbudzon FYI that I moved this issue. The team that owns the API will help you with it.

**Comment by olksdr** [comment]
I believe we do return this header in [`the newest release`](https://github.com/getsentry/relay/releases/tag/23.8.0), done in https://github.com/getsentry/relay/pull/2394

Please, reopen if there are any concerns or errors. Thank you.
