### ISSUE TITLE
Improve documentation about deploying to popular cloud services and default for Docker

### ISSUE THREAD

**Issue by jernejstrasner** [getsentry/relay#2419]

**Comment by souredoutlook** [comment]
Some comments from a [recent ticket](https://sentry.zendesk.com/agent/tickets/99666) about related to this issue:

With regards to lack of opinionated deployment strategies for different cloud hosting environments:

>Most of software companies would provide their requirement in settings (if any) for Cloud, as GCP, AWS or Azure have been taking quite a lot of market, and I believe you should really have your service fully test with Cloud, otherwise customers will just pick the products with Cloud supported.

With regards to the default state of the Relay image requiring multi-step configuration for any mode other than proxy with HTTP:

>"For the Docker image, I don’t against that customers need to do minimal configuration, BUT your Docker Hub image, at least need to be able to load into Google service first, in order for customers to add another config, so far your image cannot even be loaded."
>
>"The manually way is not doing good as without using regular Google Cloud Docker feature. Most of Cloud services, just do the “pull” then “run” when brining images from Docker hub."

### Additional Context

It's worth noting that for any cloud hosting environment a great deal of manual orchestration is required as a Relay's public key must be registered with Sentry before that instance can be run in managed mode (most useful for PII scrubbing on preferred sub-processor) even if all other aspects like CA bundle colocation and configuration, mode, port, logging level, keys etc. were available to the instance at runtime.

### Brainstorm

Ideally the run command for a customer of Sentry would take a mode, and an auth token as environment variables on the container and handle configuration, registration and boot-up on it's own with minimal interaction or steps. This would help us achieve the goal of simplified instructions across different cloud hosting environments. The only other instructions required would be opinionated instructions for configuring load balancing by vendor and deployment tool.

**Comment by iambriccardo** [comment]
Closing this issue since we have one more descriptive here: https://github.com/getsentry/team-ingest/issues/275.
