### ISSUE TITLE
Not properly binding the port since 23.4.0 (therefore unable to deploy to AWS app runner)

### ISSUE THREAD

**Issue by tuky** [getsentry/relay#2423]
### The Problem
Starting with version `23.4.0` I cannot deploy the image to AWS app runner anymore. It seems the new version does not properly / "eagerly" bind the port. I cannot understand the issue, as I am not into Rust. But at least I can prove there is a problem, so thank you for your help:

### Environment

Official docker image from docker hub at versions `23.3.1`, `23.4.0` and `latest`.

### Steps to Reproduce

Run the image with this command:

```sh
docker run --rm -it -p 3000:3000 getsentry/relay:23.4.0 bash -c "apt update && apt install -y python3 && python3 -m http.server --bind 0.0.0.0 3000 & sleep 10 && relay run --mode proxy --host 0.0.0.0 --port 3000"
```

This looks weird at first, but is to prove that the new HTTP server is not properly binding the port. What I am doing here is installing `python3` to run an HTTP server on port 3000 in the background, then sleeping a bit and launching `relay` in foreground on the same port. Until `23.3.1` this is not possible as the service crashes with

```
ERROR relay_log::utils                         > bind to interface failed
caused by: Address already in use (os error 98)
```
But starting with `23.4.0` the port is not properly bound and the service keeps running. 

Of course, in AWS app runner I am not launching any python3 HTTP stuff, but still the port cannot be bound and the health check keeps failing.

### Expected Result

As with `23.3.1` a port failure from

```sh
docker run --rm -it -p 3000:3000 getsentry/relay:23.3.1 bash -c "apt update && apt install -y python3 && python3 -m http.server --bind 0.0.0.0 3000 & sleep 10 && relay run --mode proxy --host 0.0.0.0 --port 3000"
```

![image](https://github.com/getsentry/relay/assets/2981274/1fd80cf0-b07a-43d0-a3ee-08465bb17d85)

### Actual Result

Also with `latest`, no complaint about port 3000 already in use:

```sh
docker run --rm -it -p 3000:3000 getsentry/relay:latest bash -c "apt update && apt install -y python3 && python3 -m http.server --bind 0.0.0.0 3000 & sleep 10 && relay run --mode proxy --host 0.0.0.0 --port 3000"
```

![image](https://github.com/getsentry/relay/assets/2981274/ed1012d2-19b9-40b3-b2b7-639a37f1cbab)

**Comment by jjbayer** [comment]
@tuky thanks for reporting, we will fix this!
