### ISSUE TITLE
Default PII config

### ISSUE THREAD

**Issue by iluuu1994** [getsentry/relay#243]
I'd like to use semaphore in `proxy` mode. Thus I do not create a project.json file per project. Unfortunately, according to the [documentation](https://github.com/getsentry/semaphore/blob/master/docs/quickstart.md) at least, the pii can only be set in the project.json file.

It would be nice if the global settings could be changed. In our case, we'd like to track the e-mail and ip addresses.

WDYT?

Thanks!

**Comment by jan-auer** [comment]
You can use the `static` mode for this. I believe this is not documented, sorry about that.

**Comment by iluuu1994** [comment]
Thanks @jan-auer for your reply!

The docs say this:

> `static`: Projects must be statically configured on the file system. If configured, PII stripping is also performed on those events. Events for unknown projects are automatically rejected.

Doesn't this imply having to configure all the projects manually? The `proxy` mode so far look great, except that we'd like to change the default value of the pii config for all projects.

**Comment by iluuu1994** [comment]
What's also funny is that the docs say:

> `proxy`: Relay acts as a proxy for all requests and events. It will not load project configurations from the upstream or perform PII stripping. All events are accepted unless overridden on the file system.

But it does, e-mails, ips, user paths, etc. are now hidden.

**Comment by untitaker** [comment]
A lot of stuff happened on this front. Is this still broken for you?

**Comment by iluuu1994** [comment]
Not sure, we're still using an older version of Semaphore. I'll close the issue. If we update and I have any issues I'll let you know. 🙂

**Comment by untitaker** [comment]
Thanks! We have flipped half of the codebase upside down there and it's sometimes hard to keep track what behaves differently and what doesn't.
