### ISSUE TITLE
session replays not being relayed, potentially because of unknown rate limit.

### ISSUE THREAD

**Issue by agoddard** [getsentry/relay#2435]
### Environment

1) relay 23.8.0, executing linux binary, also seeing the same with 23.8.0 running under docker with official image
2) self-hosted sentry, 23.8.0

(New install, so this has never worked on this install)

### Steps to Reproduce

1. configure SDK to send session replays
2. witness session replays being sent, by inspecting XHR requests in browser console
3. configure DSN to send data directly to sentry, see replay available in sentry UI
4. configure DSN to send via relay using either static or proxy mode, witness no session replays being created (but witness error reports and performance data created fine)

### Expected Result

Session replays created when using relay just as they are when sending direct to sentry

### Actual Result

No session replays ever created when relay in use. The following log is frequent when running with DEBUG level:

```{"timestamp":"2023-08-29T08:45:27.169806Z","level":"DEBUG","message":"dropped envelope: rate limited","target":"relay_server::utils::managed_envelope","filename":"relay-server/src/utils/managed_envelope.rs","line_number":292}```

Some additional context around this log line:

```
{"timestamp":"2023-08-29T08:55:00.847840Z","level":"DEBUG","message":"started processing request","target":"tower_http::trace::on_request","filename":"/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-http-0.4.0/src/trace/on_request.rs","line_number":91,"span":{"method":"POST","uri":"/api/2/envelope/?sentry_key=xxxxxxxxxxx&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.64.0","version":"HTTP/1.1","name":"request"},"spans":[{"method":"POST","uri":"/api/2/envelope/?sentry_key= xxxxxxxxxxx&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.64.0","version":"HTTP/1.1","name":"request"}]}
{"timestamp":"2023-08-29T08:55:00.848128Z","level":"TRACE","message":"queueing separate envelope for non-event items","target":"relay_server::endpoints::common","filename":"relay-server/src/endpoints/common.rs","line_number":286,"span":{"method":"POST","uri":"/api/2/envelope/?sentry_key= xxxxxxxxxxx&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.64.0","version":"HTTP/1.1","name":"request"},"spans":[{"method":"POST","uri":"/api/2/envelope/?sentry_key= xxxxxxxxxxx&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.64.0","version":"HTTP/1.1","name":"request"}]}
{"timestamp":"2023-08-29T08:55:00.848208Z","level":"TRACE","message":"queueing envelope","target":"relay_server::endpoints::common","filename":"relay-server/src/endpoints/common.rs","line_number":307,"span":{"method":"POST","uri":"/api/2/envelope/?sentry_key= xxxxxxxxxxx&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.64.0","version":"HTTP/1.1","name":"request"},"spans":[{"method":"POST","uri":"/api/2/envelope/?sentry_key= xxxxxxxxxxx&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.64.0","version":"HTTP/1.1","name":"request"}]}
{"timestamp":"2023-08-29T08:55:00.848274Z","level":"DEBUG","message":"finished processing request","latency":"0 ms","status":200,"target":"tower_http::trace::on_response","filename":"/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-http-0.4.0/src/trace/on_response.rs","line_number":254,"span":{"method":"POST","uri":"/api/2/envelope/?sentry_key= xxxxxxxxxxx&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.64.0","version":"HTTP/1.1","name":"request"},"spans":[{"method":"POST","uri":"/api/2/envelope/?sentry_key= xxxxxxxxxxx&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.64.0","version":"HTTP/1.1","name":"request"}]}
{"timestamp":"2023-08-29T08:55:00.848300Z","level":"DEBUG","message":"dropped envelope: rate limited","target":"relay_server::utils::managed_envelope","filename":"relay-server/src/utils/managed_envelope.rs","line_number":292}
{"timestamp":"2023-08-29T08:55:00.848346Z","level":"DEBUG","message":"dropped envelope: rate limited","target":"relay_server::utils::managed_envelope","filename":"relay-server/src/utils/managed_envelope.rs","line_number":292}
```

Relay config as follows:
```
relay:
  mode: static
  upstream: <upstream_url>
  host: 0.0.0.0
  port: 4600
  tls_port: null
  tls_identity_path: null
  tls_identity_password: null
sentry:
  enabled: true
  dsn: <dsn>
logging:
  level: trace
  format: json
limits:
  max_concurrent_requests: 10000
  max_connection_rate: 10000
  max_session_count: 10000
  max_concurrent_queries: 100
  max_event_size: '10MiB'
  max_attachment_size: '100MiB'
  max_envelope_size: '100MiB'
  max_api_payload_size: '50MiB'
  query_timeout: 60

```
(I have experimented with various options in terms of limit, these might be excessive, but nothing has made a difference so far, there is only a small amount of data being sent to this relay and sentry presently)

projects are basic config, i.e.
```
{
	"slug": "slug1",
	"disabled": false,
	"publicKeys": [
		{
			"publicKey": "xyz",
			"isEnabled": true
		}
	],
	"config": {
		"allowedDomains": ["example.com", "other.example.com"]
	}
}
```

I haven't yet (but will) test the relay against sentry.io as well.

**Comment by agoddard** [comment]
another thing to note, the SDK requests containing the session replays always succeed, get a `200` response, with the ID contained in the response.

**Comment by agoddard** [comment]
Confirmed that this is also happening when relaying to sentry.io, so something specific to the relay environment for sure.

**Comment by agoddard** [comment]
Switching to managed mode fixed this, I might have missed that it's a limitation or static/proxy mode, or perhaps managed mode is letting the relay know that it has quota available for replays?

**Comment by jjbayer** [comment]
@agoddard thanks for reporting this! In static mode, does adding the following to your static project config solve the issue?

```js
{
	// ...
	"config": {
		"allowedDomains": ["example.com", "other.example.com"],
		"features": ["organizations:session-replay"]
	}
}
```

In a future version of Relay, this feature will be enabled by default.

**Comment by agoddard** [comment]
@jjbayer yep, that fixed it - thank you! I had not seen this list previously https://getsentry.github.io/relay/relay_dynamic_config/enum.Feature.html
