### ISSUE TITLE
panic in android_trace_log

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#2451]
> invalid or out-of-range datetime

Panic occurs here: https://github.com/getsentry/relay/blob/63390b6da1e03bf437e4da0e7d903bef98e2d268/relay-profiling/src/android.rs#L115

Presumably because of call to panicking function here: https://github.com/chayleaf/android-trace-log/blob/master/src/lib.rs#L849

See [RELAY-2NNP](https://sentry.my.sentry.io/organizations/sentry/issues/399461)

**Comment by jjbayer** [comment]
Opened a pull request against the library: https://github.com/chayleaf/android-trace-log/pull/2

**Comment by chayleaf** [comment]
resolved in 0.3.0 of the library

**Comment by jjbayer** [comment]
> resolved in 0.3.0 of the library

@chayleaf thank you so much!
