### ISSUE TITLE
Allow-/deny-list for custom metrics and tags

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/relay#2459]
Sentry does not require any configuration to send new metrics (DDM) from SDKs, by default every new metric is ingested and stored. This can be undesirable in a number of cases:
 1. The developer accidentally sends a metric they do not want to ingest anymore.
 2. The developer accidentally sends a tag they do not want to ingest anymore.
 3. In a frontend project with exposed DSN, the developer expects allow listing of metrics and tags.

To make this configurable, Relay should support both allow-listing and deny-listing metrics and tags so that the product can push out configuration. While this is project-level configuration, the existing project configs are not ideal for very large lists. We may need to look into better mechanisms to send large amounts of config to Relay.

**Comment by jan-auer** [comment]
**Note:** Updated the description.
