### ISSUE TITLE
Crons: Move rate limiter to Relay instead of consumer

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/relay#2490]
Currently rate limiting is handled in our consumer [[code here](https://github.com/getsentry/sentry/blob/33e91f2a857e70bf4dcee20f6c4faa94e02aa1a1/src/sentry/monitors/consumers/monitor_consumer.py#L181-L198)].

This is a problem for a couple of reasons.

1. The consumer is not free, the more messages we process in our consumer more consumer horsepower we need. Without rate-limiting of the message prior to a check-in being sent to kafka, the consumer becomes susceptible to a large spikes in traffic from a single user.

2. Because we're using semantic partition (https://github.com/getsentry/relay/pull/2496) and partitioning by monitor slug, it means a single bad actor can dramatically increase load in a single partition.

   This is made worse by the fact that consumer partitions need to move at somewhat the same rate otherwise our clock significantly slows down.

What we would like to do is have ingestion rate-limited in relay. This should be done on a **per monitor slug, per environment key**. NOT per project ID. project rate limiting is not ideal because there can be many cron monitors on one project. Where as if we rate limit by `(monitor_slug, environment)` we can limit to a reasonable value like `5 check-ins per minute`.

**Comment by evanpurkhiser** [comment]
From @jan-auer 

> Relay‘s current rate limiting works per project, which allows us to limit with minimal state and without even parsing the payload, as well as send hard backoffs to clients. That’s the reason why it’s so fast. Per-slug rate limiting makes this harder

**Comment by evanpurkhiser** [comment]
@jan-auer could you share where the rate limiting is implemented?

Sounds like it's happening very early, before we're even unmarshalling json right. And I'm guessing we don't have any kind of precedent for rate-limiting after we've parsed the envelope?

One other thing we can consider, and Filippo pointed this out, is that we can do rate-limiting in memory on our consumer instead of using our Redis rate limiter, which would presumably be a good bit more performant.

We're also considering using multi-threading for our consumer, which should significantly help with performance and perhaps make this requirement moot.

**Comment by evanpurkhiser** [comment]
Alright. Had a discussion with @mitsuhiko @jan-auer and @olksdr about this.

We're going to implement rate limiting via a QuotaConfig from sentry computed based on the number of monitors for each project.

This is now being tracked here https://github.com/getsentry/sentry/issues/60303

**Comment by mitsuhiko** [comment]
This issue is no longer applicable. Closing.
