### ISSUE TITLE
Provide interface to dynamically enable / disable relaying

### ISSUE THREAD

**Issue by remod** [getsentry/relay#2492]
**Use Case**
We've started to use Sentry on our autonomous mobile robot, but I think this feature request can apply to IoT with limited upload bandwidth in general.

**Challenge** 
During operation, the robot collects data and sends it to a user and/or server. As network bandwidth is a very scarce resource, we'd like to prioritize uploading operational data over uploading error reports. 

**Feature Request**
Ideally, the robot has control over when error reports should be uploaded and when not. I was wondering whether it would make sense to be able to toggle the Sentry relay between "receive and cache error reports" and "receive and upload error reports"? 

Alternative approaches which sound a bit more "brutal" to me:
* kill and respawn the relay on demand
* tell the OS to disallow communication to the IP of Sentry's server in some cases

Inputs welcome!

**Comment by iker-barriocanal** [comment]
Hi @remod! Could you provide some more details on what your setup looks like? It'd be helpful to know what SDK you're using, where are you running Relay...

**Comment by remod** [comment]
Hi @iker-barriocanal !

At the moment we use the Sentry Native and the Angular SDKs, in the future we plan to additionally use the Python SDK. We have around 100 processes distributed over two onboard computers which instantiate a Sentry client and directly talk to the Sentry SaaS instance in case of an event.

There is no relay yet, but I'd have added it directly on one of the two onboard computers. I believe that apart from "toggling" the upload of error reports it might also be useful as a single central place to monitor and control Sentry traffic.

**Comment by jernejstrasner** [comment]
@remod you should be able to achieve what you want with some configuration work directly with the SDKs, no Relay required. You would need to use a custom flag/remote config solution though.

Native: https://docs.sentry.io/platforms/native/configuration/transports/
Angular: https://docs.sentry.io/platforms/javascript/guides/angular/configuration/transports/

Check the above docs and let us know if we're misunderstanding.

**Comment by remod** [comment]
Hi @jernejstrasner 

Thank you for your response! You're right, it looks like it is possible to achieve in the SDKs.

From an architectural point I assume it would be beneficial to centralize this "send/cache" decision in a relay because it avoids code / logic duplication and the offline cache would be "global", allowing us to configure its overall size resp. number of errors to keep.

I leave it up to you if you want to close this feature request or keep it open as improvement over the SDK solution.

**Comment by iker-barriocanal** [comment]
I'll close this ticket as the question has been resolved, but we'll reopen it again if there are more use cases for this in the future!
