### ISSUE TITLE
Scrub auth tokens anywhere

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#2567]
Currently we do not scrub bearer tokens everywhere, e.g.

```json
{
    "vars": {
        "headers": [
            ["authorization", "Bearer abc123"]
        ]
    }
}
```

We do not treat `["authorization", "Bearer abc123"]` as a key-value pair, so we scrub the _key_, but not the value (see [code](https://github.com/getsentry/relay/blob/c4c6fc6104be17b7f753134fea92c0354dc9164d/relay-pii/src/processor.rs#L326-L328)).

Possible solutions:

1. Redact `Bearer <hex>` anywhere in a string (as we do for credit card numbers).
2. Build a heuristic that treats list of pairs as key-value mappings.

**Comment by olksdr** [comment]
### Actions: 

* We want to try to implement option 2 - this is more generic and should support and catch more stuff. 
  * make the rules match on pairs

**Comment by antonpirker** [comment]
Maybe related:
We have an issue in the Python SDK repo: https://github.com/getsentry/sentry-python/issues/2417

A user sends a Breadcrumb that contains sensitive data in the breadcrumb message (see reproduction event here: https://sentry-sdks.sentry.io/issues/4535377485/?project=5461230&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=4 )

The breadcrumb message string contains `'Authentication': 'SECRET'` which is not scrubbed by Relay.

**Comment by dcramer** [comment]
I'd start with implementing this on the server, and probably just have it be a "scrub-next-token" behavior if the value is identified in a tuple/list. Obviously you could look for tuples, and I'm sure next token won't always be valid, but given the intent of scrubbers its always better to be safe.

**Comment by Dav1dde** [comment]
Option 1 was implemented with https://github.com/getsentry/relay/pull/3484
