### ISSUE TITLE
Make global config required for processing

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#2584]
Before a global config is loaded / if a global config cannot be loaded during an incident, we currently fall back to using a default global config everywhere.

There are several use cases where if we actually want to rely on dynamic configuration, we have to be able to load it, e.g.

* When we move span metrics extraction config to sentry,
* when we move config for generic inbound filters to sentry.

## Solution

Just like envelopes get buffered until a valid project state is available, we should queue envelopes until a valid global config is available.

**Comment by TBS1996** [comment]
finished with #2765
