### ISSUE TITLE
Values promoted to tags should handle newlines consistently

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/relay#2601]
### Environment

SAAS

### Steps to Reproduce

A customer ran into a problem where searching for `user:"id:LTMHC2KW3651834"` didn't work but searching for `user:"id:LTMHC2KW3651834*"` did work. Also, from the issue details page, if they clicked on the tag value to search for all events with that tag, the first search was performed and nothing came back.

### Expected Result

All of the above should work, without needing the `*`.

### Actual Result

It doesn't. 

The problem turned out to be twofold:
1. The user was accidentally sending a newline at the end of their user id value.
2. The event JSON revealed that the newline was getting stripped in one place (`event.tags.user` was `"id:LTMHC2KW3651834"`) but not another (`event.user.id` was `"LTMHC2KW3651834\n"`). Clicking on the tag value populated a search with the former, but in snuba it was being compared against the latter.

We should handle newlines consistently when it comes to non-tag values we convert to tags: if we're going to strip them in the tag, we should strip them in the original, or if we don't want to strip them in the original, we shouldn't strip them in the tag.

Semi-related: https://github.com/getsentry/relay/issues/1015

**Comment by olksdr** [comment]
@lobsterkatie we can take this into our TODO list, but it can take a bit time for us to get to it. But you're also welcome to contribute if you'd like 😄

**Comment by lobsterkatie** [comment]
> you're also welcome to contribute if you'd like 😄

Just as soon as I learn rust! 😛 

Legit, though, I think the first thing to be done is to decide what the correct behavior here is (strip newlines? keep them?), and to which specific parts of the event schema it applies. Once we do that, we could at least throw a `Help Wanted` tag on here.

**Comment by iambriccardo** [comment]
Took a closer look, we are doing `\n` normalization in Relay for any tag value. My hunch is that Relay receives the tag value, and normalizes it but the `user` object of the field, contains all the original user values.

The UI then uses the tag value for autocomplete but then looks for the `user` field which is a column likely created from a non-normalized field.

**Comment by iambriccardo** [comment]
Will investigate the consumer implementation to see how tags are mapped into columns:
> Produce the occurrences [here](https://github.com/getsentry/sentry/blob/master/src/sentry/issues/producer.py#L50) and they are processed and saved by the consumer [here](https://github.com/getsentry/sentry/blob/master/src/sentry/issues/ingest.py#L42), which also creates the related group.

**Comment by iambriccardo** [comment]
Currently closing this ticket because we didn't have enough time to dive deep into it. Will re-open in case the problem escaltes.
