### ISSUE TITLE
Safe fields not working when data is an array

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/relay#2605]
When running a python app from console the `sys.argv` has some information being filtered by Sentry default data scrubbing. This information is useful and I do not want filtered.

### Steps to Reproduce

run a python scrip that throws an error, for example: `python3 test.py password`
test.py and password will be added as extra context by the SDK: `{'extra': 'sys.argv': ['test.py', 'password']}`
add sys.argv in project settings -> security and privacy -> safe fields

### Expected Result
the information in the event is not scrubbed

### Actual Result
the information is scrubbed
```
sys.argv	
[
test.py, 
[Filtered]
]
```

From testing, this happens with any extra context that is added as an array, and none of the following worked:
sys.argv
extra.sys.argv
extra.'sys.argv;
extra.'sys.argv'.* (taken from the Advanced scrubbed rules suggestion)
extra.sys.argv.**
extra.sys.argv.[*]

I also tested with another field without a dot in its name, the behaviour is the same. 

What is the correct syntax to prevent default data scrubbers to scrub information from arrays in extra? Or is it a current limitation?

**Comment by jjbayer** [comment]
Was able to confirm that `exclude_fields` does not work with arrays in this unit test: https://github.com/getsentry/relay/pull/2610

**Comment by Dav1dde** [comment]
@rodolfoBee we've rolled out a change which allows the advanced expressions syntax in the safe fields field now, meaning you should be able to exclude your array using `extra.'sys.argv'.**`
