### ISSUE TITLE
Cannot enable spooling with provided docker image or binary

### ISSUE THREAD

**Issue by remod** [getsentry/relay#2617]
*Note: I haven't found any help / documentation online, so I might be doing something wrong.*

### Environment

Sentry Relay Docker Image: `getsentry/relay:23.10.0`

### Steps to Reproduce

1. Created configuration file at `/usr/share/sentry_relay/config.yml`:
   ```
   relay:
     mode: proxy
     upstream: ...
     host: 0.0.0.0
     port: 3000
     tls_port: null
     tls_identity_path: null
     tls_identity_password: null

   spool:
     envelopes:
       path: /var/spool/sentry_relay/file
   ```
1. Run relay in docker: `docker run --rm -it -v /usr/share/sentry_relay/:/work/.relay/:ro -v /home/remod/.spool/sentry_relay/envelopes/:/var/spool/sentry_relay/:rw -p 3000:3000 getsentry/relay:23.10.0 run`

### Expected Result

Relay starts successfully with spooling enabled.

I expect that the relay writes the spooled data into the file `/var/spool/sentry_relay/file` within docker which corresponds to `/home/remod/.spool/sentry_relay/envelopes/file` on the host system.

### Actual Result

I am getting an error:

```
 INFO relay::setup: launching relay from config folder /work/.relay
 INFO relay::setup:   relay mode: proxy
 INFO relay::setup:   relay id: -
 INFO relay::setup:   public key: -
 INFO relay::setup:   log level: DEBUG
 INFO relay_server: relay server starting
 INFO relay_server::actors::outcome: Configured to emit outcomes as client reports
 INFO relay_server::actors::processor: starting 16 envelope processing workers
 INFO relay_server::actors::global_config: global config service starting
 INFO relay_server::actors::global_config: serving default global configs due to lacking static global config file
 INFO relay_server::actors::outcome: OutcomeProducer started.
 INFO relay_server::actors::project_cache: project cache started
 INFO relay_server::actors::outcome_aggregator: outcome aggregator started
 INFO relay_server::actors::spooler: buffer file /var/spool/sentry_relay/file
 INFO relay_server::actors::spooler: max memory size 500000000
 INFO relay_server::actors::spooler: max disk size 500000000
 INFO relay_metrics::router: metrics router started
 INFO relay_server::actors::relays: key cache started
 INFO relay_server::actors::envelopes: envelope manager started
 INFO relay_server::actors::server: spawning http server
 INFO relay_server::actors::server:   listening on http://0.0.0.0:3000/
ERROR relay_server::actors::project_cache: failed to start buffer service error=failed to setup the database: error returned from database: (code: 14) unable to open database file
```

The only way I manage to get the relay to start successfully with spooling is to configure the file to lie _directly_ in `/tmp`.

```
spool:
  envelopes:
    path: /tmp/file
```
Even setting the path to `/tmp/folder/file` results in the error, which makes me wonder whether the relay cannot create new directories? However, in the original example the docker directory mapping should not even require the creation of a new directory inside the docker image, as the file directly lies in `/var/spool/sentry_relay`.

For me the `/tmp` folder is not a sufficient solution because I need the spooled events to survive a restart of the docker container, and even a restart of the entire computer.

**Comment by iker-barriocanal** [comment]
Hi! How are you dealing with the directory to place the spool file? If you haven't configured anything, docker will not persist the file, [see docs](https://docs.docker.com/storage/). Using a [volume](https://docs.docker.com/storage/volumes/) may be a great choice here.

**Comment by remod** [comment]
Hi @iker-barriocanal !

I am mounting the host directory as volume into the docker container: `-v /home/remod/.spool/sentry_relay/envelopes/:/var/spool/sentry_relay/:rw` and then configure Sentry to write to `/var/spool/sentry_relay/file`.

I expect that this creates the file `/home/remod/.spool/sentry_relay/envelopes/file` in the host system, which may be owned by `root` but I'd be fine with that.

**Comment by iker-barriocanal** [comment]
I'm not sure what may be missing off the top of my head, I'll add this to the backlog and the team will get back soon.

**Comment by iker-barriocanal** [comment]
I've tried replicating it and I'm not able to -- the same commands (changing directories) to the ones on my machine works as expected. Does your local filesystem and docker have enough disk space?

**Comment by remod** [comment]
@iker-barriocanal Thank you for iterating! :+1: 

Yes, I have 40 GB free disk space, and the created spool file upon spawning the relay is only 24 KB in size.

I could recreate the issue by running the provided executable instead of the docker image (also 23.10.0, downloaded from [GitHub](https://github.com/getsentry/relay/releases/download/23.10.0/relay-Linux-x86_64)):

When I run `~/Downloads/relay-Linux-x86_64 run --config /usr/share/sentry_relay/config.yml`

1. with `path` set to `/var/spool/sentry_relay/file` it fails. This is expected because the executable does not have root permissions.
1. with `path` set to `/tmp/not_yet_existing_subfolder/file` it fails. This is unexpected, I'd expect subfolders to be created automatically.
1. with `path` set to `/tmp/file` it succeeds. This is expected, but I don't want to lose spool data upon restarting.
1. with `path` set to `~/file` it fails. This is unexpected. As I can't use `/var` I'd like to use the home directory of the respective user as it is persistent.
1. with `path` set to `/home/remod/file` it succeeds. This is expected, but I don't want to hardcode the username.
1. with `path` set to `/home/remod/not_yet_existing_subfolder/file` it fails again, same as 2.?

My OS is Ubuntu 20.04 LTS.

My file system permissions in `/`:

```
drwxrwxrwt  38 root root  32K Okt 19 09:15 tmp
drwxr-xr-x  17 root root 4.0K Okt 12  2022 var
```

**Comment by iker-barriocanal** [comment]
Thanks for your detailed response! I've been able to replicate the two issues:

- For case 4, it seems that sqlx, the tool we use for spooling, doesn't handle correctly relative paths.
- For cases 2 and 5, only the spool file was created and not the directories in between.

I've tried providing a more meaningful error message for case 4 and creating the directories for cases 2 and 5 in https://github.com/getsentry/relay/pull/2636. In the meantime, creating the directory (excluding the file) and providing an absolute path in the config should get you unblocked.

**Comment by remod** [comment]
Thank you very much @iker-barriocanal !

After talking to a colleague we've agreed to store the file in `/var/tmp`. It is absolute, writable without root permissions and survives a reboot. It's great if we can have subfolders for more expressive folder structures, thank you for this new feature!

I'd suggest to close this issue with your PR then.

**Comment by iker-barriocanal** [comment]
My initial analysis was inaccurate and relative paths are supported, the caveat is that `~` is interpreted as a literal. https://github.com/getsentry/relay/pull/2636 still creates the required directories, and both things are documented in https://github.com/getsentry/sentry-docs/pull/8306. The relay binary and the docker image will be updated in the next calendar release. Let me know if you have any further questions!

**Comment by remod** [comment]
@iker-barriocanal Fantastic, thank you!
