### ISSUE TITLE
Patch sentry-getsentry/relay:23.9.1 to the latest version 

### ISSUE THREAD

**Issue by ziler-orca** [getsentry/relay#2619]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

v2.21.0

### Steps to Reproduce

After running a scan on sentry packages, the sentry-getsentry/relay:23.9.1 image reported several vulnerabilities. Please see attached for details.

[relay_cves.xlsx](https://github.com/getsentry/self-hosted/files/12924097/relay_cves.xlsx)

### Expected Result

Reported vulnerabilities should be patched.

### Actual Result

The package lists several vulnerabilities.

**Comment by hubertdeng123** [comment]
The CVEs, given to us by the security team. 

[relay_cves.csv](https://github.com/getsentry/relay/files/12961797/relay_cves.csv)

**Comment by iker-barriocanal** [comment]
Thanks for reporting! The team will look at it soon.

**Comment by iker-barriocanal** [comment]
Hi, would it be possible to get an update on the list of these issues? https://github.com/getsentry/relay/commit/899d5f367ba330beb0342d59d66bc247735db394 updated the base Debian image v10 -> v12, so some issues may already be addressed by that. Thanks!

**Comment by hubertdeng123** [comment]
Looks like this is good to close, since the rest of CVE's do not have fixes available from slack thread in #discuss-security
