### ISSUE TITLE
Accept `csp-violation` reports?

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#2645]
We see a lot of security reports that fail parsing because they have `type:csp-violation`, which we do not support.

1. Is this a well-known type that we should support?
2. If so, extend the [security report types we support](https://github.com/getsentry/relay/blob/7e44fb03b58723cac120e1de1c7c6cecbea4532b/relay-event-schema/src/protocol/security_report.rs#L1056-L1062).

ref: [POP-RELAY-2TA](https://sentry.my.sentry.io/organizations/sentry/issues/395812/)
Ref: https://github.com/getsentry/sentry/issues/52794

**Comment by olksdr** [comment]
@oioki Hey, could you help us with this? 

Is there more info you could provide on `type:csp-violation`. Is this type a valid type for `csp` reports?
