### ISSUE TITLE
Relay Section Not Shown In Settings

### ISSUE THREAD

**Issue by rojinebrahimi** [getsentry/relay#2658]
Hi! I am running Sentry v23.10.1 and I have encountered the issue in which I am not able to see Relay settings in UI. Seems Sentry does not load the settings at all!
How can I find any clues related to the issue?

![Screenshot 2023-10-25 at 20 21 58](https://github.com/getsentry/relay/assets/44529498/1fb17937-ce81-4f2a-825e-5975c2fa0721)

**Comment by TBS1996** [comment]
closing duplicate
