### ISSUE TITLE
Graphql Scrubbing can't be disabled via the Data Scrubber toggle option

### ISSUE THREAD

**Issue by Fwang36** [getsentry/relay#2666]
### Steps to Reproduce
1. Disable the Data Scrubber in the project settings.
2. Send an event with a Graphql request body.
3.  See variables still scrubbed like the image in this [PR](https://github.com/getsentry/sentry-laravel/pull/720)
Specifically, I believe it is this[ rule in the repo](https://github.com/getsentry/relay/blob/75397010d18044a17759161e74475297fe9b0493/relay-pii/src/processor.rs#L218).

### Expected Result

Disabling the Data Scrubber should disable the scrubbing.

### Actual Result

Disabling the Data Scrubber does not disable the scrubbing.

**Comment by jjbayer** [comment]
@Fwang36 we're looking into it!

**Comment by TBS1996** [comment]
Looked a bit into this: 

It should only scrub graphql if it can create a piiconfig from datascrubbingconfig, which would be when `to_pii_config` returns Ok(Some()).   

So for the graphql to not be scrubbed, that function must return Ok(None) in [this line].(https://github.com/getsentry/relay/blob/08362f23bc3e23f076f80dd1efb05deec6e2c5d6/relay-pii/src/convert.rs#L125)

For that to happen, both datascrubbing have to be disabled, and ip address scrubbing must be disabled as well.   
 
Next step for me is to verify this, then think about any potential changes in behaviour.

**Comment by TBS1996** [comment]
problem is fixed now, deployed and I've verified that it works as expected. graphql scrubbing now depends on whether datascrubbing is enabled, and if it's not, it still respects the "prevent storing ip address" option
