### ISSUE TITLE
Config init via docker not possible

### ISSUE THREAD

**Issue by jglapa** [getsentry/relay#267]
Hi. I think I'm an early adopter but I really need to use the relay.

The installation instruction are really scarce and the only possibility to run  was to use the provided docker image.

The problematic thing is generating the initial config using the docker command:

`docker run -v $(pwd)/configs/:/etc/semaphore/ us.gcr.io/sentryio/semaphore config init --config /etc/semaphore`

There is a _rich console interaction_ in place and everything hangs or is refreshed without the possibility to exit or abort

![semaphore](https://user-images.githubusercontent.com/742104/66902239-9b703880-f000-11e9-806e-761729528780.gif)

I ended up logging into the container directly. Running the command in there and copying out the config outside.

**Comment by tonyo** [comment]
To start the container in the interactive mode and run commands such as `config init`, please add `-it` to your docker command, so it looks like `docker run -it -v $(pwd)/configs:...`.

> I really need to use the relay.

What is your use case, if you don't mind me asking?

**Comment by jglapa** [comment]
> To start the container in the interactive mode and run commands such as `config init`, please add `-it` to your docker command, so it looks like `docker run -it -v $(pwd)/configs:...`.

:+1: works fine indeed!

> > I really need to use the relay.

> What is your use case, if you don't mind me asking?

We host sentry on premise (in AWS) in a single region. 
We're experiencing big configuration overhead when it comes to inter-region connectivity. 
Having a relay in every region and configuring only it would be a major relief.
