### ISSUE TITLE
`request.headers` contains null values after processing

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/relay#2684]
A customer [reported](https://github.com/getsentry/sentry/issues/59034) (via @JLuse) that they were having a problem accessing the curl version of the request data on the issue details page. The issue turned out to be that we were trying to sort the headers before displaying them, and our sort function couldn't deal with the fact that some of the headers were null. (Not null values for named headers - multiple cases in which the entire entry in the `headers` array was null.)

We should definitely handle this better on the FE, but IMHO the null values also shouldn't have made it that far. Any reason not to drop them during ingest? Or is relay actually the source of the nulls? Either way, we should prevent them from ending up in the event.

**Comment by Dav1dde** [comment]
The `request.cookies` also has null values:

```json
    "cookies": [
        [
            "_mxxxx_xxx",
            "[Filtered]"
        ],
        // A bunch more cookies I removed
        [
            "SomeOther",
            "Value…"
        ],
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    "headers": [
        [
            "Accept",
            "*/*"
        ],
        [
            "Accept-Encoding",
            "gzip, deflate, br"
        ],
        [
            "Accept-Language",
            "en-GB,en-US;q=0.9,en;q=0.8"
        ],
        [
            "Connection",
            "close"
        ],
        [
            "Content-Length",
            "6298"
        ],
        // A bunch more headers I removed
        [
            "Content-Type",
            "application/json"
        ],
        null,
        null,
        null,
        null,
        null
    ],
```

**Comment by TBS1996** [comment]
Forwarding null values is expected behaviour from Relay, so you can look into why the SDK is sending it, or else continue working on how it's handled in FE.
