### ISSUE TITLE
Make it possible to create Investigation Bias with has:profile.id

### ISSUE THREAD

**Issue by matejminar** [getsentry/relay#2710]
Users would like to create Investigation Biases (reservoir rules that boost Dynamic Sampling to 100%) with the condition containing `has:profile.id`. This ticket is about the Relay part that's needed in order for this to happen.
Jan mentioned that we don't have `profile.id` exposed as a queryable field, actually, it's not a field at all.

**Comment by jjbayer** [comment]
We currently have the profile ID as a field on `contexts.profile.profile_id`, but

1. It's set in `process_profiles`, which happens after dynamic sampling.
2. (easy part) There is no getter for it yet.

https://github.com/getsentry/relay/blob/d19ec3ab494890a8e3f825705fb00d7fbe540df6/relay-server/src/actors/processor.rs#L1191

https://github.com/getsentry/relay/blob/d19ec3ab494890a8e3f825705fb00d7fbe540df6/relay-event-schema/src/protocol/event.rs#L724-L727
