### ISSUE TITLE
Replace invalid timezone with sensible default

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/relay#2718]
While working on https://github.com/getsentry/sentry-cli/pull/1807, I noticed that when an invalid timezone string is provided when configuring a cron monitor via monitor upserts, the monitor silently fails to be created in Sentry. This could lead to a scenario where a user, who has a typo in their timezone string, thinks that they have created a cron monitor. But, when they later go to Sentry to check on it, they will notice that their cron monitor is not actually there, and they will have no idea why. 

So, we should check in Relay whether the timezone string corresponds to a valid timezone, and if it does not, we should replace it with a sensible default (such as UTC time). Probably, the best option would be to treat an invalid timezone input as an absent timezone input, since we already are correctly handling the case of no timezone being provided.

**Comment by evanpurkhiser** [comment]
This may make more sense to be handled in our consumer

**Comment by jan-auer** [comment]
Can you share a repro, please?

**Comment by olksdr** [comment]
Please, re-open if there is a repro or any additional information we can act on. Thank you.

**Comment by Dav1dde** [comment]
We looked into it, Relay does not touch or parse the timezone. Additional validation will be added to the cli.

**Comment by szokeasaurusrex** [comment]
I have opened https://github.com/getsentry/sentry-cli/issues/1845 to validate the timezone string directly within the CLI.
