### ISSUE TITLE
Allow regex in allowed domains

### ISSUE THREAD

**Issue by taschik** [getsentry/relay#2740]
### Problem Statement

Hi I'd like to limit traffic to only specific domains and subdomains like `https://company-*.vercel.app` this sadly doesnt work right now and hence it would be good to get full regex support for allowed domain in the client security section of a projects settings.

### Product Area

Settings - General

**Comment by iambriccardo** [comment]
Hi, thanks for reaching out. For technical reasons, we support wildcards only as prefixes. In this case, something like `https://*-something.vercel.app` would work. Unfortunately, we are not planning to add regex support to this field, as it is designed to be highly specific.
