### ISSUE TITLE
Fix metrics extraction ordering

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/relay#2786]
For the on-demand initiative, a problem was found, in which some specs that were extracting `event.request.url` had no data but that data was available in transactions.

@jan-auer assumed this might have to do with the order in which metrics extraction is performed in the Relay processing pipeline, since it might be that the request URL that is stored in sentry is different from the one received at the edge in Relay, due to processing that is likely to happen in Relay but could also be in Sentry.

This ticket aims at starting research to figure out what the problem could be.

**Comment by iker-barriocanal** [comment]
Apparently, Relay is performing this normalization in "store normalization" instead of "light normalization". I'll get to this ~by the end of this week or early next week~ at the end of next week, it shouldn't be hard to fix.
