### ISSUE TITLE
Exclude endpoints that match the healthcheck inbound filter from transaction sanitization

### ISSUE THREAD

**Issue by Fwang36** [getsentry/relay#2806]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

A user reported that their default healthcheck inbound filter suddenly stopped working.  After taking a look at the org it looks like the endpoint that is supposed to be filtered `/ping` started getting lumped into their `http://*/*` transactions on ingest causing the inbound filter to fail.  The times when the inbound filter stopped working line up with when the `/ping` transactions started appearing in their `http://*/*` transactions url tag.

Maybe we should exclude these [healthcheck GlobPatterns](https://github.com/getsentry/relay/blob/c134e789d1bc803fb967c22faa6ca249198d543e/relay-filter/src/transaction_name.rs#L43) from the transaction sanitization on ingest.

Link to Org and Zendesk ticket in [synced Jira ticket here
](https://getsentry.atlassian.net/browse/FEEDBACK-2016)
### Expected Result

healthcheck transactions should stay filtered

### Actual Result

healthcheck transactions stopped getting filtered

### Product Area

Relay

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2016) by [Unito](https://www.unito.io)

**Comment by Dav1dde** [comment]
I have a suspicion this happened in 2f0602e361eff9b17b4ad2c67df121cbc5744533 and now suddenly light normalization is applying the transaction sanitazation rules when it shouldn't.

**Comment by Dav1dde** [comment]
Possibly related: https://github.com/getsentry/sentry/issues/60739

**Comment by iker-barriocanal** [comment]
Update: we've identified the root cause and I'll be working on a fix for it. Thanks for reporting!
