### ISSUE TITLE
Investigation rules seem to  stop functioning after a few minutes

### ISSUE THREAD

**Issue by RaduW** [getsentry/relay#2814]
# What is happening
I create an investigation rule (a.k.a. a reservoir rule) for a transaction in the Javascript project.
I specify my email name as a condition in order to control the amount of messages generated
I  go to the sentry application and navigate through the application generating the transaction I want to track.
I can see that transactions are accumulated.

After about 10 minutes I try the same thing and transactions are no longer accumulated.

Doing a query for the condition for which I created the rule returns only a few transactions ( about 6) so
the reservoir should not have been filled.

Looking in the sentry admin ( /_admin) at the project configs for the Javascript project I can see the 
reservoir rule being active, but somehow Relay doesn't seem to collect data anymore.

**Comment by matejminar** [comment]
![CleanShot 2023-12-04 at 17 29 16](https://github.com/getsentry/relay/assets/9060071/132318f1-15bf-434e-b4e7-724c5b6d4adc)

**Comment by armenzg** [comment]
If you look at [this query](https://sentry.sentry.io/discover/homepage/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&id=25491&name=&project=1&project=11276&query=transaction%3A%2Fdashboard%2F%3AdashboardId%2F+user.email%3Aarmenzg%40sentry.io+event.type%3Atransaction&sort=-timestamp&statsPeriod=3d&topEvents=5&yAxis=count%28%29), you will see that only 1 sample was captured in the last 3 days:
<img width="952" alt="image" src="https://github.com/getsentry/relay/assets/44410/9df235dd-76da-4b26-926b-be6d2d349f42">

**Comment by TBS1996** [comment]
> What I’m thinking it might happen is that relay sees this rule… it matches it (so it stops matching any other rule) but then it sees that it already reached 100 so it is not sampled anymore, so the more specific rule for the dashboard ( i.e. rule with id 3003) doesn’t get to run.
> Could we check that this doesn’t happen, i.e. if the reservoir is full for a matching rule then the rule is simply ignored and relay tries to match the next rule ( this should be the case but it wouldn’t hurt to double check).
> 

if the reservoir rule matches and then sees its past its limit, it'll simply skip the reservoir rules, so the more specific rules should still be applied. 

you can see it here:
https://github.com/getsentry/relay/blob/104390dbc7861239f4a5c9e7ad1926b4cf8f3ea8/relay-sampling/src/evaluation.rs#L235-L237
evaluate returning `false` means its past the limit, and its returning `None` just like `SamplingValue::Factor` which means it'll continue matching

**Comment by TBS1996** [comment]
Some different theories: 


1. the time range is messed up 
    - Inspecting the project config of sentry and this doesn't seem to be right 
2. The rule expires in redis prematurely
     - This would have the opposite effect since we use an upsert when incrementing, the count would start again from 0.
3. We count the transaction but it gets dropped later in the pipeline
    - This seems somewhat plausible, im looking into this now
4. After reaching the limit, the reservoir rule overrides the other sampling rules and we end up sampling less because of that
    - as I wrote in the comment above, this is not how the code is written, so this shouldn't happen

**Comment by jan-auer** [comment]
One more problem from the above, which is likely the cause why this rule doesn't match at all: `event.tags.event.type` **does not exist**. This is from an `event.type:transaction` filter, which must be removed by the product before generating a rule. Please look at the metric extraction mapping code in Sentry and use the same functions to create the spec. 

I'm going to put this ticket on hold until this is fixed.

**Comment by matejminar** [comment]
@jan-auer @TBS1996 the product is not generating `event.tags.event.type` anymore 👍
