### ISSUE TITLE
Correctly Parse SQL query when `db.system` is provided

### ISSUE THREAD

**Issue by Fwang36** [getsentry/relay#2847]
### Environment

SaaS (https://sentry.io/)

This is an issue created following an internal slack discussion.

A user has correctly added the span data value of `db.system` of `mysql`.  Sentry is failing to parse some queries even though the `db.system` is being provided.  This has led the user's queries to be blocked by Sentry due to high cardinality.

User's Project Id and Org will be in the synced Jira Ticket.

 [Jira](https://getsentry.atlassian.net/browse/FEEDBACK-2036)

**Comment by jjbayer** [comment]
This will be at least partially fixed by https://github.com/sqlparser-rs/sqlparser-rs/pull/1065.

**Comment by jjbayer** [comment]
Looks like this was largely fixed by https://github.com/getsentry/relay/pull/2846.
