### ISSUE TITLE
Inbound Filter Outcome Reason 

### ISSUE THREAD

**Issue by smeubank** [getsentry/relay#2850]
**Description**
We want to be able to categorize why errors dropped by a serverside inound filter are dropped. In this specific case we are trying to analyze the full impact of filtering out hydration errors, but it maybe usefuly to do this in a more scalable way

<img width="781" alt="image" src="https://github.com/getsentry/relay/assets/47563310/2e2a83fc-da75-4fd1-aa75-820a515a2057">

[link](https://sentryio.cloud.looker.com/explore/super_big_facts/outcomes_v3?qid=G287w19xEvHJKFC4g4n312&toggle=fil)

If the filter is based on hyrdation error. Is this included in the "error message" reason? If yes could that be added to the outcome reason? error "message: hydration"

the in product toggle found in project inbound filter settings

<img width="578" alt="image" src="https://github.com/getsentry/relay/assets/47563310/49d2708f-58ea-498a-9da4-6b0bca1b2a1a">

**Comment by jjbayer** [comment]
Will be fixed by https://github.com/getsentry/sentry/issues/57799.

**Comment by bruno-garcia** [comment]
This will really help when debugging customer who reach out about data not being in. "My replay is sampled but the error was dropped" and we dunno what filter was applied

**Comment by mydea** [comment]
Referencing https://github.com/getsentry/sentry-javascript/issues/10036, as that may be related to this!

**Comment by smeubank** [comment]
@billyvg also stumbled across this, related to customers calling in and not having enough insight

**Comment by jjbayer** [comment]
Should be straight-forward to port hydration errors to generic filters now, which would give them a separate outcome reason. We just need to extend the `Getter` on `Event` to [access](https://github.com/getsentry/relay/blob/84224e9eef04b576306ca401a5d9b4fa04ed571f/relay-filter/src/error_messages.rs#L188-L195) `exception.values.value`. @iker-barriocanal maybe something for you?

**Comment by iker-barriocanal** [comment]
@smeubank do you have a list of filters we could target? I see special cases for hydration errors and chunk load errors. Getting reasons for these two specifically is quite straightforward.

**Comment by smeubank** [comment]
for a list for filters, we should be able to manage at least what is here and toggleable
- browser extensions
- health check (transations)
- legacy browsers
- localhost
- web crawlers
- hydration errors
- chunkLoadError(s)

![image](https://github.com/getsentry/relay/assets/47563310/f485fb6c-9a56-4ab4-84c4-a68ea6f0b287)

**Comment by iker-barriocanal** [comment]
After discussing on Slack, the only missing filters without a reason in the above list are the hydration and chunk load errors.

**Comment by iambriccardo** [comment]
We are now working on the foundational elements needed to allow the expression of error message rules generically. This is the PR for reference: https://github.com/getsentry/relay/pull/3791.

The next steps are:
1. Implementing the new looping semantics
2. Implementing the rule generation in Sentry

**Comment by iambriccardo** [comment]
Will use this query to validate the new outcomes:
```sql
MATCH (outcomes)
SELECT reason, count(reason) BY reason
WHERE project_id = 11276 AND org_id = 1
AND outcome = 1
AND timestamp >= toDateTime('2024-07-01T10:30:30')
AND timestamp < toDateTime('2024-07-30T10:30:30')
```

**Comment by iambriccardo** [comment]
Here is an updated screenshot on the latest data:
![Image](https://github.com/user-attachments/assets/762718b4-73db-47cc-9d27-98df72e6e792)
