### ISSUE TITLE
Memory watermark in health check

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#2880]
To prevent OOMs, reply with 429s and set health check to unhealthy when system memory goes over a configured limit.

Open questions:
* If memory is full because of project configs, we should _not_ stop accepting requests, but stop fetching project configs instead. But that is the less common scenario so we could ignore it in a first step.
* Instead of becoming unhealthy, should we go into spooling state?

**Comment by Dav1dde** [comment]
Spooling changes are tracked here: https://github.com/getsentry/team-ingest/issues/131

Health check watermark is implemented.
