### ISSUE TITLE
Span grouping for complex db queries

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#2925]
Some projects generate many different SQL queries that are distinct even after parameter scrubbing (e.g. programmatically generated queries), which leads to an explosion in tag cardinality.

We need to find a way to deal with such queries. Some options (there might be more):

1. Rely on a [per-tag cardinality limiter](https://github.com/getsentry/team-ingest/issues/250). More relevant queries have a higher quality of being accepted because of their frequency.
2. Build a top-K per-tag cardinality limiter to increase the probability that relevant queries are recorded.
3. Group more coarsely by erasing deep levels of nesting / joins from the query.
4. Group more coarsely by [keeping only the first 200 characters of a query](https://github.com/getsentry/relay/pull/2749).
5. ...

**Comment by Dav1dde** [comment]
No.
