### ISSUE TITLE
relay config init [OPTIONS]

### ISSUE THREAD

**Issue by lynomet** [getsentry/relay#2970]
What are the [OPTIONS] ?
i can't find them with the --help
i need to automate this(runs inside pod) and it runs interactive:
Initializing relay in /work/.relay
? Do you want to create a new config? ›
❯ Yes, create default config
  Yes, create custom config
  No, abort

**Comment by Dav1dde** [comment]
The config options are documented in our docs: https://docs.sentry.io/product/relay/options/ - the rest of the docs may be interesting to you as well. Especially the [getting started](https://docs.sentry.io/product/relay/getting-started/) page which goes into more detail how to run Relay.
