### ISSUE TITLE
`contexts.trace.data.route` getting rejected by Sentry

### ISSUE THREAD

**Issue by SystematicCZ** [getsentry/relay#3000]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.13.1

### Steps to reproduce

1. Trigger an event that sends a trace to Sentry.
2. Observe the trace details in the Sentry issue interface.
3. The `contexts.trace.data.route` field does not contain the actual route name.

### Expected result

contexts.trace.data.route should contain route name

### Actual result

![obrazek](https://github.com/getsentry/sentry-symfony/assets/53008590/24a8f5c6-30ea-4829-8095-edecd2797649)

```
{
http.flavor: 1.1,
 http.request.method: GET, 
 http.url: ...,
net.host.name: ..., 
net.host.port: 443, 
net.peer.ip: ..., 
route: None
}
```

**Comment by cleptric** [comment]
Are you setting these values manually?

**Comment by SystematicCZ** [comment]
No, we only use the `captureException()` function and we use Sentry relay. We do not alter the payload that is sent. My understanding is that these values are set by event listener from this bundle.

**Comment by cleptric** [comment]
Thanks, I'll take a look.

**Comment by markitosgv** [comment]
Same issue here, it seems something has changed

**Comment by cleptric** [comment]
I do confirm this issue, and it looks like something regarding ingestion has changed. Talking to the team to fix it. The good news is that the `route` tag is still applied correctly to all events, and tags are actually queryable/searchable while the context is not. So, while the error in the UI is annoying, it does not break anything.

**Comment by Dav1dde** [comment]
In Relay we want to fully type out the `Route`, which includes adding a `path` field.

When the SDKs send a string Relay should normalize the string to the new `path` field.

**Comment by ruudvanderweijde** [comment]
I'm experiencing the same issue. The route was working before, but for a couple of weeks, we get the same error as described.

**Comment by Dav1dde** [comment]
@ruudvanderweijde sorry for the inconvenience, it's a high priority issue for us, top of the list.

**Comment by cleptric** [comment]
This also causes the HTTP method not to be populated on the transactions list.

**Comment by olksdr** [comment]
@cleptric could you point me to the schema which is used to set the `data` in the `trace` context ? At least the one used in PHP

**Comment by cleptric** [comment]
Just an issue in Symfony, see https://github.com/getsentry/sentry-symfony/blob/master/src/EventListener/TracingRequestListener.php#L89-L110.
It says tags, but it's put into span data and could also end up on the trace context.

**Comment by olksdr** [comment]
Trance context was typed out in 
https://github.com/getsentry/relay/blob/1a780e2831c1e6e8b3cfda97e7345c3e3279c367/relay-event-schema/src/protocol/contexts/trace.rs#L133-L153 and has only `route` and `previous_route` defined, but the rest should stay same. 

> This also causes the HTTP method not to be populated on the transactions list.
This seems unrelated to the bug reported in this issues.

**Comment by olksdr** [comment]
This change should be rolled out to SaaS by now. Please give it a go, if there is still an error.

**Comment by gndk** [comment]
Just one datapoint from a sentry-symfony + sentry.io user: the errors disappeared 🙂
