### ISSUE TITLE
Replace `MetricMeta` feature flag with `CustomMetrics`

### ISSUE THREAD

**Issue by Dav1dde** [getsentry/relay#3024]
We want to merge the metric meta feature flag with the custom metrics one.

CoS:
* remove `MetricMeta` feature flag from Relay
* use `CustomMetrics` feature flag for metric metadata (`project.rs`)
* remove feature flag from Sentry whitelist for project configs

**Comment by jjbayer** [comment]
Don't forget about external Relays compatibility.
