### ISSUE TITLE
[Flaky CI]: test_global_rate_limit

### ISSUE THREAD

**Issue by Dav1dde** [getsentry/relay#3030]
### Flakiness Type

Assertion failure

### Name of Test

tests/integration/test_outcome.py::test_global_rate_limit

### Link to Test Run

https://github.com/getsentry/relay/actions/runs/7722991438/job/21052183827

**Comment by jjbayer** [comment]
Another one: https://github.com/getsentry/relay/actions/runs/7928029973/job/21645478342

**Comment by olksdr** [comment]
Another one: https://github.com/getsentry/relay/actions/runs/7930570068/job/21653115711
