### ISSUE TITLE
ERROR: project state for key <id> is missing key id.

### ISSUE THREAD

**Issue by ladovina** [getsentry/relay#3033]
We run Relay(getsentry/relay:21.5.1) as a part of Sentry(getsentry/sentry:21.5.1) in the docker swarm. Our Sentry stopped tracking issues, the only error I can see is this, in Relay:

```
...
2024-01-31T15:20:17Z [relay_server::actors::envelopes] ERROR: project state for key d57a044f6aa0493e9bc64a4d93df4123 is missing key id
...
```

The key ('d57a044f6aa0493e9bc64a4d93df4123') changes to different values... Is there some setting I can delete/edit to resolve the issue? 

An update to the latest Sentry/Relay (24.1.1) did not help...

I was able to track it down in the source code, method `store_process_event` but I can't figure it out.

Any suggestions?

**Comment by jjbayer** [comment]
Hey @ladovina, could it be that you're running Relay in proxy mode? See https://github.com/getsentry/relay/issues/2390.

**Comment by ladovina** [comment]
Hi @jjbayer, thank you very much for your reply.

I can confirm when I changed it to "managed" mode and added allowed public keys (https://forum.sentry.io/t/relay-fails-to-get-projects-configs/14391) the error disappeared.

However I noticed the main problem why we have no issues received in Sentry was some network issue... When I scheduled all sentry containers on just one node Sentry events started working - even with the Relay in "proxy" mode, which still contains the mentioned error message "project state for key <id> is missing key id", but it works...

**Comment by jjbayer** [comment]
> even with the Relay in "proxy" mode, which still contains the mentioned error message "project state for key is missing key id", but it works...

@ladovina Thanks, tracking this in https://github.com/getsentry/relay/issues/3048.
