### ISSUE TITLE
[Flaky CI]: test_processing_quotas[nel-86400-172800] 

### ISSUE THREAD

**Issue by Dav1dde** [getsentry/relay#3037]
### Flakiness Type

Timeout

### Name of Test

tests/integration/test_store.py::test_processing_quotas[nel-86400-172800] 

### Link to Test Run

https://github.com/getsentry/relay/actions/runs/7733940648/job/21086995952

**Comment by Dav1dde** [comment]
Happened again: https://github.com/getsentry/relay/actions/runs/8342314399/job/22830195487

**Comment by jjbayer** [comment]
One more: https://github.com/getsentry/relay/actions/runs/8983663323/job/24673902427#step:9:1471
