### ISSUE TITLE
Proxy Relay drops Metrics because of missing feature flags

### ISSUE THREAD

**Issue by Dav1dde** [getsentry/relay#3042]
A Relay configured in Proxy mode does not forward metrics due to a missing metrics feature flag.

Since proxy Relays do not load project configs all metrics will be dropped. A proxy Relay should forward statsd metrics in an envelope.

**Comment by jjbayer** [comment]
Decision to be made: Should proxies / static relays aggregate metrics?

**Comment by olksdr** [comment]
Let's keep aggregation and keep the features flag `ON` by default.
