### ISSUE TITLE
Align MRI validation between Sentry and Relay

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/relay#3108]
Sentry has its regex to validate MRIs and right now there is a divergence in how Relay validates. The regex definition code in Sentry is here: https://github.com/getsentry/sentry/tree/master/src/sentry/snuba/metrics/naming_layer/mri.py#L71-L71.

This ticket involves the work of aligning the validations in Relay to Sentry. In addition, docs must be updated here: https://develop.sentry.dev/sdk/metrics/#normalization.

**Comment by Dav1dde** [comment]
The `unit` is different, in Relay it accepts anything ASCII, Sentry expects `[\w.]+`. We probably want to limit it to ASCII Alphabetic or Alphanumeric (TODO: figure this out).

Double check the other parts as well.

**Comment by Dav1dde** [comment]
Maybe expose validation of MRIs in `librelay`
