### ISSUE TITLE
Allow ingestion of internal metrics

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#3114]
For features that need to emit metrics from the sentry code base, such as [Aggregated Functions](https://www.notion.so/sentry/Moving-Profile-Metric-to-Generic-Metrics-Platform-194ead02a6a84b0b81939c7ef88e9fef) and [Escalating Issues](https://github.com/getsentry/sentry/blob/e7fae9c02e49f18f9ab40dedb8bd36701bfdea22/src/sentry/tasks/post_process.py#L146), we need the possibility to send metrics without associating them to a specific user DSN.

Initial idea for solution (see Option 2 in comment below): Allow ingestion by numeric project ID. Problem:

A `Project` in Relay corresponds to a DSN, not to a numeric project ID. So we need a way to either

1. Associate the project with a random DSN from that project somehow,
2. Enable Relay to fetch project config for a numeric project ID as well as a public key.

Possible solutions:

- Make the `projectconfig` endpoint in Sentry & Relay accept numeric IDs. Return the project config without DSN-specific parts (i.e. DSN rate limits).
- Revisit the idea of "layered configs" that we discarded for global configs: Make Relay request config on multiple levels (global, org, project, DSN), and pass around a struct with a reference to each layer in the Relay code base.

**Comment by jjbayer** [comment]
cc @viglia

**Comment by Dav1dde** [comment]
We should:

* investigate if we couldn't accept envelopes in general without DSN and guard the submission with an extra layer of authentication.
* see if we can't come up with a better specified endpoint/format, e.g. I don't think they need support for cross org submissions and they can't submit the key component of the endpoint the ProjectKey

**Comment by jjbayer** [comment]
Will discuss possible solution today, then decide who can implement and when.

**Comment by jjbayer** [comment]
We took a step back and thought about how to solve the general problem of submitting per-project metrics from sentry:

# Option 1 (preferred)

- Sentry / Vroom sends envelopes with public key
    - create an internal DSN for project
        - hide from UI
        - sentry util `get_or_create_internal_dsn(project_id=123, use_case="profiles")`
            - add a column to `sentry_projectconfig` with the use case (Customer, Profiling, EscalatingIssues)
               see                 [Database Migrations](https://develop.sentry.dev/database-migrations/#adding-columns-with-a-default)
            - only show internal DSNs to superuser
                
## Pros:

- Everything works in Relay
- We can still define rate limits, etc. per DSN
- We can disable internal DSNs

## Cons:

- Vroom needs to receive one extra field

# Option 1a

- Generate DSN deterministically from numeric ID
- Sign the request to prevent abuse or `dsn := fn(numeric_id, secret)`

**Pros**

- Vroom can compute the DSN from the project ID

**Cons**

- Still need to store DSN in DB
- Needs a secret

# Option 2

- Send data with numeric ID (authenticated endpoint)
- Means Relay needs to fetch project config by numeric ID as well
- Would endpoint accept anything, or only metrics?

**Pros**

- Vroom can use numeric ID

**Cons**

- Needs major Relay + sentry work
    - sentry needs to serve project-level config
    - relay needs new endpoint with authentication + mechanism to fetch project-level config
- Data cannot be attributed to the use case(”profiling”)

# Option 3 (rejected)

Vroom sends metrics into `ingest-metrics` topic directly.

**Pros**

- Unblock immediately

**Cons**

- Bypass everything (rate limiting, aggregation, …)

**Comment by jjbayer** [comment]
Based on the pros & cons listed above, we propose to implement Option 1:

# Proposal

1. Add a column to `sentry_projectkey` that identifies the DSN's use case. The default use case is `"user"`. Every existing DSN gets this default.
2. Hide non-user DSNs from all public APIs, i.e. DSN GUI, etc.
3. When emitting metrics for Aggregate Functions or Escalating Issues, call `ProjectKey.get_or_create` with the current project ID and the appropriate use case string.
4. Add this project key to the message Vroom receives from Sentry.
5. In Vroom, emit an envelope in the existing format associated to the new project key.

**Comment by jjbayer** [comment]
@viglia the PR is merged, you should now be able to create internal DSNs from code like this:

```python
from sentry.models import ProjectKey, UseCase
# label is optional
ProjectKey.objects.get_or_create(project_id=my_project_id, use_case=UseCase.PROFILING.value, label='Aggregate Functions')
```

**Comment by viglia** [comment]
> @viglia the PR is merged, you should now be able to create internal DSNs from code like this:
> 
> ```python
> from sentry.models import ProjectKey, UseCase
> # label is optional
> ProjectKey.objects.get_or_create(project_id=my_project_id, use_case=UseCase.PROFILING.value, label='Aggregate Functions')
> ```

Awesome!! Thank you @jjbayer !!
