### ISSUE TITLE
Support csp-violation reports

### ISSUE THREAD

**Issue by iker-barriocanal** [getsentry/relay#3119]
Apparently, CSP reports of type `csp-violation` are not supported in Relay. This is a valid type according to the [reporting spec](https://www.w3.org/TR/CSP3/#reporting):

> csp violation reports have the report type "csp-violation".

See [POP-RELAY-30F](https://sentry.my.sentry.io/organizations/sentry/issues/625266/).

**Comment by Dav1dde** [comment]
Duplicate? https://github.com/getsentry/relay/issues/2645 and https://github.com/getsentry/sentry/issues/52794

**Comment by iker-barriocanal** [comment]
Right 😄
