### ISSUE TITLE
Investigate proper roles of relay modes

### ISSUE THREAD

**Issue by TBS1996** [getsentry/relay#3127]
We had following questions on proxy mode:

> We had some internal discussion about whether proxy relay is even needed. 
> 
> Apparently php needs it, we should investigate the current use cases and see if there's a better alternative for them. Getting rid of a relay mode would be a win for simplicity.   

We should have a broader discussion on our relay modes, what the role of each is and whether we want to investigate having separate binaries

**Comment by Dav1dde** [comment]
See also: #3021

**Comment by TBS1996** [comment]
https://github.com/getsentry/relay/pull/3146#discussion_r1495762531

**Comment by iker-barriocanal** [comment]
Supporting external Relays requires a big investment from the Ingest team to design and implement new features and bug fixes without introducing breaking changes. Sometimes, these discussions and the workarounds take longer than implementing the actual features.

We should find a way not to impact development velocity by removing these conversations, while still supporting old Relays running.
