### ISSUE TITLE
[Flaky CI]: test_outcome.py::test_global_rate_limit_by_namespace

### ISSUE THREAD

**Issue by olksdr** [getsentry/relay#3169]
### Flakiness Type

Assertion failure

### Name of Test

tests/integration/test_outcome.py::test_global_rate_limit_by_namespace

### Link to Test Run

https://github.com/getsentry/relay/actions/runs/8065335723/job/22030936697?pr=3168

### Details

Got the following assertion failure:

```
=================================== FAILURES ===================================
_____________________ test_global_rate_limit_by_namespace ______________________
[gw0] linux -- Python 3.10.13 /home/runner/work/relay/relay/.venv/bin/python3
Traceback (most recent call last):
  File "/home/runner/work/relay/relay/tests/integration/test_outcome.py", line 2042, in test_global_rate_limit_by_namespace
    assert len(outcomes) == 1
AssertionError: assert 0 == 1
 +  where 0 = len([])
```

**Comment by jjbayer** [comment]
Another one: https://github.com/getsentry/relay/actions/runs/8093934644/job/22117581073?pr=3186#step:9:1162

**Comment by iker-barriocanal** [comment]
I've only managed to replicate the test failure once, so moving it back to the backlog.
