### ISSUE TITLE
[Flaky CI]: Failed to assert elapsed time is 10 seconds.

### ISSUE THREAD

**Issue by cmanallen** [getsentry/relay#3171]
### Flakiness Type

Assertion failure

### Name of Test

extractors::start_time::tests::start_time_from_timestamp

### Link to Test Run

https://github.com/getsentry/relay/actions/runs/8050926586/job/21987677539

### Details

Seems like an issue between the generation of the `now` timestamp and the `system_time` timestamp.  We're likely crossing from second `n` to second `n+1` between calls.

```
---- extractors::start_time::tests::start_time_from_timestamp stdout ----
thread 'extractors::start_time::tests::start_time_from_timestamp' panicked at relay-server\src\extractors\start_time.rs:74:9:
assertion `left == right` failed
  left: 9
 right: 10


failures:
    extractors::start_time::tests::start_time_from_timestamp

test result: FAILED. 225 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 4.77s

error: test failed, to rerun pass `-p relay-server --lib`
```

**Comment by jjbayer** [comment]
Another occurrence: https://github.com/getsentry/relay/actions/runs/8153936126/job/22286298121?pr=3213#step:5:1852
