### ISSUE TITLE
Unable to send replay events in proxy mode

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/relay#3175]
When sending events from the JS SDK via Relay on proxy mode all replays events are dropped with the message: 
```
DEBUG request: tower_http::trace::on_response: finished processing request latency=0 ms status=200 method=POST uri=/api/5278835/envelope/?sentry_key={key}&sentry_version=7&sentry_client=sentry.javascript.react%2F7.102.0 version=HTTP/1.1
DEBUG relay_server::utils::managed_envelope: dropped envelope: rate limited
```

This happens on the first replay event sent by the SDK, error events are sent normally and I can see them in the project settings. 

Steps to reproduce:
1. Configure relay on proxy mode with default settings:
```
relay:
  mode: static
  upstream: https://o<ID>.ingest.sentry.io
  host: 0.0.0.0
  port: 3000

logging:
  level: debug
  log_failed_payloads: true
```
2. Add project configuration, again with default settings
```
{
    "slug": "react",
    "publicKeys": [
      {
        "publicKey": "379539....",
        "isEnabled": true
      }
    ],
    "config": {
      "allowedDomains": ["*"]
    }
  }
```
3. Run relay and configure the SDK to send events to it.

Expected result:
All events categories are accepted

Actua result:
Error events and transactions are accepted, replays events are marked as rate limited.

I also tested on managed mode, the result is the same. The only difference is that it does not show the `dropped envelope: rate limited` debug message for replays.  

Edit: using latest docker image

**Comment by jjbayer** [comment]
@rodolfoBee what should work is enabling the feature in the project config:
```json
 "config": {
      "allowedDomains": ["*"],
      "features": ["organizations:session-replay"]
    }
```

I will put this ticket on our backlog to make sure we "graduate" this feature and enable it by default in the future.

**Comment by rodolfoBee** [comment]
@jjbayer a few observations:
1. this option needs to be documented. 
2. ~It did not work, I got the same error when running in proxy mode. I did try to prune docker cache before running again, the result was the same~ 
  - I found the issue in the project file configuration, relay was not loading it. The flag solved the issue. 
3. How does it affects managed mode? My understanding is that the project configuration files are for static and proxy mode only as managed mode grab the configurations from the server.

**Comment by jjbayer** [comment]
> this option needs to be documented.

Rather than documenting it, I would like to [graduate](https://develop.sentry.dev/feature-flags/#after-launch-graduation) it such that replays are always enabled. @getsentry/replay can we do that, or are there still customer plans that are not allowed to ingest replays?

> How does it affects managed mode? My understanding is that the project configuration files are for static and proxy mode only as managed mode grab the configurations from the server.

Yes, managed mode gets its feature flags from the server, so if it's connected to SaaS, replays should work out of the box.

**Comment by jjbayer** [comment]
> Rather than documenting it, I would like to [graduate](https://develop.sentry.dev/feature-flags/#after-launch-graduation) it such that replays are always enabled. @getsentry/replay can we do that, or are there still customer plans that are not allowed to ingest replays?

@cmanallen do you know if we can remove feature flags for replays? Or should they not be enabled for self-hosted / specific customer groups?

**Comment by cmanallen** [comment]
@jjbayer Not every customer group has it enabled yet.  So it has to remain for now.

**Comment by jjbayer** [comment]
Thanks, that means we will have to keep the feature flag for now. @rodolfoBee I added documentation here: https://github.com/getsentry/sentry-docs/pull/9371
