### ISSUE TITLE
Simplify Relay modes

### ISSUE THREAD

**Issue by iker-barriocanal** [getsentry/relay#3190]
## Current state

Relay has 3 modes (see [docs](https://docs.sentry.io/product/relay/modes/)):
- Managed mode.
- Static mode.
- Proxy mode.

Additionally, for each mode Relay can be configured to do processing.

## Problem

Sentry only has controls Relays running in SaaS, but still supports external Relays for SaaS and Self-Hosted instances. This requires a big investment from the Ingest team to design and implement new features and bug fixes without introducing breaking changes. Sometimes, these discussions and the workarounds take longer than implementing the actual features.

The solution should find a way not to impact development velocity by removing these conversations, while still supporting old Relays running.

Related: what `sentry` versions should Relay be compatible with?

**Comment by olksdr** [comment]
We have following issues already open and related to this one:
* https://github.com/getsentry/team-ingest/issues/262
* https://github.com/getsentry/relay/issues/3127

**Comment by iker-barriocanal** [comment]
Expanded with https://github.com/getsentry/relay/issues/3127#issuecomment-1973099698 so closing this issue, thanks!
