### ISSUE TITLE
Pass on multipart attachments without a content-type

### ISSUE THREAD

**Issue by supervacuus** [getsentry/relay#3224]
This relates to https://github.com/getsentry/sentry-native/issues/955.

A summary of the above issue is:
* attachments sent via the `crashpad_handler` (which sends them as part of a multipart request) cannot be previewed in the web-ui because they all have content-type `application/octet-stream` by default.
* attachments sent as envelope items typically do not get a content-type header, in which case they will be MIME detected in the backend and only assigned `application/octet-stream` [if no MIME type could be identified](https://github.com/getsentry/sentry/blob/42050bfa4f3fcc6b19c9f104eba868dcc8535eaa/src/sentry/models/eventattachment.py#L184-L187).
* users would like to see the same behavior for attachments sent via the crashpad backend.

To achieve this in the Native SDK, we'd remove the content-type header from the multipart attachments sent via the `crashpad_handler`. This would reflect how we send attachment envelop items, which we also send without content type (this seems to be the default for other SDKs).

But to make this change in the Native SDK meaningful, we'd need Relay to pass on multipart attachments without content type if the SDK sent them this way (similar to how envelope attachments' content types are untouched). Right now, Relay assigns `application/octet-stream` to incoming multipart attachments without a content type.

Are there currently any components that rely on the automatic content type assignment in Relay, rather than deferring to the MIME detector in the Python code?

**Comment by olksdr** [comment]
Hey @supervacuus 

thanks for opening an issue and a PR. We will discuss this with the team and post the update here or on your PR.

**Comment by supervacuus** [comment]
Since the associated PR has been merged and deployed and preliminary tests show that multipart attachments are correctly detected and thus can be previewed in the web UI, we can close this. Thanks for the support!
