### ISSUE TITLE
Rebuild spool as a swap space

### ISSUE THREAD

**Issue by Dav1dde** [getsentry/relay#3288]
We should start treating the spool as a swap, at a certain point of managed envelopes we should start buffering to disk and treat the disk as a swap space.

We've seen in the past that the current spooling behaviour is not enough, especially in lower memory setups. It also causes confusion, people expect the spool to work like a swap but then it doesn't.

Related to: https://github.com/getsentry/team-ingest/issues/131

**Comment by jjbayer** [comment]
> We should start treating the spool as a swap, at a certain point of managed envelopes we should start buffering to disk and treat the disk as a swap space.

This is now roughly how the spooler works, we keep a stack per project that only keeps 10 kib of compressed envelopes in memory and offloads everything else to SQLite.
