### ISSUE TITLE
Adblockers and Relay

### ISSUE THREAD

**Issue by sandstrom** [getsentry/relay#3314]
## Problem

We have a lot of customers using Adblockers, and when they block relay requests, we cannot easily debug errors and provide a good service to our customers. When the customers call to complain, we tell them that they need to disable the adblocker for us to help them. But many don't understand how they work or why Sentry was blocked to begin with (Sentry isn't ads).

In short, it makes debugging JS errors hard.

## Background

This is the line that's blocking Sentry (in one list, at least):

https://github.com/easylist/easylist/blob/2fdf00ce/easyprivacy/easyprivacy_general.txt#L347

I did some quick research, and it seems like blocking based on an HTTP body is still rare.

https://github.com/uBlockOrigin/uBlock-issues/issues/1357

## Solution

Allow Managed Relay to accept the key in either the body (a key in the JSON payload), or as a query param, and in both cases with an arbitrary name (one we can choose ourselves).

Relay can then forward it to Sentry in a standardised format (same as today, i.e. relay would move the key to a standard location/name). That should allow JS error reports to be received, when using Sentry with Relay.

Next level of obfuscation could be to base64 encode the HTTP body, and have relay also decode it, before forwarding.

**Comment by Dav1dde** [comment]
Is this a longterm solution? Seems like a never ending arms race of changing query params and ad lists updating.

**Comment by sandstrom** [comment]
@Dav1dde I agree that broadly, it's to some extent an arms-race.

However, I think if there is something easy that could be done, then maybe it's worth it anyway.

Another suggestion would be to make sentry accept both `sentry_key` (current) and `key` (or `skey`, but `key` is better) as a param name.

Blocking all URLs with a query param called `key` will be untenable.

***

As an aside, I also wonder why they do this (block sentry), since it's just making it harder for developers to debug issues and provide good service that works. It's very difficult to debug errors if you don't know about them.

**Comment by Dav1dde** [comment]
> As an aside, I also wonder why they do this (block sentry), since it's just making it harder for developers to debug issues and provide good service that works. It's very difficult to debug errors if you don't know about them.

I agree, it's very unfortunate that they block Sentry. Especially since we do take a big effort to *not* track any user identifying information.

There have been multiple discussions in the past with maintainers of these lists and some did actually remove the block again, but seems like easy list wants to also block error reporting tools, unfortunately.

> Another suggestion would be to make sentry accept both sentry_key (current) and key (or skey, but key is better) as a param name.

We'll discuss it in the Team.

Personally I am not a fan of this, I don't want to start a fight with the list maintainers and they will just coming up with a new rule that blocks Sentry again if that's their intention.

If you're looking for a workaround for self hosted (or SaaS), you should be able to rewrite the params with a reverse proxy like Nginx before forwarding it to Relay.

**Comment by sandstrom** [comment]
I understand that you don't want to fight them, that's a reasonable approach!

That said, renaming the key to something more generic would be easy and might do the trick. Great that you'll discuss it!

> If you're looking for a workaround for self hosted (or SaaS), you should be able to rewrite the params with a reverse proxy like Nginx before forwarding it to Relay.

Good idea!

***

More broadly, as much as I hate online ads, I think it's ultimately going to be solved in one of two ways: (1) companies that rely on ads will go bankrupt or (2) they will paywall or detect ad-blockers and block.

The adblockers success will be their own demise, and they will take a lot of companies living on ads with them, which is probably a good thing! 😃

**Comment by jjbayer** [comment]
@sandstrom have you consulted https://docs.sentry.io/platforms/javascript/troubleshooting/#dealing-with-ad-blockers?

> you can use the `tunnel` option to tell the SDK to deliver events to the configured URL, instead of using the DSN. This allows the SDK to remove sentry_key from the query parameters, which is one of the main reasons ad-blockers prevent sending events in the first place.

**Comment by sandstrom** [comment]
Thanks @jjbayer, I'll have a look!

**Comment by olksdr** [comment]
Please, reopen if the proposed solution does not work.
