### ISSUE TITLE
[Flaky CI]: test_rate_limit_metrics_consistent

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#3343]
### Flakiness Type

Timeout

### Name of Test

tests/integration/test_spans.py::test_rate_limit_metrics_consistent

### Link to Test Run

https://github.com/getsentry/relay/actions/runs/8437186538/job/23106404892?pr=3328#step:9:1184

**Comment by Dav1dde** [comment]
A bunch of this code has been recently changed including this test. Let's re-open when it happens again, we then should also have better logs.
