### ISSUE TITLE
[Flaky CI]: test_profile_chunks

### ISSUE THREAD

**Issue by iker-barriocanal** [getsentry/relay#3353]
### Flakiness Type

Assertion failure

### Name of Test

tests/integration/test_profile_chunks.py::test_profile_chunk_outcomes[2]

### Link to Test Run

https://github.com/getsentry/relay/actions/runs/8456600557/job/23166753013#step:9:1428

**Comment by Dav1dde** [comment]
Should be fixed with #3647 - you can see in the log that the message was sent, but Python never received it in time.
