### ISSUE TITLE
[INC-696] Validate Kafka configuration on startup

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#3404]
When Relay is configured to publish to a non-existing topic, it currently starts normally and only starts logging errors when traffic for that topic comes in.

Relay should fail startup when a Kafka topic does not exist.

Note: This issue is a narrower version of https://github.com/getsentry/relay/issues/2766.

**Comment by Dav1dde** [comment]
> Relay should fail startup when a Kafka topic does not exist.

This is possible but breaks with a cluster that relies on topics to be auto created, which is the [default setting](https://kafka.apache.org/documentation/#brokerconfigs_auto.create.topics.enable).

Probably an issue for self hosted and our own tests also rely on this behaviour.

**Comment by lynnagara** [comment]
Self hosted doesn't rely on topic auto-creation (it uses snuba bootstrap + https://github.com/getsentry/self-hosted/blob/67382fd2abc0357e6d39634c4051cae0240da9c2/install/create-kafka-topics.sh for the rest IIRC)

**Comment by Dav1dde** [comment]
Ah okay, I saw the list and though it was a bit short, if the rest is created elsewhere that's good to know.

Our current plan would be to have config flag which toggles a strict mode in which Relay validates topics, question is whether it should be on by default.
