### ISSUE TITLE
Unstable on-demand metric extraction

### ISSUE THREAD

**Issue by obostjancic** [getsentry/relay#3410]
Starting ~27th of March [this alert](https://sentry.sentry.io/alerts/rules/details/182904/?alert=103479&referrer=metric_alert_slack&notification_uuid=f106cc92-5db7-4f74-80e1-170ed208aaa4) counting the number of received on demand metrics started occasionally firing.
Most drops last for a just a couple of minutes with some of them being >10mins. These latter ones are also visible in charts that depend on on demand metrics.

We already eliminated cardinality and rate limits as potential causes and have no indication that project config is unavailable when this occurs. (All project config related metrics we have show no correlation and we also saw generated project configs during one of the drops) 

Extraction of standard metrics does not seem to be affected.

Rough approximation between the counts of regular transaction metrics and on-demand metrics: [link](https://sentry.sentry.io/metrics/?environment=prod&interval=5m&multiChartMode=0&period=14d&project=1&statsPeriod=72h&widgets=%5B%7B%22mri%22%3A%22d%3Atransactions%2Fon_demand%40none%22%2C%22op%22%3A%22count%22%2C%22query%22%3A%22%22%2C%22groupBy%22%3A%5B%5D%2C%22powerUserMode%22%3Afalse%2C%22type%22%3A1%2C%22id%22%3A0%2C%22displayType%22%3A%22area%22%2C%22focusedSeries%22%3A%5B%5D%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%2C%22isHidden%22%3Atrue%7D%2C%7B%22mri%22%3A%22d%3Atransactions%2Fduration%40millisecond%22%2C%22op%22%3A%22count%22%2C%22query%22%3A%22%22%2C%22groupBy%22%3A%5B%5D%2C%22powerUserMode%22%3Afalse%2C%22type%22%3A1%2C%22id%22%3A1%2C%22displayType%22%3A%22area%22%2C%22focusedSeries%22%3A%5B%5D%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%2C%22isHidden%22%3Atrue%7D%2C%7B%22formula%22%3A%22%24b+%2A+15%22%2C%22type%22%3A2%2C%22id%22%3A0%2C%22displayType%22%3A%22line%22%2C%22focusedSeries%22%3A%5B%5D%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%2C%22isHidden%22%3Atrue%7D%2C%7B%22formula%22%3A%22%28+%24b+%2A+15+%29+-+%24a%22%2C%22type%22%3A2%2C%22id%22%3A1%2C%22displayType%22%3A%22line%22%2C%22focusedSeries%22%3A%5B%5D%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%2C%22isHidden%22%3Afalse%7D%5D)
![Image](https://github.com/getsentry/relay/assets/86684834/2d0eab57-c349-4dc7-8c72-3642da1010ad)
Count of on-demand metrics: [link](https://sentry.sentry.io/metrics/?environment=prod&interval=5m&multiChartMode=0&per)
![Image](https://github.com/getsentry/relay/assets/86684834/29ee6e3c-dc79-4278-bcbe-98f23a4e9fea)

**Comment by iker-barriocanal** [comment]
> have no indication that project config is unavailable when this occurs. (All project config related metrics we have show no correlation and we also saw generated project configs during one of the drops)

Could you expand on how this was measured? I wonder if Relay could have stale configs without required entries.

**Comment by Dav1dde** [comment]
I confirmed that `metricExtractions` is missing from the project config for a short period of time, by grabbing a quick snapshot when the error triggered.

@k-fish is investigating.
