### ISSUE TITLE
On sentry side, have organization-wide option for sample rate (`[0.0, 1.0]`). AM3 plans will have a single sampling rule which is trace-based.

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/relay#3446]

**Comment by iambriccardo** [comment]
The entry point in code is here: https://github.com/getsentry/sentry/blob/a9e519265fa4ad7c7abedaf412137d3b3ac17770/src/sentry/dynamic_sampling/rules/base.py#L100-L100

A suggestion would be to make a new combinator that has a single rule and you just iterate over all the combined rules and you generate them.

**Comment by jjbayer** [comment]
Not needed after all, see https://github.com/getsentry/relay/issues/3330.
