### ISSUE TITLE
project_cache: failed to start buffer service - (code: 14) unable to open database file

### ISSUE THREAD

**Issue by williamdes** [getsentry/relay#3475]
Similar to https://github.com/getsentry/relay/issues/2617

```sh
relay-1  | 2024-04-23T13:41:25.633220Z ERROR relay_server::services::project_cache: failed to start buffer service error=failed to setup the database: error returned from database: (code: 14) unable to open database file
```

I am unable to find where it is in the code. If I remove `path: /var/lib/sentry-envelopes/files` it goes away
This is a Docker volume and I even created a folder with 777 permissions in it.

**Comment by iker-barriocanal** [comment]
Hi @williamdes, thanks for reporting! Could you share a minimum repro case to ease the debugging? The log is happening [here](https://github.com/getsentry/relay/blob/160946fb46d4a4967ce56ad0c52392759917fe34/relay-server/src/services/project_cache.rs#L1062-L1065).

**Comment by jjbayer** [comment]
@williamdes feel free to reopen with a config to reproduce if you still encounter this issue.

**Comment by williamdes** [comment]
You need to use this config and un-comment the line: https://github.com/getsentry/self-hosted/issues/2876#issuecomment-2084399019

**Comment by jjbayer** [comment]
The error comes from the SQLite driver so it might still be a permission problem. Does this help you in any way?

> The SQLITE_CANTOPEN result code indicates that SQLite was unable to open a file. The file in question might be a primary database file or one of several [temporary disk files](https://www.sqlite.org/tempfiles.html).

https://www.sqlite.org/rescode.html#cantopen
