### ISSUE TITLE
"relay_server::services::store: StoreService received unexpected item type" Error from sentry-self-hosted-relay-1  container after upgrade from 23.8.0 to 24.4.1

### ISSUE THREAD

**Issue by allen12921** [getsentry/relay#3492]
### Self-Hosted Version

24.4.1

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.20.0

### Steps to Reproduce

1.upgrade from 23.8.0 to  24.4.1
2.docker compose logs -f  
3.docker logs -f sentry-self-hosted-relay-1 

### Expected Result

no such error

### Actual Result

There are many such errors for different tags.project_key:
2024-04-25T09:47:02.415953Z ERROR relay_server::services::store: StoreService received unexpected item type: session tags.project_key=xxxxxxxx tags.event_type="none"

**Comment by Dav1dde** [comment]
I'll take a look, we recently stopped (and removed) session ingestion from Relay, but sessions should still be accepted! But instead Relay should turn sessions into metrics and forward these instead. There is possibly a feature flag missing or too much. The idea is to remove the feature flag alltogether and extract sessions unconditionally into metrics.

This won't help you right now for self hosted, I'll try to figure out what feature flag is missing or what needs to be flipped so you can set it in your self hosted instance and keep using the upgraded version until there is a new release.

**Comment by Dav1dde** [comment]
@allen12921 can you try enabling the `organizations:metrics-extraction` feature flag and see if that resolves your issue?

**Comment by Dav1dde** [comment]
Related: https://github.com/getsentry/relay/issues/3368

**Comment by Dav1dde** [comment]
This should be fixed with the next Sentry release, closing this for now.

As a workaround until the next release, setting the feature flag `organizations:metrics-extraction` should suffice.
