### ISSUE TITLE
Cloudflare IP visible in Sentry for NextJs tunnel instead of real user IP

### ISSUE THREAD

**Issue by szwabodev** [getsentry/relay#3493]
Hello, I am having trouble with getting real user IP to save in my tunneled Sentry errors/messages while using Cloudflare as a proxy for my NextJS application.

The problem is that Cloudflare replaces the "X-Forwarded-For" header with its own server IP and the real user IP is under "CF-Connecting-IP" header. I have tried using a middleware for my Sentry tunnel endpoint to replace the request's and response's "X-Forwarded-For" and "X-Vercel-Forwarder-For" as well as "X-Sentry-Forwarded-For" with the value of real user IP, however Sentry still keeps storing the cloudflare IP instead. 

Would it be possible to add this "[CF-Connecting-IP](https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#cf-connecting-ip)" as a priority header so that Sentry can automatically grab its value instead of the others if it exists? I will keep trying to replace it somehow in the middleware in the meantime, but it would be much easier if Sentry did it automatically.

**Comment by Dav1dde** [comment]
We should do that! Opened PR #3496 to add support for the cloudflare header, like we already have it for Vercel.

**Comment by szwabodev** [comment]
> We should do that! Opened PR #3496 to add support for the cloudflare header, like we already have it for Vercel.

Hello again, thanks for handling it quick, however, after checking some of my latest errors/messages in Sentry, I still see cloudflare IP saved in user context instead of real user IP. I am currently on 7.113.0 SDK version for NextJS.

**Comment by Dav1dde** [comment]
Sounds like you're using a tunnel. If that runs on a cloudflare worker it won't forward the header in the fetch call.

**Comment by szwabodev** [comment]
> Sounds like you're using a tunnel. If that runs on a cloudflare worker it won't forward the header in the fetch call.

My app is hosted on Vercel, I only use Cloudflare for proxying traffic through it for additional protection and caching. I don't use any of the CF workers. Also, like I mentioned in the first post, when I console.log the "CF-Connecting-IP" in my middleware, I can see the real IP of the user in my server logs, so it's available for sure.

I checked the changes [in your code](https://github.com/getsentry/relay/blob/master/relay-server/src/extractors/forwarded_for.rs#L46C19-L46C42), and it looks like you still use "VERCEL_FORWARDED_HEADER" with priority over new cloudflare header, and if I am not mistaken, this header also had value of CF IP instead of user IP which would still send wrong IP to Sentry in this case on Vercel. I can check it out later, but I am pretty sure that will be the cause why I still get CF ip in errors.

**Comment by Dav1dde** [comment]
If you're sending both headers than yeah, Vercel will have priority, that was on purpose to not accidentally break something for existing users already using the Vercel header. 

But it may make sense to swap these around, it's more common to have CF infront of Vercel.

**Comment by szwabodev** [comment]
> If you're sending both headers than yeah, Vercel will have priority, that was on purpose to not accidentally break something for existing users already using the Vercel header.
> 
> But it may make sense to swap these around, it's more common to have CF infront of Vercel.

Yeah, both headers are added automatically, but in my opinion CF should have priority in this case, even as you mentioned, there are for sure some users which use Cloudflare as extra layer over Vercel.

**Comment by Dav1dde** [comment]
Let's swap the order, opened a PR https://github.com/getsentry/relay/pull/3627 - I agree this makes more sense. Thanks for the report/update!
