### ISSUE TITLE
Loosen IP address scrubbing in `span.domain` tag

### ISSUE THREAD

**Issue by gggritso** [getsentry/relay#3572]
### Problem Statement

IP addresses like `8.8.8.8` get fully scrubbed out to `*.*.*.*`. When users look at the requests module, all requests to IP addresses get mashed together.

### Solution Brainstorm

- no scrubbing at all (IPv4 addresses have a known cardinality. It's only 4 billion! That's fine, right? I'm kidding)
- partial scrubbing (e.g., `8.8.8.8` becomes `*.*.8.8` or `*.*.*.8` or `8.8.*.*`)
- customizable IP scrubbing allowlist (let people add IPs that don't get scrubbed)
- allow self-hosted users to turn IP scrubbing off (people who have their own infra might want to turn this off, and bear the weight of high cardinality)

### Product Area

Ingestion and Filtering

**Comment by jjbayer** [comment]
> customizable IP scrubbing allowlist (let people add IPs that don't get scrubbed)

I wonder if we could get to an "80%" solution by hardcoding a list of"special" IPs. E.g. reserved IPs, DNS servers, .... Unless this does not cover the majority of the cases.

**Comment by aldy505** [comment]
I'd like to see private IPs being not redacted on SaaS and self-hosted. For public IPs, I think it's better if it's redacted on SaaS and not redacted on self-hosted. Since on self-hosted, it's a different environment, it's only possible that the outgoing request is made only for those defined on the `tracePropagationTargets` config (from the sdk side).

**Comment by aldy505** [comment]
Hey @jjbayer @gggritso seeing [this PR](https://github.com/getsentry/relay/pull/3383) I think I can implement this one.. partially. Right now we only allow `127.0.0.1` as seen on here: https://github.com/getsentry/relay/blob/e1fb9f1251ff5dc8e03de58a95a87f3dd686e1e3/relay-event-normalization/src/normalize/span/description/mod.rs#L243

But considering what @jjbayer said, it's a good idea to whitelist "special IPs", with what I had in mind are:
- `192.168.0.0–192.168.255.255` (65,536 addresses)
- `10.0.0.0–10.255.255.255` (16,777,216 addresses)
- `100.64.0.0–100.127.255.255` (4,194,304 addresses)
- `172.16.0.0–172.31.255.255` (1,048,576 addresses)
- `192.0.0.0–192.0.0.255` (256 addresses)
- `198.18.0.0–198.19.255.255 (131,072 addresses)

Private IPv6 address has higher address count, so I believe that's out of the question. For popular IPs like DNS servers and such, I don't think there's any good use case for it to be included in a span. Although I might be wrong here.

**Comment by Dav1dde** [comment]
I think we should just use [`Ipv4Addr::is_private`](https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#method.is_private), if we decide to implement it.

**Comment by jjbayer** [comment]
Private addresses can still be high cardinality, so I wouldn't unconditionally allowlist them all. IMO the simplest thing we can start with is add a global option that allows self-hosted users to disable IP scrubbing. @gggritso what do you think?

**Comment by aldy505** [comment]
> Private addresses can still be high cardinality, so I wouldn't unconditionally allowlist them all.

I'm wondering about how "high" is the high cardinality for you? 

> IMO the simplest thing we can start with is add a global option that allows self-hosted users to disable IP scrubbing. @gggritso what do you think?

Yes, this should also work, since self-hosted has known range. But the default should be set to `false` (disabled) though.

**Comment by jjbayer** [comment]
> I'm wondering about how "high" is the high cardinality for you?

Can't give you an exact number, but the purpose of the scrubbing is to merge spans into "meaningful" groups. So accepting every single private IP as a separate group would be too fine grained IMO, but we could do partial scrubbing for private IPs like the issue description proposes (e.g. `192.168.*.*`).

**Comment by gggritso** [comment]
We haven't heard a lot of complaints about this issue lately, so I don't have a strong opinion. I think starting with allowing self-hosted users to turn off scrubbing completely feels like a good solution even though it'll let people degrade their own experience with Sentry. Either that, or an IP allowlist for self-hosted folks seems like it'd solve a lot of these problems!

**Comment by aldy505** [comment]
> > I'm wondering about how "high" is the high cardinality for you?
> 
> Can't give you an exact number, but the purpose of the scrubbing is to merge spans into "meaningful" groups. So accepting every single private IP as a separate group would be too fine grained IMO, but we could do partial scrubbing for private IPs like the issue description proposes (e.g. `192.168.*.*`).

I'd rather go with @gggritso's solution on whitelisting a certain IPs. I'm also thinking of specifying CIDRs? Something along the line of `192.168.18.0/24` instead of declaring all 255 IPs on the relay config.

**Comment by jjbayer** [comment]
> an IP allowlist for self-hosted folks

Sounds good to me. @aldy505 I'll add it to our backlog, I cannot make any promises on when this will be implemented though.

**Comment by aldy505** [comment]
> > an IP allowlist for self-hosted folks
> 
> Sounds good to me. @aldy505 I'll add it to our backlog, I cannot make any promises on when this will be implemented though.

I might be able to work on this later this weekend, can you point out to me somethings that I need to take a look at? (Other than this file https://github.com/getsentry/relay/blob/master/relay-event-normalization/src/normalize/span/description/mod.rs)

**Comment by jjbayer** [comment]
@aldy505 that would be great and very welcome!

Best would probably be to register an option for the allowlist on sentry side, add it to this list: https://github.com/getsentry/sentry/blob/23ccc70817cc6dbc43230ddd86c2f6329ecb34ab/src/sentry/relay/globalconfig.py#L13-L14, then declare it in relay as well: https://github.com/getsentry/relay/blob/a440dbb87539ca1637a7aa77de5854ed247dd7d9/relay-dynamic-config/src/global.rs#L106-L110 and pass the allowlist into the normalization module you referenced.

**Comment by aldy505** [comment]
@jjbayer Quick question, since I need to implement the allowlist here: https://github.com/getsentry/relay/blob/6dc184f0d1b339460909a27c9c152bdbe3098bf9/relay-event-normalization/src/normalize/span/description/mod.rs#L228-L234

And since we can't make `GlobalOptions` as `Arc<>` since there's no struct that would hold it for long, how would you recommend me to pass the allowlist? I'm thinking of modifying the function signature, but that wouldn't be nice.

**Comment by jjbayer** [comment]
I have no better idea than passing it all the way through the call stack, like we do here: https://github.com/getsentry/relay/blob/6dc184f0d1b339460909a27c9c152bdbe3098bf9/relay-server/src/services/processor.rs#L1483

**Comment by aldy505** [comment]
I see, thanks. Might do this tomorrow.

**Comment by jjbayer** [comment]
The allowlist approach is now implemented and merged (see linked PRs).

**Comment by gggritso** [comment]
Awesome!
