### ISSUE TITLE
Document Relay API endpoints

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#3591]
Relay is, among other things, a web API, but its endpoints are not documented.

Let's add rustdoc documentation for all endpoints.

**Comment by jjbayer** [comment]
cc @cleptric

**Comment by jjbayer** [comment]
Should be OpenAPI spec o.a., ideally auto-generated from rust code.

**Comment by Dav1dde** [comment]
We should instead have a proper spec in the dev docs and Relay is just the implementor of the spec.
