### ISSUE TITLE
No scoping due to missing project ID

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#3651]
See

[POP-RELAY-31Z](https://sentry.my.sentry.io/organizations/sentry/issues/929927/)

This is related to https://github.com/getsentry/relay/issues/3553, but not the same, because the failure happens _before_ aggregation.

Started happening around May 15th.

**Comment by jjbayer** [comment]
There's a bad assumption in here somewhere:

```
see the error
  => state_value() missing
    => contradiction! `merge_buckets_into_aggregator` would not even be called
  OR
  => project_id is none
    => project is invalid or disabled
      => contradiction! we call check_disabled in both code paths leading to the error
    OR
    => project is expired
      => contradiction! project_id wouldn't be none
```

**Comment by Dav1dde** [comment]
I am making a few changes to how metrics work this should fix this issue as well.

**Comment by Dav1dde** [comment]
There are project cache changes coming from @jjbayer which should address this issue. My changes did not touch this part of the code, only surrounding parts.

**Comment by jjbayer** [comment]
Has not occurred since Jun 24.
