### ISSUE TITLE
[Flaky CI]: test_rate_limit_metrics_consistent

### ISSUE THREAD

**Issue by Swatinem** [getsentry/relay#3664]
### Flakiness Type

Assertion failure

### Name of Test

tests/integration/test_spans.py::test_rate_limit_metrics_consistent

### Link to Test Run

https://github.com/getsentry/relay/actions/runs/9286693626/job/25553960573?pr=3654

### Details

```
  File "/home/runner/work/relay/relay/tests/integration/test_spans.py", line 1642, in test_rate_limit_metrics_consistent
    assert len(spans) == 0
AssertionError: assert 1 == 0
 +  where 1 = len([{'data': {'browser.name': 'Python Requests'}, 'description': 'my 1st OTel span', 'duration_ms': 1000, 'end_timestamp_precise': 1716988991.946604, ...}])
```

**Comment by Dav1dde** [comment]
Previously and apparently not fixed https://github.com/getsentry/relay/issues/3343

**Comment by jjbayer** [comment]
Possibly fixed by https://github.com/getsentry/relay/pull/3700, I will reopen this issue if it occurs again.
