### ISSUE TITLE
output what feature shoule enable in log

### ISSUE THREAD

**Issue by RiESAEX** [getsentry/relay#3683]
I'm self-hosting a relay in static mode.
I find a lot of `WARN relay_server::services::processor::span: dropping span because feature is disabled` in log, but no idea what feature I should enable for which project.

**Comment by iker-barriocanal** [comment]
Hi! This log message belongs to an experimental product and runs in other types of Relays. Feel free to ignore it, https://github.com/getsentry/relay/pull/3685 decreases the log level to `DEBUG`.
