### ISSUE TITLE
Add custom-metrics-ingestion-disabled option

### ISSUE THREAD

**Issue by matejminar** [getsentry/relay#3690]
Today, we have a `custom-metrics-disabled` option that, when enabled, kills both UI and ingestion.
We want the old `custom-metrics-disabled` option removed and replaced with `custom-metrics-ingestion-disabled`, which just kills ingestion. This needs to be true for both US and DE regions.

This is a result of a discussion around the metrics readiness checklist: https://www.notion.so/sentry/Metrics-GA-753de24577b54c8fa5c39d7dd2298350?pvs=4#beccdb7cf1444562a37b0576944eb7a5

**Comment by jan-auer** [comment]
No longer needed.
