### ISSUE TITLE
Multi-valued metric tags not supported

### ISSUE THREAD

**Issue by elramen** [getsentry/relay#3691]
The [metrics developer docs](https://develop.sentry.dev/sdk/metrics/) say _"metrics are tagged by key value pairs, where each key can have more than one value."_ Also the [RFC](https://github.com/getsentry/rfcs/blob/metrics/text/xxxx-metrics.md) says _"More than one value per key is permitted if represented as a list or tuple."_ Multi-valued tags is also implemented in the python sdk (not sure about the other sdks). 

However, it seems that relay doesn't allow multi-valued tags for single emissions, only the last value of the list/tuple sent is actually used. Have raised this issue offline but opening it here so it's not forgotten.

**Comment by jjbayer** [comment]
@elramen thanks, good catch! Do you have a specific use case for multi-value tags? Neither Relay nor storage support it so I will remove it from the Relay docs. As for the Python SDK docs, all the examples [here](https://docs.sentry.io/platforms/python/metrics/) show dictionaries so I think we're good?

**Comment by elramen** [comment]
Hey @jjbayer, I don't have a specific use case for it, just opened this issue to make sure things are aligned. 

I'll remove Tuple and List from the Python SDK's type hints for tag values.

**Comment by szokeasaurusrex** [comment]
> @elramen thanks, good catch! Do you have a specific use case for multi-value tags? Neither Relay nor storage support it so I will remove it from the Relay docs. As for the Python SDK docs, all the examples [here](https://docs.sentry.io/platforms/python/metrics/) show dictionaries so I think we're good?

@jjbayer To be clear, I believe that @elramen is referring to the tag **values** (i.e. the values of the tags dictionary), which in the Python docs examples are all strings. The question is referring to whether the tags could have multiple values, e.g. by setting a value in the dictionary to a list. The tags would still be defined in a dictionary

**Comment by Dav1dde** [comment]
A single metric emission can only have one value per key and every key must be unique. Please check the [docs PR](https://github.com/getsentry/develop/pull/1307) if that new explanation does make sense to you.
