### ISSUE TITLE
Produce outcomes for spans in transactions

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#3705]
On the fast path (i.e. during request handling), we reject transactions if their quota is zero. For new plans that are based on spans rather than transactions, we would also like to produce an outcome for the number of rejected spans (contained spans + 1). This is not straight-forward because the transaction has not been parsed at the point where we reject it.

We could extend `MinimalEvent` with a list of empty objects (`spans`) just to count the number of spans to produce outcomes for: https://github.com/getsentry/relay/blob/e549ce1270f683f3ee86f4ebe5f6a6d0c95d161a/relay-server/src/endpoints/common.rs#L154-L160

Note: it is not necessary to derive a rate limiting decision for the transaction itself just from span quota, because sentry can / will send an exhausted transaction quota as well.

**Comment by iambriccardo** [comment]
We are deferring the implementation, because it doesn't work with the SDKs since they are rate-limiting spans but not communicating the numbers to Relay, so even if we implemented outcomes in Relay, data will still be broken.
