### ISSUE TITLE
Sentry checks for Relay deployments

### ISSUE THREAD

**Issue by IanWoodard** [getsentry/relay#3735]
Continuing off of #3369, it does appear that most of the sentry checks are working properly. S4S seems to not be receiving many events, but I am not sure if that is accurate or if the filtering is messed up. Either way, something to look into. Additionally, the sentry checks are currently being dry-run, meaning if the error count exceeds the threshold, it will not fail. Once we are confident in the thresholds and filtering, we should set dry-run to false so they can start doing their job.

**Comment by olksdr** [comment]
@IanWoodard  is this something you have time to look into?

**Comment by bc-sentry** [comment]
@IanWoodard Please reopen if this is still relevant and/or needs investigation.
