### ISSUE TITLE
Make the aggregator partition aware

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/relay#3737]
The metrics aggregator is now generating partitions of a bucket when flushed and syncing partitions using flush times based on the partition key.

This mechanism works well in practice but we would like to try and implement partitions directly into the aggregator so that at each flush cycle we will flush a single partition.

Related to: https://github.com/getsentry/team-ingest/issues/258

**Comment by jan-auer** [comment]
This has been implemented in https://github.com/getsentry/relay/pull/3661
