### ISSUE TITLE
`.\some\directory\relay.exe config show` shows incorrect data (when not called from `relay.exe` dir or using `--config`)

### ISSUE THREAD

**Issue by simonmcconnell** [getsentry/relay#3763]
Hello,

It seems relay.exe is looking for the config relative to the current working directory rather than the directory that the executable is in.  Is this intentional?  It was unexpected.  If it is intentional, it could be explained more clearly in the docs.

> Configuration for Relay is recorded either in the file .relay/config.yml, or when noted, can be overridden through an environment variable. To change the config location, pass the --config option to any Relay command:

Note that upstream is set by an environment variable in the following.

```
> D:\AAA> .\include\relay.exe config show
relay:
  mode: managed
  upstream: http://10.36.36.36:4001/
  host: 127.0.0.1
  port: 3000
...
# expected mode: static and port: 3001

> D:\AAA> .\include\relay.exe --config .\include\.relay\ config show
relay:
  mode: static
  upstream: http://10.36.36.36:4001/
  host: 127.0.0.1
  port: 3001
...

> D:\AAA> cd .\include\

> D:\AAA\include> .\relay.exe config show
relay:
  mode: static
  upstream: http://10.36.36.36:4001/
  host: 127.0.0.1
  port: 3001
...
```

relay 24.6.0
Windows Server 2019

**Comment by jjbayer** [comment]
> It seems relay.exe is looking for the config relative to the current working directory rather than the directory that the executable is in. Is this intentional?

Hey @simonmcconnell, yes that is intentional. I've added some clarification to the docs:

https://github.com/getsentry/sentry-docs/pull/10498
