### ISSUE TITLE
Health check urls require trailing slash

### ISSUE THREAD

**Issue by klemmchr** [getsentry/relay#3773]
When querying health check endpoints a trailing slash is required, otherwise the endpoint is not found and a 404 is reported. While this is not a bug and the documentation includes a trailing slash, this is something one might miss (e.g. when copying). It is quite uncommon for url paths to require trailing slashes these days.

**Comment by Dav1dde** [comment]
Currently we require trailing slashes for internal/non user facing routes and there are no current plans to change this. 

Although I agree it wouldn't hurt to accept both, but at the current state we're still using a relatively old version of the axum framework for our routes, implementing this now would be incompatible with the most recent version. I'll keep it in mind for the upgrade.
