### ISSUE TITLE
ERROR relay_server::services::health_check: Health check probe 'auth' failed,

### ISSUE THREAD

**Issue by xuweixi10** [getsentry/relay#3774]
when i start relay, i get this error
here is my config
`relay:
  upstream: "https://sentry.xxx.com/"
  host: 0.0.0.0
  port: 3000
logging:
  level: DEBUG
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "kafka:9092"}
    - {name: "message.max.bytes", value: 50000000} # 50MB
  redis: redis://xxx`

**Comment by xuweixi10** [comment]
when i send event i also get error
ERROR relay_server::services::project_upstream: error fetching project state fa53341d006347a5f58eef5b0096e3a7: deadline exceeded errors=0 pending=236 tags.did_error=false tags.was_pending=true tags.project_key="fa53341d006347a5f58eef5b0096e3a7"

**Comment by Dav1dde** [comment]
Make sure your upstream is reachable, looking you have processing enabled in which case you wouldn't want to go through a public route. You can follow the [self hosted config](https://github.com/getsentry/self-hosted/blob/master/relay/config.example.yml) and [docker compose](https://github.com/getsentry/self-hosted/blob/master/docker-compose.yml).

Going through a public route will mean the Relay is not authenticated, if you absolutely must go through a public route you need to register the Relay in the org settings.

**Comment by Dav1dde** [comment]
I assume this answers your question feel free to re-open or reach out on discord if you have more issues.

**Comment by max-wittig** [comment]
@Dav1dde This still happens every time when the machine gets rebooted
