### ISSUE TITLE
Library builds fail after CentOS 7 EOL

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#3785]
CentOS builds for the Relay library fail since `mirrorlist.centos.org` no longer exists as CentOS 7 has reached EOL on 2024-07-01. 

Options to resolve this are:
- Replace the mirror with `vault.centos.org` in all repos
- Update to a more recent centos distribution along with a more recent manylinux

The detailed error message is:

```
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64
```

See also:
- [Example build](https://github.com/getsentry/relay/actions/runs/9764002786/job/26979163843#step:4:46)
- [Workaround on StackOverflow](https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve)

**Comment by jan-auer** [comment]
Sentry now runs on `python:3.11.8-slim-bookworm`, which is based on Debian `glibc 2.36`. 

This means we can update all the way to `pypamanylinux_2_28_{x86_64,aarch64}`. All available tags [here](https://quay.io/organization/pypa). Let's double-check with @asottile-sentry if we're happy to raise the minimum requirement.

**Comment by asottile-sentry** [comment]
2.28 is our current floor for pypi -- anything newer than that and it'll cause some problems but 2.28 should be fine!
