### ISSUE TITLE
Static and proxy mode should forward profiles and replays

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#3800]
A few months back I added this documentation because we noticed static Relays dropped replays:

> Some Sentry product features are disabled by default in Relay, either because they are still experimental or because they are not available on all plans. In static mode, these features have to be enabled manually if needed.

https://docs.sentry.io/product/relay/projects/#basic-options

We have the same problem with profiles: We filter all profiles if the feature flag is enabled, so proxy Relay cannot forward them:

https://github.com/getsentry/relay/blob/89a8dd7caaad1f126e1cacced0d73bb50fcd4f5a/relay-server/src/services/processor/profile.rs#L30-L32

This is bad for usability, and goes against the philosophy of proxy relays (which is forward everything).

Desired outcome:
* Proxy relays forward everything.
* Static relays forward everything by default.

**Comment by cleptric** [comment]
cc @stayallive

**Comment by Dav1dde** [comment]
Should we treat all feature flags as implicitly enabled for these Relays?

**Comment by jjbayer** [comment]
> Should we treat all feature flags as implicitly enabled for these Relays?

I'm afraid we cannot generalize it like that. The filtering logic should rather be `if internal_relay && ! feature_enabled { drop() }`. Or we give every feature flag an explicit default and set the filtering ones to `true`.

**Comment by stayallive** [comment]
Is there anything I can configure to force Relay to forward the data? Currently missing quite some data and would rather not use the direct connection but keep my local Relay to reduce latency and effects of upstream Sentry.

**Comment by jjbayer** [comment]
@stayallive do you have the option of adding a static project config as a workaround, like described [here](https://docs.sentry.io/product/relay/projects/)? See feature flags at the bottom of that page. You can keep the Relay mode configured as `proxy`:

> Proxy mode is similar to static mode, but it forwards events from unknown projects. In this mode, events for statically configured projects are handled identically to static mode.

**Comment by stayallive** [comment]
That is far from ideal, but it's an option for now. Thanks!

**Comment by jjbayer** [comment]
Bumped priority to P1 because this affects all customers using proxy relays who want to use replays or profiles.
