### ISSUE TITLE
failed to setup the database: error returned from database: (code: 5) database is locked

### ISSUE THREAD

**Issue by klemmchr** [getsentry/relay#3816]
I'm trying to set up spooling for relays hosted using Azure Container Apps. I have multiple replicas and have auto scaling configured. I want to reduce the amount of memory used using spooling. The documentation about it really isn't great so I assumed that the storage provided to each instance should be shared so that all instances can access the same storage. I did this using a shared volume. Now I get the error that the database is locked.  
Therefore I assume that every replica should have their own (ephemeral) storage. Is this assumption correct?

**Comment by Dav1dde** [comment]
> Therefore I assume that every replica should have their own (ephemeral) storage. Is this assumption correct?

Correct. Each Relay instance needs its own storage.

My recommendation for you, at this time, is to not enable spooling. It is quite fragile at the moment and probably doesn't work as you expect it, we have ongoing work to rework and improve it.

For example it will not improve the memory usage and data will still be lost under memory pressure, it does not work like you'd expect a swap to work. The future spooling will address this.

**Comment by klemmchr** [comment]
> My recommendation for you, at this time, is to not enable spooling. It is quite fragile at the moment and probably doesn't work as you expect it, we have ongoing work to rework and improve it.

Might be worth mentioning this in the docs. Spooling is explained nowhere.

> For example it will not improve the memory usage and data will still be lost under memory pressure, it does not work like you'd expect a swap to work. The future spooling will address this.

So what exactly is spooling for then?

**Comment by Dav1dde** [comment]
> Might be worth mentioning this in the docs. Spooling is explained nowhere.

Docs need to be improved, but the current 'weird' behaviour is one of the reasons it's not explained more, because it probably doesn't do what you want it to do.

> So what exactly is spooling for then?

It's basically a temporary storage for a limited amount of conditions, for example when a project config cannot be fetched from upstream and there is a certain threshold of envelopes already in memory, it will be stored in the spool until it is ready.

But this is old behaviour we want to change and are currently working on, it should behave like you're expecting it.

**Comment by klemmchr** [comment]
So what exactly is the current way to reduce memory footprint? Just cranking up memory until the process doesn't crash any more? I dislike having multiple replicas with more than 2 Gigs of RAM, some of our application services are serving more requests and taking less resources than the Sentry relay.

**Comment by Dav1dde** [comment]
The spool won't reduce the memory footprint.

Generally Relay scales better if you give it more resources over more instances, especially memory. So yes the general recommendation is to give it more memory and CPU over scaling horizontally.

Relay has a relatively large baseline of resources required at the moment, but if you satisfy that and memory consumption is growing, that might be a sign that it cannot process envelopes fast enough and buffers in memory instead -> check the CPU usage.

**Comment by klemmchr** [comment]
Appreciate the quick responses.

Since Container Apps have tight limitations when it comes to computing resources I will just try to find a sweet spot then. For Container Apps the amount of memory is always twice the amount of CPU cores. We're running at 1 core and 2 GB RAM and I was hoping that this would be enough.

Is there any soft ETA on the rework of spooling?

The memory usage on the relay seems to be quite constant at maximum memory. After restarting it takes only little time to fill up again. To me this could indicate a memory leak.

![image](https://github.com/user-attachments/assets/65114000-d55d-42dc-98ca-ff96270af225)

**Comment by Dav1dde** [comment]
> Is there any soft ETA on the rework of spooling?

We're currently in a designing phase, with some work slowly starting, I'd hope until end of the quarter. But spooling again wouldn't decrease overall memory consumption it would just deal with backlogs much better, the baseline would be unaffected.

> We're running at 1 core and 2 GB RAM and I was hoping that this would be enough.

It really depends on how much traffic you're seeing, I'd be interested in a ballpark number of requests/second you're getting.

**Comment by Dav1dde** [comment]
> The memory usage on the relay seems to be quite constant at maximum memory. After restarting it takes only little time to fill up again. To me this could indicate a memory leak.

This is to be expected and again depends a lot on your setup, e.g. Relay will pretty much forever cache project configurations (as long as they get an envelope an hour). Additionally if services are backlogging because of not enough processing power this will naturally happen as data accumulates.

We're experiencing no memory leak in our SaaS instances (steady memory consumption) so I don't think there is an actual leak.

**Comment by klemmchr** [comment]
So our setup is as follows:

- Managed mode
- 2 Relay Instances with a round-robin load balancer running at 1 vCPU and 2 GiG RAM (now scaled up to 1.5 vCPU and 3 GiG RAM)
- 5 Projects using the relay
- Around 500.000 Performance Units, 20.000 errors and 1500 replays per month
- Default configuration (max 100 concurrent requests and so on)

This are the requests of the last 24 hours grouped by 5 minutes.

![image](https://github.com/user-attachments/assets/179dd8dc-1e54-42f7-a0e7-30c3e98c4187)

This shows 7 days with same granularity

![image](https://github.com/user-attachments/assets/2550f7e1-4107-4777-b18a-aba06c32d51a)

> We're experiencing no memory leak in our SaaS instances (steady memory consumption) so I don't think there is an actual leak.

How is the relay used in Saas?

**Comment by Dav1dde** [comment]
If I didn't mess up my math that's less than 2 requests per second, we're seeing a throughput of >500/s per core on Relay (now the composition of envelopes may be different from SaaS than your setup). Although again, Relay does have a certain baseline of CPU usage (scheduled jobs that always happen independent of volume), adding more cores will scale better than horizontal scaling also for CPU.

I'd gradually give it more memory and see when it evens out, long term the new spooling should be able to compensate spikes and prevent OOMs (current one does not).

> How is the relay used in Saas?

Our setup is a bit more complicated (we have multiple regions to ensure fast response times across the globe) but apart from that it essentially is just a managed Relay on bigger machines autoscaled.

**Comment by klemmchr** [comment]
I'm going with 2 vCPUs and 4 GiG RAM now and will monitor the system over the next couple days. I've also reduced sample size at the same time to see the impact there.

Are there any benefits to the current implementation of spooling that would make it worth activating? And do you have any plans on reducing overall resource usage for each relay instance to allow scenarios with horizontal scaling on low resources?

**Comment by Dav1dde** [comment]
> Are there any benefits to the current implementation of spooling that would make it worth activating? 

At this current state I would say it is primarily useful for our SaaS environment where we deal with many many thousands of projects and various other issues you should never experience in a more controlled environment. So no, I would not activate it.

> And do you have any plans on reducing overall resource usage for each relay instance to allow scenarios with horizontal scaling on low resources?

Plans yes, time for it no. I wanted to look into this for pretty much half a year now. Definitely on the todo but other things keep pushing it down in priority. Generally Relay will always benefit from more resources over horizontal scaling because of internal caches and things like metric aggregation (metrics just aggregate better if they are all in one place ;)). But we want to bring the baseline consumption down, which will make horizontal scaling much more attractive.

**Comment by klemmchr** [comment]
Gotcha. Thanks for the nice conversation and your quick help. I'm going to monitor our relays for a bit now, but right now the changes made look quite promising. Closing for now.

**Comment by Dav1dde** [comment]
@klemmchr awesome! 

I remembered one thing, when Relay starts up, it logs something like `starting 10 envelope processing workers`, make sure this value does not **exceed** (less is okay) the amount of cores you give Relay. This may interact incorrectly with cgroups, if it does, set `limits.max_thread_count` to the number of CPU cores available.

**Comment by klemmchr** [comment]
Is this setting affecting the amount of concurrent requests the relay can handle or is this only for the background worker that forwards them to the ingestion endpoint?

**Comment by Dav1dde** [comment]
The log message tells you how many worker threads are spawned for the CPU intensive part of Relay, the config setting is used to infer the amount of workers that should be started and the max amount of worker threads the tokio runtime gets allocated.

**Comment by klemmchr** [comment]
Cheers, gonna check that.
