### ISSUE TITLE
Add documentation for environment variable `RELAY_LOG_LEVEL`

### ISSUE THREAD

**Issue by klemmchr** [getsentry/relay#3823]
Some deployment methods make it hard to edit configuration files during deployment. Currently I need to redeploy our relay when I want to change the log level in the config. This is quite inconvenient. It would be great if the log level could be set using an environment variable (e.g. `RELAY_LOGGING_LEVEL`).

**Comment by Dav1dde** [comment]
`RELAY_LOG_LEVEL` already exists and overrides `logging.level`.

**Comment by klemmchr** [comment]
That's good to know. Then the [documentation](https://docs.sentry.io/product/relay/options/) is missing out on that.

**Comment by Dav1dde** [comment]
Sorry small correction, the env var is actually `RELAY_LOG_LEVEL`

**Comment by klemmchr** [comment]
PR has been created
