### ISSUE TITLE
can't find sentry-relay@0.8.7 anymore

### ISSUE THREAD

**Issue by yayapao** [getsentry/relay#3826]
Our team use self-hosted@21.6.3 sentry, and it's requirements.txt look like this:

```
sentry-relay (==0.8.7)
```

But now we can't find it anywhere, both at pipy or getsentry/relay/release, So what happened and what can i do to solve the problem?

BTW, before 2024-01 it worked fine!

**Comment by iambriccardo** [comment]
Hi, let me help you out!

Unfortunately, we have removed some versions of `sentry-relay` and other libraries due to space problems in our public pypi.

My suggestion here would be to upgrade sentry.
