### ISSUE TITLE
Redis: One Pool per usecase

### ISSUE THREAD

**Issue by Dav1dde** [getsentry/relay#3829]
We should split the Regex pools into multiple pools, one per usecase:

- Project Config
- Cardinality
- Quotas
- Misc (metric meta)

The configuration should accept the config we already have and use that to configure each pool with these values or share the same pool for all usecases (tbd).

Additionally the config should accept a config for each pool with different configuration values.

**Comment by loewenheim** [comment]
Can you reiterate which services (`EnvelopeProcessor`, `ProjectCache`, `RelayStats`) need access to which Redis pools?

**Comment by Dav1dde** [comment]
- `ProjectCache` needs project configs
- `RelayStats` needs all pods (it just exports pool metrics via statsd, we want these stats for all pools)
- `EnvelopeProcessor` needs cardinality, quotas and misc (metric meta)
