### ISSUE TITLE
Support configuring custom tags to be sent along for internal Error reporting

### ISSUE THREAD

**Issue by tcoville-coveo** [getsentry/relay#3842]
Hi !

We have a self-hosted version of the sentry relay on our infrastructure and we configured it to send its own sentry issues to our sentry account via [this config](https://docs.sentry.io/product/relay/options/#internal-error-reporting).

However as we have many regions for a given environment, when an issue arise it is impossible for us to know in which region the issue occured as the only tag included in the sentry issue is the environment one. 

![Image](https://github.com/user-attachments/assets/5e170289-6549-4462-8ca8-b5e8de0c5fef)

Ideally we would like to be able to set a config and / or an environment variable in the relay deployment with the region so that it is sent along in relay's own sentry issues and we can include that tag in our alerts.

NOTE: this really concerns the relay's own issues not any issue being sent through it :)

Thanks :)

**Comment by Dav1dde** [comment]
We already have this for metric tags, `default_tags`. We'd need a similar thing for the Sentry section and probably need to use a `before_send` hook in the SDK to add the tags.

This is a useful feature but very far in the backlog for us, we'd appreciate a PR if you want to work on this.
