### ISSUE TITLE
Luhn algorithm for credit card number validation

### ISSUE THREAD

**Issue by oioki** [getsentry/relay#3879]
Currently, Relay validates if a specific string is a payment card by using only [regex](https://github.com/getsentry/relay/blob/master/relay-pii/src/regexes.rs#L202-L220). However, payment card numbers typically pass the [Luhn algorithm check](https://en.wikipedia.org/wiki/Luhn_algorithm), what we could use to reduce false positives:
> Most credit cards and many government identification numbers use the algorithm as a simple method of distinguishing valid numbers from mistyped or otherwise incorrect numbers.

**Comment by Dav1dde** [comment]
Requires a bigger refactor in the PII scrubbing, closing for now until more customer issues surface.
