### ISSUE TITLE
Fix trimming of spans

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/relay#3880]
This PR (https://github.com/getsentry/relay/pull/3645) introduced a maximum size for spans, resulting in redactions of the contents of the span that effectively introduced problems with metrics because some fields are redacted and later used for tags in the metric.

**Comment by jjbayer** [comment]
Reopening because we're seeing [snuba](https://sentry.sentry.io/issues/5429321769/) and relay errors again, just like we saw before https://github.com/getsentry/relay/pull/3670.
