### ISSUE TITLE
Issue authenticating to on-premise instance

### ISSUE THREAD

**Issue by lunim** [getsentry/relay#39]
I have configured my on-premise instance to allow the relay public key, but am seeing this when attempting to run:

>  INFO  semaphore_trove::auth     > sending register challenge response
>  INFO  semaphore_trove::types    > changing auth state: RegisterRequestChallenge -> RegisterChallengeResponse
>  ERROR semaphore_trove::auth     > failed to register relay with upstream: bad request (401 Unauthorized; Challenge expired)
>  INFO  semaphore_trove::auth     > scheduling authentication retry

The failure happens instantly.

**Comment by mitsuhiko** [comment]
Currently this happens if the sentry instance does not have a cache configured. This will be solved soon.
