### ISSUE TITLE
arm64 binary does not work on AWS EC2 ARM

### ISSUE THREAD

**Issue by tytanick** [getsentry/relay#4006]
I am trying to execute arm64 binary on AWS Amazon Graviton ARM64 debian and getting error:

./relay: cannot execute binary file: Exec format error

Linux #24~22.04.1-Ubuntu SMP Sat Jul 20 10:48:15 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

**Comment by jjbayer** [comment]
@tytanick thanks for the report! How did you retrieve the binary? We do not currently release one (see https://github.com/getsentry/relay/issues/3497). https://github.com/getsentry/relay/pull/3943 might be related.

**Comment by tytanick** [comment]
Yeah might be related.
We used  binaries from amd64 on arm64 so the error is normal.
Then we tried to compile relay on arm64 but make release throws error like oit of memory. We do have 8gb of mem there so not sure why this happened.

Anyway, can tou guys make arm64 binary or maybe send it to me if anyone has it ?

**Comment by jjbayer** [comment]
> Anyway, can tou guys make arm64 binary

@tytanick Yes, we have a task to release ARM binaries on our backlog: https://github.com/getsentry/relay/issues/3497

Will close this ticket in the mean time.

**Comment by Dav1dde** [comment]
You can grab the binary from the arm64 docker container published on dockerhub and github. Or grab a nightly build from CI, for example from [here](https://github.com/getsentry/relay/actions/runs/10737380015) (if it's not expired yet), at the bottom of the page [`relay@aarch64-unknown-linux-gnu`](https://github.com/getsentry/relay/actions/runs/10737380015/artifacts/1900833124).
