### ISSUE TITLE
Unreal crash reporter issues no longer show user counts

### ISSUE THREAD

**Issue by redxdev** [getsentry/relay#4083]
**9/27 - This is now a Feature Request to support the `<LoginId>` field sent from the Unreal Crash Reporter in the `CrashContext.runtime-xml` and create a Sentry User based on the value of that field**

### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Configure an unreal engine project to use the built-in crash reporter (not the sentry SDK)
2. Crash, allow the crash to upload to sentry

Tested on Unreal 5.4.

### Expected Result

Issue create on sentry shows a user count, user id appears in context.

### Actual Result

No "user" is counted towards the issue, user count stays at 0.

This occurs despite EpicAccountId being set in CrashContext.runtime-xml. Manually sending `{ "user": { "id": "<id>" } }` as part of game data does not fix this either, though other context data sent as part of the "user" object does appear as part of the issue in the user context section (but not "id").

### Product Area

Processing

### DSN

https://218a1a74770c8302ae698208a6c67c20@o276210.ingest.us.sentry.io/4506471069908992

**Comment by mrduncan** [comment]
Hi @redxdev can you share a link to an example event so we can narrow this down a bit? If you'd prefer not to share your organization name publicly, feel free to email: matt.duncan@sentry.io

**Comment by redxdev** [comment]
@mrduncan Sent you an email. Thanks for taking a look!

**Comment by mrduncan** [comment]
I'm going to transfer this over to our Unreal folks since the events themselves look to be missing any of: `id`, `username`, `email`, or `ip` (https://github.com/getsentry/sentry/blob/master/src/sentry/utils/eventuser.py#L52) which are used to uniquely identify users.

**Comment by tustanivsky** [comment]
Hey @redxdev, whenever a crash occurs Crash Reporter tries to obtain your unique machine identifier which should be sent to Sentry along with other crash context data as `<LoginId>`. This particular value is then considered to be a valid user ID and unless something is preventing you from reading/sending it the user counter should be updated properly.

Sentry processes reports uploaded by Crash Reporter differently and currently there's no way to override this behavior (see getsentry/sentry-unreal#593 for more details) so setting the user ID manually via engine/plugin API won't take any effect.

The machine ID can be found in the Windows registry `Computer\HKEY_CURRENT_USER\Software\Epic Games\Unreal Engine\Identifiers\MachineId`.

Did you consider switching to native integration instead? It has pretty much the same level of crash details being reported while offering much more flexibility in terms of configuration/features.

**Comment by redxdev** [comment]
@tustanivsky I'm not looking to override the user id (though that would be nice). Sentry is not processing the login id in the first place - it is set in the uploaded CrashContext.runtime-xml, but sentry seemingly ignores the value and as such the user counter is never updated (or almost never - seems like very rarely the counter updates). Furthermore no user id is shown anywhere in an event's context.

Nothing changed on our end, we have not modified how the unreal crash reporter works since this started happening (though I did attempt to add a user.id value myself once I noticed it happening, but as you stated that doesn't work anyway). Sentry seemingly stopped processing the LoginId element a month or two ago.

We are not considering using the native integration at this time.

**Comment by redxdev** [comment]
Following up here, still wondering why sentry doesn't seem to be taking `LoginId` (or any other field, I don't entirely understand which fields get used when uploading a CrashContext.runtime-xml) into account as the user id. Once again, I am _not_ trying to override the id, I'm just trying to understand why suddenly sentry seems to be ignoring it with no changes on the game side.

**Comment by Fwang36** [comment]
Hey, I wanted to bump this issue.  

The user has written in to support regarding this and I took a look at many of their Sentry issues.  As far as I can tell, all the CrashContext.runtime-xml files attached to events have the proper `<LoginId>` field that we are supposed to be looking for.

This is the [Zendesk ticket](https://sentry.zendesk.com/agent/tickets/132870) which contains the user's org information.

**Comment by Fwang36** [comment]
The team took a look at this.  It turns out we are not looking at the `<LoginId>` when determining whether we create a user in the event or not.  We instead are looking at either the `<UserName>` field in the context file or whether the request payload to us contains a `UserId` parameter.

They also took a look at supporting the `<LoginId>` field if one of the other ones are missing and it should not be too much work.  

@redxdev would it be acceptable if we turn this issue into a feature request instead to support `<LoginId>`?  Then I can transfer the issue to our ingest repo.

**Comment by redxdev** [comment]
@Fwang36 oh weird, I guess Epic might have changed the behavior of that field at some point.

Yes, a feature request for adding support for LoginId would be good.
