### ISSUE TITLE
Request Volume Measurements for SDKs per Envelope Item Type

### ISSUE THREAD

**Issue by HazAT** [getsentry/relay#4160]
It would be amazing to know which SDK causes the most load on Relay related to incoming request volume and envelope items.  
Especially for "client side" SDKs like Browser JS, Mobile, and Gaming, the number of requests directly scales with the end user amount.  
In comparison to server SDKs, where everything is funneled through only a few outgoing SDKs and therefore is naturally limited. 

Like for example:

Nr. 1:
`sentry-javascript`, `envelope item: client_report`

Nr. 2:
`sentry-cocoa`, `envelope item: session`

Nr. 3:
`sentry-cocoa`, `envelope item: session & client_report`

The goal of this is to figure out if we can optimize some of our SDKs to more efficiently batch items in an envelope together to send fewer requests.

**Comment by Litarnus** [comment]
@HazAT Do we need to track metrics for all SDKs or would it be enough to take the top 20 or so?

**Comment by olksdr** [comment]
This seems like done, @Litarnus ? I'm closing this issue.
