### ISSUE TITLE
Sentry outages caused the buffers in the Sentry relay workers to fill up

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/relay#4177]
User reported the following: We use Sentry Relay (https://docs.sentry.io/product/relay/) to proxy events from our applications to Sentry.

On October 16th and 20th, Sentry had major outages which caused events to stop being processed:
https://status.sentry.io/

These outages caused the buffers in the Sentry relay workers to fill up. Since then, they have rejected all events and not sent anything to Sentry.

```
ERROR relay_server::endpoints::common: error handling request error=failed to queue envelope error.sources=[envelope buffer capacity exceeded]
```

Is there anything on the relay workers user can change to make them more resilient/recover from incidents better?

**Comment by jjbayer** [comment]
@kerenkhatiwada thanks for your report!

> These outages caused the buffers in the Sentry relay workers to fill up. Since then, they have rejected all events and not sent anything to Sentry.

Relay _should_ empty the buffer and start accepting requests again after the outage is resolved. Would you be able to share the exact Relay version, your `config.yaml` and Relay logs?

**Comment by liam-careerhub** [comment]
Hi @jjbayer, thanks for following up.
I was the customer @kerenkhatiwada  logged this issue for.

We host the relays on AWS ECS Fargate using the Docker image supplied by Sentry.
The specific image is: `getsentry/relay:24.2.0`

We are not using a customised `config.yml` and instead are configuring only with environment variables. We are setting:

* `RELAY_PUBLIC_KEY`
* `RELAY_HOST` to `0.0.0.0`
* `RELAY_ID`
* `RELAY_SECRET_KEY`

No other configuration is changed.

We have a health check running `curl -f http://localhost:3000/api/relay/healthcheck/ready/ || exit 1` which never failed, and therefore never stopped the backlogged worker.

The container has 8GB of ram and 4 vCPUs (standard fargate ones).

We usually run 2 containers/workers which handles general load fine.

Here are the logs:
[log-events-viewer-result.csv](https://github.com/user-attachments/files/17549492/log-events-viewer-result.csv)

Thanks for your help!

**Comment by jjbayer** [comment]
@liam-careerhub thank you for the details! I checked the code and I am unsure why Relay failed to free up space in your case, especially if it was able to reach the upstream again. Did a restart resolve the issue?

This is the code that raises the error: https://github.com/getsentry/relay/blob/a9cda1f32a729085981b38b9a9d2a058ffdc7ea9/relay-server/src/endpoints/common.rs#L346

This code path has since been replaced by [a simple memory check](https://github.com/getsentry/relay/blob/182a93e74f4a14c793dd187b8a5eaa9a0a53509a/relay-server/src/endpoints/common.rs#L355-L357), so it might be worth updating to the latest version.

**Comment by liam-careerhub** [comment]
I started some new containers which did resolve the communication to sentry, however the stuck containers never became unstuck, so I stopped them which unfortunately lost off of the events in their buffers.

Sure, I'll update the container image versions, hopefully that resolves it long-term.

Thanks for the help.

**Comment by jjbayer** [comment]
@liam-careerhub thank you, I'm sorry I couldn't be of more help here. Please reach out if this behavior reappears with the new version.
