### ISSUE TITLE
Timing metric for body extraction/reading the request body

### ISSUE THREAD

**Issue by Dav1dde** [getsentry/relay#4182]
We need a timer when reading the request body from the network. 

The metric should be created for all reads for all endpoints and it should be tagged with the endpoint and the body size (bucketed) if available. Implementation can be done through a custom extractor as described in the [axum docs](https://docs.rs/axum/0.7.7/axum/extract/index.html#wrapping-extractors).

**Comment by jan-auer** [comment]
We extract bytes in a lot of places in Relay, it's quite easy that we miss one of those in the future. Another way to achieve this is a middleware that wraps the request body and injects measurements (similar to the decompression middleware), though that will require more work to implement.

**Comment by Dav1dde** [comment]
Need to explore this a bit, with recent axum you can no longer change the Body/Request types. We'd need a custom body stream which times the reading, and a middleware to wrap the body - at this point we do have information about the route which should give the information we're interested in.
