### ISSUE TITLE
Authenticating to sentry.io

### ISSUE THREAD

**Issue by mans0954** [getsentry/relay#42]
In the README it says:

"At present Sentry requires the relays to be explicitly whitelisted by their public key. This is done through the SENTRY_RELAY_WHITELIST_PK config key which is a list of permitted public keys."

How does one register this public key with sentry.io, or otherwise authenticate the relay to that site?

Thanks.

**Comment by jan-auer** [comment]
That's not possible at the moment. We are still working on finalizing the first public preview of Relay and will offer a full UI for early adopters very soon, once we've ensured that it runs stable enough.
