### ISSUE TITLE
Identify dependency update that causes transaction processing regression

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#4301]
See https://getsentry.atlassian.net/browse/IA-27 for a list of candidates. The regression again happened with https://github.com/getsentry/relay/pull/4284 -> intersect both lists to narrow it down.

**Comment by loewenheim** [comment]
`old.txt` and `new.txt` are, respectively, the lists of dependencies of 57458159fa9c9171cee7a0020d1b35ba4420f66a (before #4284) and 9b39f40d8dde6bafffa584342a84906e178c7006 (after #4284). Generated with
```
❯ cargo tree --prefix none -e normal -e build --no-dedupe | sort | uniq
```
[new.txt](https://github.com/user-attachments/files/17937115/new.txt)
[old.txt](https://github.com/user-attachments/files/17937116/old.txt)
