### ISSUE TITLE
Breadcrumbs coming from wrong runtime

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/relay#4380]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which version of the SDK?

Unreal Upload Endpoint

### Steps to Reproduce

Upload two log files, breadcrumbs seem to be coming from the latter rather than the former.

### Expected Result

Breadcrumbs come from former file.

### Actual Result

Breadcrumbs come from the wrong file.

**Comment by gid-sentry** [comment]
More specific troubleshooting info available in https://getsentry.atlassian.net/browse/FEEDBACK-2112

**Comment by bruno-garcia** [comment]
Looks like this got dropped completely. The details on Jira might be helpful. It's useful to know which customer too.

**Comment by bruno-garcia** [comment]
This is related to `unreal.crashreporter` and not this plugin btw

**Comment by bitsandfoxes** [comment]
Based on the additional context this is a processing issue in relay. Depending on which order the logfiles get processed (i.e. alphanumerical?), different logs make it into breadcrumbs.

https://github.com/getsentry/relay/blob/1a56dbc5a0b8e5d0ab8b892b0eee097f7165e072/relay-server/src/utils/unreal.rs#L125

**Comment by Dav1dde** [comment]
@bitsandfoxes to summarize, the unreal crash can have multiple `UnrealLogs` items but Relay just processes a single one?
