### ISSUE TITLE
Requirement to have a license key to download GeoLite2-City.mmdb

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/relay#527]
A successful run of `make test` requires a file `GeoLite2-City.mmdb`. This file is downloaded through a make target that requires the `GEOIP_LICENSE` environment variable set.

Failure to set the env var to a proper value creates an empty `GeoLite2-City.mmdb` file which satisfies the build in the next run of `make test`.

The tests depend on a non-empty file, though, and fail.

As a side-effect, PRs from external contributors cannot build successfully in Travis, e.g. https://travis-ci.com/github/getsentry/relay/jobs/299613662
```
$ make -e test-rust-all
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    20  100    20    0     0     83      0 --:--:-- --:--:-- --:--:--    83
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Makefile:206: recipe for target 'GeoLite2-City.mmdb' failed
```

Investigate and reconsider this dependency, perhaps replacing with something more easily available and with an open source license.

**Comment by untitaker** [comment]
Initially this didn't require GEOIP_LICENSE as variable IIRC. It's probably worth taking a look at what the maxmindb crate (or other geoip libs) use for testing. Some of them are just C wrappers though
