### ISSUE TITLE
Fragile clock drift correction

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/relay#534]
_From https://github.com/getsentry/relay/pull/526#discussion_r395376450_

@jan-auer wrote:

> @untitaker clock drift correction looks extremely fragile. It should use a timestamp of when the event was received, not when the processor runs (now). Since we can have arbitrary delays inside Relay due to project config fetching, this can massively skew the clock -- more than what's expected from usual clock skew. This means, the TransactionsProcessor should always receive sent_at and also received_at instead of now.
>
> Also, doing clock drift correction with the end timestamp probably does more harm than it helps. We cannot assume that the transaction is sent immediately after it's complete (especially if we want to start batching up in the SDK).

**Comment by rhcarvalho** [comment]
_From https://github.com/getsentry/relay/pull/526#discussion_r395515196_

**Comment by jan-auer** [comment]
> But that's precisely why the sent_at parameter exists. It is eventually supposed to be passed by the SDK (we didn't impl that part yet), and is supposed to tell Relay what the SDK thinks is the current time. The difference between sent_at and now/received_at is our skew.

That makes sense. To sum this up, the behavior should be:
- If `sent_at` is not set, do not perform clock drift correction as this skews too much. **Edit**: Do not backfill with the event timestamp.
- Fix SDKs to always include `sent_at`. We will require Envelope submission soon, so this change is feasible. Clock drift correction is a vital feature, but is not required for correctness of error events.
- Use the `start_time` instant as received timestamp. This is already collected in Relay.
- Compare `sent_at` with `started_time` for clock drift correction. We can convert `start_time` to a `SystemTime` at the time of normalization for best results.
- A drift smaller than a few seconds (configurable) should not be corrected, as it is most likely just a networking delay.
- Timestamps to correct should be start&end timestamps, span timestamps, breadcrumbs.
- Clock drift correction needs to run before timestamp validation (we throw away timestamps older than 30 days).
- If clock drift correction applies, we set an annotation on the event's timestamp (once).
- The minimum drift for clock drift correction will be ~1h.

@rhcarvalho @untitaker do you concur with this?

**Comment by untitaker** [comment]
Where do we get the idea from that backfilling `sent_at` with `now()` skews too much? I think it's a very reasonable assumption that most of the SDKs send the transaction when it is over, as that's what all SDKs do right now. I would argue that delayed event submission is the special case.

**Comment by untitaker** [comment]
also gotta rope @mitsuhiko @HazAT into this one as I discussed this logic with them at the time.

**Comment by jan-auer** [comment]
Please also see the comments at #535

**Comment by jan-auer** [comment]
> Where do we get the idea from that backfilling sent_at with now() skews too much? 

It does not if we fill at the right place. This right place is when receiving the event, making it equal to the `received_at` timestamp, in which case clock skew is canonically `0`. If we fill it later, then we're only correcting by Relay's internal delays. 

If the actual question you're asking is why we don't fill `sent_at` with `event.timestamp`: This is based on the assumption that we cannot trust the event timestamp, since the SDKs have arbitrary delays between recording and sending an event. See `native`, where the events are buffered on disk and sent on restart.

**Comment by untitaker** [comment]
>It does not if we fill at the right place.

Okay, right, that's my impression as well 👍

**Comment by rhcarvalho** [comment]
> do you concur with this?

While I extracted the conversation from #526, I don't have much insight on this with the limited information I have.

> Clock drift correction is a vital feature

Why is it vital?
What are we trying to achieve here? Do we have a design I can refer to?

If the idea is to compare timestamps from client and server, it does not sound like a sound algorithm for clock drift correction.

**Comment by rhcarvalho** [comment]
> To sum this up, the behavior should be:
> 
> * If `sent_at` is not set, do not perform clock drift correction as this skews too much. **Edit**: Do not backfill with the event timestamp.

:+1: 

Agree, the event may have been sent any time after it happened. We cannot assume `time.timestamp` is related to when the event was sent.

---

> * Fix SDKs to always include `sent_at`. We will require Envelope submission soon, so this change is feasible. Clock drift correction is a vital feature, but is not required for correctness of error events.

Not familiar with envelopes yet. From my research this is not sent by the JS SDK yet.


---

> * Use the `started_time` instant as received timestamp. This is already collected in Relay.

:+1: 

Didn't find it with the name `started_time` in the code base.
Probably you meant `ProcessEnvelope.start_time`:

https://github.com/getsentry/relay/blob/68e105bdaeb22e2301f4c76129e0d1e42d76311e/relay-server/src/actors/events.rs#L729-L733

That indeed seems better than `Utc::now()` when calling `TransactionsProcessor::new`.

---

> * Compare `sent_at` with `started_time` for clock drift correction. We can convert `started_time` to a `SystemTime` at the time of normalization for best results.

I see where it is going, if multiple clients are sending transactions that are part of the same trace, they may come with skewed clock readings. This normalization can try to give a more consistent view of what actually happened.

On a fine grained level, the problem with this is that it ignores the time it takes from a request to travel from client to server. Different requests will have a different latency, and the server-side normalization could theoretically make things worse than they would be if the multiple clients had their clocks synchronized (by means external to Sentry -- e.g. plug them all to the same NTP source).

**Comment by jan-auer** [comment]
Thanks. Seems like we are in general agreement. 

> the problem with this is that it ignores the time it takes from a request to travel from client to server

Excellent point. I remember that this was raised in the initial discussions around this feature and was accepted. However, we can mitigate this by only run clock drift correction, if the drift is larger than a certain amount (e.g. `5s`). Let's add this configurably, too.

Let's close discussion on this for now and implement the changes based on https://github.com/getsentry/relay/issues/534#issuecomment-601669487. Thanks everyone for participating!

**Comment by mitsuhiko** [comment]
That's why originally we only wanted to do drift correction if we have more than a threshold (and the proposal was actually hours and not seconds). All the points brought up are correct.

The drift correction is only really necessary/useful for clients with clocks completely out of sync (eg: wrong hour/date) as otherwise the correction makes matters worse.

**Comment by HazAT** [comment]
We had a call and decided to move `sent_at` into the envelope header.
Reasons:
- In the future, we will eventually only send envelopes
- Until envelope sending is implemented in JS we keep it as it is

**Comment by JeanMertz** [comment]
I didn't read through this thread in detail, but I came here searching for an issue where my millisecond and nanosecond breadcrumb timestamps (formated as a Unix timestamp integer with millis or nanos added) are being rejected by the Sentry API (regular Unix timestamps in seconds work as expected).

After verifying that my timestamps are correct, my mind drifted towards clock skew, which was how I found this issue.

Here's what the API injected into the raw JSON:

```json
  "_meta": {
    "breadcrumbs": {
      "values": {
        "0": {
          "timestamp": {
            "": {
              "val": 1585983484747,
              "err": [
                [
                  "invalid_data",
                  {
                    "reason": "timestamp out of range"
                  }
                ]
              ]
            }
          }
        }
      }
    }
  }
```

If this isn't related, I'll file a separate issue (assuming I'm not doing anything incorrectly).

This is using the Go SDK.

**Comment by untitaker** [comment]
@JeanMertz your timestamp is milliseconds, please divide by 1000

**Comment by rhcarvalho** [comment]
@JeanMertz your issue is unrelated to the discussion here. I've cut https://github.com/getsentry/sentry-go/issues/190 to discuss/track that. In short, when sending a numeric value, the server treats it as seconds since the UNIX epoch. Please let's continue the conversation in the new issue.
