### ISSUE TITLE
Document Event.Exception.RawStacktrace

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/relay#549]
The [SDK development docs](https://docs.sentry.io/development/sdk-dev/event-payloads/exception/) mentions the `stacktrace` attribute, but not `raw_stacktrace`.

The [source code documentation](https://github.com/getsentry/relay/blob/1f0d5f8fab5fb64c4d882a001853ed5bdbaf1759/relay-general/src/protocol/stacktrace.rs#L181-L198) also doesn't do much explaining the intentions and differences.

SDK developers would benefit from having this part of the protocol documented.

**Comment by untitaker** [comment]
SDK developers are not supposed to set this attribute so I would not like to document this in SDK dev docs, but the code comments do need some love. We only have this: https://github.com/getsentry/relay/blob/1f0d5f8fab5fb64c4d882a001853ed5bdbaf1759/relay-general/src/protocol/exception.rs#L27

After server-side processing, the old SDK-provided stacktrace is backend up in this attribute

**Comment by rhcarvalho** [comment]
> SDK developers are not supposed to set this attribute

I didn't know. For whatever reason, this field is defined and exported (public) in the Go SDK causing unnecessary confusion.

**Comment by jan-auer** [comment]
@untitaker We can take a pass through both sentry-docs (again 😄)and the protocol, to explicitly mark all fields as required, recommended or optional. Additionally, we can also qualify which attributes are for internal use only. 

I'm thinking at least along the lines of how we documented outcomes (here it declares where an outcome is emitted):
https://github.com/getsentry/relay/blob/1f0d5f8fab5fb64c4d882a001853ed5bdbaf1759/relay-server/src/actors/outcome.rs#L80-L82

**Comment by untitaker** [comment]
Do you want to document culprit, title and Metadata as well? I considered them out of scope in principle, but in any case i see them in the same bucket as raw_stacktrace

**Comment by jan-auer** [comment]
The rule in the past was that we do not document internal attributes in external docs. Culprit, for example, was explicitly removed because it is no longer considered public API. 

I would propose we mark all fields in Relay, and we ensure that this is also reflected in docs for all attributes that are not internal.

**Comment by RaduW** [comment]
I would propose to put all internal fields in an `internal` object, an internal object can appear at any level.
Anything under a field `internal` is ... internal and shouldn't be messed with by any SDK, similar to internal 
packages in Go ( this should please Rodolfo).

**Comment by jan-auer** [comment]
Putting them in objects would be challenging, but we can have an annotation that is parsed and rendered in documentation, up to the point that we hide it in some places.

**Comment by RaduW** [comment]
Sure documenting it would help and would be easier that adding another sub-object any time you need some "private" fields. I still believe that serializing internal fields in an `internal` sub object would make it universally clear (whether you are looking at the structure definition, the structure usage, the serialized object or the documentation).
