### ISSUE TITLE
contexts.device.timezone normalization issue

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/relay#643]
While implementing https://github.com/getsentry/sentry-dotnet/pull/457 I noticed an issue:

![image](https://user-images.githubusercontent.com/1633368/86076332-e1b6dc00-ba57-11ea-8e9a-f0fc634fee83.png)

Is this a org-wide normalization rule someone added?

Just to confirm, is there a validation to the format? Since `Toronto/Eastern` would come from a unix-like but that format isn't what is reported from Windows devices.

**Comment by jan-auer** [comment]
Confirming that this is a PII stripping rule.
