### ISSUE TITLE
Auto start while restart in Ubuntu.

### ISSUE THREAD

**Issue by starofsky** [getsentry/relay#945]
I run stand alone relay in Ubuntu and connect to Sentry/onpremise. 
How can I start relay while reboot server?

Thanks.

**Comment by BYK** [comment]
Hi,

This is not something Relay can do for you. I think this answer would help you: https://askubuntu.com/questions/9382/how-can-i-configure-a-service-to-run-at-startup

Closing as this is not relevant to Relay repo.
