### ISSUE TITLE
Allow specifying mode through argument or environment variable

### ISSUE THREAD

**Issue by spawnia** [getsentry/relay#963]
I would like to be able to specify the mode without usage of a configuration file to simplify my deployment, see https://github.com/getsentry/relay/issues/962#issuecomment-806527192. For example:

    docker run getsentry/relay run --mode=proxy

**Comment by olksdr** [comment]
This is already possible 

```bash
> docker run --rm getsentry/relay run --help                         

relay-run 23.1.1
Run the relay

USAGE:
    relay run [OPTIONS]

OPTIONS:
.....
        --mode <MODE>
            The relay mode to set [possible values: managed, proxy, static]
.....
```

The mode can be provided through the ENV variables and through the command line arguments.
