### ISSUE TITLE
Specify all configuration values through environment variables

### ISSUE THREAD

**Issue by spawnia** [getsentry/relay#964]
Follow up from https://github.com/getsentry/relay/issues/962.

As clarified by @RaduW in https://github.com/getsentry/relay/issues/962#issuecomment-806521178, some configuration values are available as environment variables, while others are not. That circumstance makes this configuration option a dead end: configuring a subset of values works fine, but once an unsupported option is required, one would have to rewrite their configuration completely.

In order to make the configuration both consistent and feature-complete, I propose to add the option to specify all configuration values available in the config file through environment variables. For ease of discovery, i propose to mirror the config path from the yaml options like this:

    relay.mode -> RELAY_MODE
	limits.max_attachment_size -> LIMITS_MAX_ATTACHMENT_SIZE

**Comment by untitaker** [comment]
I believe we have tried to do this in a generic way and failed to implement this in Rust (or rather concluded it would require metaprogramming which we did not want to invest the time into)

**Comment by spawnia** [comment]
I currently count 50 configuration options at https://docs.sentry.io/product/relay/options/. While annoying and repetitive, typing them out by hand does not seem all that bad. Would you accept a PR for that?

**Comment by untitaker** [comment]
@spawnia not sure how good that will look, and how easy it would go out of sync. I'm tempted to say no tbh. Perhaps somebody else has a better idea on how to abstract this well in code so I think we should keep this issue open regardless.

**Comment by RaduW** [comment]
While the proposed idea was previously discussed, implementing it in a generic and clean way is a bit more complicated.

There are configurations that accept arrays, like the configuration for Kafka parameters and configs that accept maps, like 
metrics, which would make the associated command line arguments and environment variables quite messy. 

There is also the problem of escaping the values provided in a command line argument.

The work involved in cleanly implementing & documenting and testing a comprehensive solution was not justified.

We do accept PRs if they pass our quality standards but we cannot guarantee that any particular PR is going to be accepted.

**Comment by spawnia** [comment]
I see your concerns and agree that there needs to be a balance between the usefulness of this feature and the implementation effort and maintenance burden. Perhaps we can develop an idea that strikes a good middle ground.

Configuration values could simply be parsed as YAML or JSON (a subset of YAML), which would solve the problem of passing complex values through strings.

	METRICS_DEFAULT_TAGS='{"foo": "bar", "baz": 42}'

**Comment by jan-auer** [comment]
This is not a commonly requested feature, so I'll close this issue in an effort to reduce the number of open issues. We're happy to accept a PR for this as long as it doesn't manually list all configured options (to avoid duplication).
