### ISSUE TITLE
Allow usage of TLS for redis connection

### ISSUE THREAD

**Issue by BlackWebWolf** [getsentry/relay#995]
We are trying to make setup of relay secure, as a part of sentry kubernetes deployment.
And apart from Kafka ssl problems (seen in https://github.com/getsentry/relay/issues/971), 
we are facing problems with connecting via tls to redis. 
It should be simple change - https://github.com/getsentry/relay/blob/master/relay-redis/Cargo.toml#L15 should also include TLS (exactly  `features = ["tls"]`)
Do You confirm that this is possible or will it brake another part of development as kafka did?

**Comment by jan-auer** [comment]
With cargo's new feature system this can now make this an optional feature.
